### ISSUE TITLE
The ibmq_lima seems very slow

### ISSUE THREAD

**Issue by DevelopDaily** [Qiskit/qiskit-ibm-runtime#101]
I run a circuit that contains a single `x` gate with 1 shot on the `ibmq_lima`. Here is the result. Could you please help interpret it?

![1gate-1shot](https://user-images.githubusercontent.com/54299975/149458010-f9419c8a-6f79-4a23-8f00-d77dfd935b33.png)

What is the difference between "_Running: 6.2s_" and "_time in system 2.1s_"?

Does it seem very slow to take 2.1 seconds to run a single shot?

I assume the `2.1s` is perhaps some sort of fixed cost. I also run 1000 shots. It takes `2.4s`. If my assumption is correct, it would take `ibmq_lima (2.4 - 2.1 = 0.3s) `to complete 1000 shots. That is still 2000 times slower than a classical simulator running on my cheap laptop.

I read this paper here: https://arxiv.org/abs/2110.14108, but that paper does not have a lot of real life examples. Is it possible to apply the theories presented in that paper to my example presented above?

I hope you would provide some practical benchmarks in the future. For example, you may benchmark some well-known algorithms: Shor, QFT, QPE, ground state energy, etc., on your real quantum hardware. Benchmarking them that way may not sound rigorous, but it may be more useful to average users such as a scientist, an engineer, etc.

**Comment by daka1510** [comment]
@DevelopDaily thanks for reaching out. Please raise this question in [Stack Exchange](https://quantumcomputing.stackexchange.com/questions/tagged/ibm-q-experience).

FYI: Other available options to get help from the Support team or the community are listed at https://quantum-computing.ibm.com if you hover the help icon in the upper right corner.
