### ISSUE TITLE
Don't upper-case RuntimeJob status reason

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-ibm-runtime#1011]
**Describe the bug**

The reason in the job status error message gets upper-cased here:

https://github.com/Qiskit/qiskit-ibm-runtime/blob/0.11.3/qiskit_ibm_runtime/runtime_job.py#L462

Which results in an error message like this:

`Job cj9uqfge5q8gtki5uuag has failed: SESSION CJ9UQF0E5Q8GTKI5UU4G HAS BEEN CLOSED`

Why does the reason need to be upper-cased like that? It sort of feels like being yelled at. 😄 

I see where the code is comparing the reason against `RAN TOO LONG` in a few places to check for timeout, but I'd argue you could replace those checks with an `is_timeout` function and leave the reason in the format it's returned from the server.

**Steps to reproduce**

Check the error message on any job which timed out or failed because the session it was in closed before the job could run.

**Expected behavior**

The reason string should be left in the potentially mixed case as it came back from the server rather than arbitrarily upper-cased on the client side.

**Suggested solutions**

See above - if you need case insensitive comparisons, do that in some utility code, don't modify the actual reason string that the user sees.

**Additional Information**

- **qiskit-ibm-runtime version**: 0.11.3
- **Python version**: 3.8
- **Operating system**: Ubuntu Focal

**Comment by merav-aharoni** [comment]
@kt474 , @jyu00 - do you agree to remove the uppercase for the status reason? If so, I'll be happy to do this.

**Comment by kt474** [comment]
Yes we can remove the uppercase - we should wait until https://github.com/Qiskit/qiskit-ibm-runtime/issues/989 first (or at the same time) because right now we are still checking for the hard coded value of `RAN TOO LONG`
