### ISSUE TITLE
Remove `qiskitrc` related code 

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit-ibm-runtime#1023]
In https://github.com/Qiskit/qiskit-ibm-runtime/pull/370 we added a way for users to automatically copy/use their old credentials from `qiskit-ibmq-provider` in this repo. `qiskit-ibmq-provider` is now fully deprecated so we no longer need this functionality. 

The `qiskitrc` file credentials were copied over to the new `qiskit-ibm.json` credentials file.

**Comment by mtreinish** [comment]
Is there actively a reason we **need** to do this? I feel like leaving the backwards compatibility code in place makes sense since just because we've archived the ibmq project doesn't mean people aren't using it still. Especially since it's still installable and will work.

**Comment by merav-aharoni** [comment]
I find it confusing from a developer's perspective. I actually used `_QISKITRC_CONFIG_FILE` in an issue I am working on now, and it took me a while to realize my mistake.
I think we should at least add a comment in the code not to use this. And I think we should deprecate it at some point in the future.

**Comment by jyu00** [comment]
> Is there actively a reason we **need** to do this? I feel like leaving the backwards compatibility code in place makes sense since just because we've archived the ibmq project doesn't mean people aren't using it still. Especially since it's still installable and will work.

People using ibmq-provider can still use `qiskitrc`. I think the proposal here is to just stop using `qiskitrc` in `qiskit-ibm-runtime` (not deleting it), since it moved to the new file over a year ago. 

> And I think we should deprecate it at some point in the future.

I thought it was deprecated (with a deprecation warning) when we moved to the json file? 😅

**Comment by merav-aharoni** [comment]
There was a notification on this in https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/releasenotes/notes/0.1/account-management-b9908e0b62dc1d81.yaml. However, I didn't see a relevant deprecation message in the code. Much of the `qiskitrc` related code was removed as far back as 2021. It seems we only have some leftovers now. 
Do you think we still need to issue a deprecation warning on this, or is it safe to simply remove the related code? @kt474 , @jyu00 .
