### ISSUE TITLE
Qiskit Runtime Sampler , sampler not taking the argument "backend"

### ISSUE THREAD

**Issue by sirgeorgesawcon** [Qiskit/qiskit-ibm-runtime#1033]
### Environment

- **Qiskit Terra version**:  0.22.2
- **Python version**:  3.8.1
- **Operating system**: Win10

### What is happening?

Following the Qiskit tutorial on sampler : https://qiskit.org/ecosystem/ibm-runtime/tutorials/how-to-getting-started-with-sampler.html

while invoking the Qiskit runtime sampler, with any backend (backend = `ibmq_qasm_simulator`) and then running the 

`sampler = Sampler(backend=backend)`

gives the error: TypeError: Sampler.__init__() got an unexpected keyword argument 'backend'

It should not happen,  since the sampler function in qiskit takes in the following input
![screenshot_2023-08-22_at_15-25-46_qiskit_ibm_runtime sampler_____qiskit_runtime_ibm_client_0 11 4_documentation](https://github.com/Qiskit/qiskit/assets/63145298/d7e8bfb7-a82e-4aad-bf38-77fa172912b7)

but here it's flagging `backend` as unexpected keyword

### How can we reproduce the issue?

```  from qiskit_ibm_runtime import QiskitRuntimeService

service = QiskitRuntimeService(channel="ibm_quantum")
backend = service.backend("ibmq_qasm_simulator")

from qiskit_ibm_runtime import Sampler

sampler = Sampler(backend=backend)

```

### What should happen?

**Sampler** should take in the `backend` and then when executed with a quantum circuit *qc* should return the job results.

**Comment by 1ucian0** [comment]
It seems to be a problem related with an out-of-sync version of `qiskit-ibm-runtime`. What's your `qiskit-ibm-runtime` version?

```
from qiskit_ibm_runtime import __version__
print(__version__)
```
If lower than `0.11`, consider updating your package `pip install -U qiskit-ibm-runtime`

**Comment by sirgeorgesawcon** [comment]
Hi @1ucian0 , it worked, thanks for helping

**Comment by sirgeorgesawcon** [comment]
It's again giving the same issue: 
![Screenshot 2023-08-25 151349](https://github.com/Qiskit/qiskit-ibm-runtime/assets/63145298/018a957c-6a5b-49ef-bd7a-21a9b1cdfcc5)

**Comment by jyu00** [comment]
@sirgeorgesawcon Where did you import that `Sampler` from? The tutorial first shows how to use Sampler from Qiskit (terra) by first doing `from qiskit.primitives import Sampler`. Then later it shows [using Qiskit Runtime Sampler](https://qiskit.org/ecosystem/ibm-runtime/tutorials/how-to-getting-started-with-sampler.html#3.-Initialize-the-Qiskit-Runtime-Sampler) by first doing `from qiskit_ibm_runtime import Sampler`. 

`qiskit.primitives.Sampler` doesn't accept `backend` as an input argument.

**Comment by sirgeorgesawcon** [comment]
![Screenshot 2023-08-28 114946](https://github.com/Qiskit/qiskit-ibm-runtime/assets/63145298/283340cf-db1b-4a78-9dec-5df0c0dff151)
 This is how I'm importing `Sampler`

**Comment by kt474** [comment]
@sirgeorgesawcon if you're using the latest version of `qiskit-ibm-runtime`, the following code snippet should work - as mentioned in the comment above, I believe you're not actually using the `Sampler` imported from `qiskit_ibm_runtime` but using the `Sampler` imported from `qiskit.primitives`. 

```python
from qiskit_ibm_runtime import QiskitRuntimeService, Sampler

service = QiskitRuntimeService(channel="ibm_quantum")
backend = service.backend("ibmq_qasm_simulator")

sampler = Sampler(backend=backend)

```

**Comment by sirgeorgesawcon** [comment]
Hi, Yes, It is running perfectly now, thanks, The issue was that in the big file of imports, I was importing `sampler` twice, first from runtime and second from `aer`. Now it's working fine. But the `sampler` from `aer` gives a different result than `sampler` from `runtime`. 

I understand that `sampler` from `aer` is running on my local machine, and `sampler` from `runtime` is running on IBM cloud and specifically `ibm_qasm_simulator`, given the Qasm Simulator is noise free simulator, both the results should be the same, But the `aer` sampler gives the result that matches with the classical and `runtime` sampler gives different result than that.
