### ISSUE TITLE
Use proper defaults for Q-Ctrl path

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1049]
**What is the expected feature or enhancement?**

Similar to #1048, proper defaults should be used when Q-Ctrl strategy is selected, so that users don't get any warnings/errors when using the default settings on the Q-Ctrl path. 

**Acceptance criteria**

Proper defaults are set when using Q-Ctrl strategy. 

@eginez, do you mind taking on this one? Since you know what would pass validation 🙂

**Comment by jyu00** [comment]
I think this one is done?

**Comment by kt474** [comment]
Done in #1027
