### ISSUE TITLE
qiskit.opflow is deprecated

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-ibm-runtime#1057]
**Describe the bug**

The module `qiskit.opflow` is used by [`qiskit.opflow` was deprecated in Qiskit 0.43](https://qiskit.org/documentation/release_notes.html#quantuminstance-opflow-and-algorithms-usage-deprecation) (released on 2023-05-04) and will be removed eventually. The migration guide can be found in https://qisk.it/opflow_migration.

**Steps to reproduce**

The grep results in two instances of qiskit.opflow usage:
```sh
grep -ri '\<opflow\>' qiskit_ibm_runtime test
```
```
qiskit_ibm_runtime/estimator.py:from qiskit.opflow import PauliSumOp
test/unit/test_data_serialization.py:from qiskit.opflow import (
```

**Expected behavior**

The usage of `qiskit.opflow` needs to be migrated to [`quantum_info`](https://qiskit.org/documentation/apidoc/quantum_info.html#module-qiskit.quantum_info) or removed in order to continue running with coming Qiskit releases.

**Suggested solutions**

With the help of  https://qisk.it/opflow_migration, migrate to `qiskit.quantum_info`.

**Comment by kt474** [comment]
fixed by #1085, feel free to reopen if something else needs to be done
