### ISSUE TITLE
Packages needed for development

### ISSUE THREAD

**Issue by gluonhiggs** [Qiskit/qiskit-ibm-runtime#1080]
**What is the expected feature or enhancement?**
As I understand, all packages mentioned in `requirements-dev.txt` are neccessary for the development of the `qiskit-ibm-runtime`. If so, there are packages that needs to be added.

**Acceptance criteria**
add these lines to `requirements-dev.txt`
```txt
qiskit_algorithms==0.2.0
qiskit-ibm-provider>=0.7.0
ibm-platform-services>=0.22.6
```

**Comment by gluonhiggs** [comment]
Yeah. My bad. I was writing a program using SPSA, therefore it needs qiskit_algorithms.
Tbh, the packages I mentioned are from requirements.txt. What is the purpose of requirements-dev.txt here?

**Comment by kt474** [comment]
Generally, requirements for an actual project are in `requirements.txt` while requirements that are needed only for testing or development are put into `requirements-dev.txt`
