### ISSUE TITLE
Usage is measured in "seconds" not in "quantum_seconds"

### ISSUE THREAD

**Issue by raulotaolea** [Qiskit/qiskit-ibm-runtime#1087]
**What is the expected feature or enhancement?**

_Qiskit Runtime usage_, or just _usage_, is defined [here](https://qiskit.org/ecosystem/ibm-runtime/cloud/cost.html#view-instance-cost) or [here](https://qiskit.org/ecosystem/ibm-runtime/cloud/plans.html#pricing-overview) as:

> Usage: Qiskit Runtime used by this job. This usage is the time counted by Qiskit Runtime to process a job, and is determined by the use of internal resources.

but in the API related with estimations, e.g. [RuntimeJob.usage_estimation](https://qiskit.org/ecosystem/ibm-runtime/stubs/qiskit_ibm_runtime.RuntimeJob.usage_estimation.html#runtimejob-usage-estimation), we are returning `quantum_seconds` instead of just `seconds`. All measures related with Qiskit Runtime must be `seconds`.

**Acceptance criteria**

Everything related with Qiskit Runtime usage (real or estimated) must be _seconds_. In a [quick search in this repo](https://github.com/search?q=repo%3AQiskit%2Fqiskit-ibm-runtime+quantum_seconds&type=code) I found 4 places where we say `quantum_seconds` instead of just `seconds`.

**Comment by mberna** [comment]
@raulotaolea have you reached a conclusion for this?

**Comment by jyu00** [comment]
Closing since `quantum_seconds` was ok again
