### ISSUE TITLE
Fix failing unit tests, fail on deprecation warning qiskit/main

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit-ibm-runtime#1097]
We run our unit [tests](https://github.com/Qiskit/qiskit-ibm-runtime/actions/workflows/unit-tests-terra-main.yml) on a nightly cron job again the main branch of qiskit (terra)

- [x] check/fix all failing tests 
- [x] check/fix all deprecation warnings - we should also fail the test on deprecation warning 

cc @1ucian0 @drew-distefano

**Comment by kt474** [comment]
Reopening because 2 tests are still failing 

https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/6263642457/job/17008487156#step:5:839

`test_coder_qc`
```
NotImplementedError: This gate class <class 'qiskit.circuit.library.standard_gates.h.HGate'> does not support manually setting a condition on an instance. Instead you must set the label when instantiating a new object or via the .c_if() method
```

`test_unsupported_values_for_sampler_options`

```
AssertionError: 'resilience_level' not found in 'The 0-th circuit does not have Measure instruction. Without measurements, the circuit cannot be sampled from.'
```

**Comment by drew-distefano** [comment]
@kt474 please investigate (and implement?) alerts via slack or other method on failing tests so we don't have to manually check the results every day

**Comment by kt474** [comment]
> @kt474 please investigate (and implement?) alerts via slack or other method on failing tests so we don't have to manually check the results every day

Set up email alerts for failing tests, now just need to fail on deprecation warnings
