### ISSUE TITLE
Backend.max_circuits gives "maximum # of circuits for all instances", not for the chosen one.

### ISSUE THREAD

**Issue by mchan90** [Qiskit/qiskit-ibm-runtime#1104]
**Describe the bug**

I used qiskit-ibm-runtime with multiple instances with different maximum circuits allowed. For some reason, I chose one of instance to use. It seems applied well. But, when I call Backend.max_circuits, it gives maximum # of circuits allowed over all instances I have, not the instnace I chose. For example, If I have two instances A and B that allow 300 circuits and 100 circuits, max_circuits gives 300, even if I choose instance B. 

Maybe this is intended, not a bug. But it is confusing. I have to visit the IBM quantum webpage, to check real max_circuits. I suggest to modify Backend.max_circuits to give "maximum # of circuits for chosen instance"

**Steps to reproduce**

1. Prepare IBM account with multiple instance, with different max_circuits.
2. Specify instance for service or backend.
3. call Backend.max_circuits

**Expected behavior**

gives # of maximum circuits for chosen instance.

**Suggested solutions**

add a instance filtering procedure in max_circuit routine.

**Additional Information**

- **qiskit-ibm-runtime version**:0.12.1
- **Python version**:3.10.12
- **Operating system**: WSL 2

**Comment by kt474** [comment]
Hi @mchan90 the `_max_circuits` property is tied to the backend configuration. The backend configuration may have a max circuits value higher than the allowed value in the instance. The max circuits value for an instance is independent of the max circuits value in a backend configuration.
