### ISSUE TITLE
Fix `jupyter` and `visualization` modules within `qiskit_ibm_runtime`

### ISSUE THREAD

**Issue by daka1510** [Qiskit/qiskit-ibm-runtime#111]
**Problem**
@jyu00 noticed that the `jupyter` and `visualization` modules within `qiskit_ibm_runtime` may not work. Prior to the first release (Runtime 0.1) we need to ensure they are functional, or are not referenced in the public documentation.

**Acceptance criteria**
- Option 1) Both modules are documented and working
- Option 2) The modules are not documented in the initial release and follow-up efforts are tracked

**Comment by jyu00** [comment]
There were [tests](https://github.com/Qiskit-Partners/qiskit-ibm/blob/main/test/ibm/test_jupyter.py) on some of the methods in these modules. Some manual testing would probably be necessary as it's a jupyter widget.

**Comment by daka1510** [comment]
Starting point for manual tests: https://github.com/Qiskit/qiskit-ibmq-provider/blob/master/docs/tutorials/2_jupyter_tools.ipynb

**Comment by daka1510** [comment]
I chose option 2 for the Runtime 0.1 release.

- references in the public API documentation have been removed
  - via https://github.com/Qiskit/qiskit-ibm-runtime/pull/123
- follow-up efforts for the two modules are tracked (added more details and thoughts to the referenced issues)
  - via https://github.com/Qiskit/qiskit-ibm-runtime/issues/112
  - via https://github.com/Qiskit/qiskit-ibm-runtime/issues/124
