### ISSUE TITLE
Revive IQX dashboard widget

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#112]
**What is the expected feature or enhancement?**

In qiskit-ibmq-provider there was an IQX dashboard that displayed backends as well as legacy jobs. It'd be nice to have something similar, especially for cloud runtime since they don't show up on IQX. 

**Acceptance criteria**

A user can see runtime backend and job information on a dashboard.

**Comment by daka1510** [comment]
**Related background information**
- The IQX dashboard widget is implemented via the [jupyter](https://github.com/Qiskit/qiskit-ibm-runtime/tree/main/qiskit_ibm_runtime/jupyter) and [visualization](https://github.com/Qiskit/qiskit-ibm-runtime/tree/main/qiskit_ibm_runtime/visualization) modules.
- I have removed it from the public API documentation of qiskit-ibm-runtime via this [PR](https://github.com/Qiskit/qiskit-ibm-runtime/pull/123).
- Its usage in qiskit-ibmq-provider is documented in this [notebook](https://github.com/Qiskit/qiskit-ibmq-provider/blob/master/docs/tutorials/2_jupyter_tools.ipynb)
  - when a user runs the Jupyter magic command (`%iqx_dashboard`), below dashboard is shown
![image](https://user-images.githubusercontent.com/16404496/151133188-238bc3b5-bbb0-4cae-ac3d-9250040746a4.png)
![image](https://user-images.githubusercontent.com/16404496/151133269-245a1e9e-dc52-4fd6-8f99-f0d4104cfca3.png)

**Open Questions**
Some initial questions we may want to clarify when we pick up this work item:
1. Should the name stay as-is?
1. Should it work transparently across Cloud (https://cloud.ibm.com/) and Legacy (https://quantum-computing.ibm.com/)?
1. Are the hard-coded device layouts up to date and complete?
1. What are reasons and benefits for implementing a dashboard _widget_ within the client library vs. implementing and linking to a dedicated UI?

**Comment by jyu00** [comment]
My 2 cents:
1. No, we should not be using `IQX` anymore. We can change it to something like `Qiskit Runtime Dashboard`
2. I think it's ok to have separate tabs for cloud and legacy jobs
3. I don't know if we even need to display backends, since there are dedicated UI for that on both IQX and cloud (but not for jobs). 
4. Linking is probably good enough.
