### ISSUE TITLE
[Doc] Docs still mention session data being cached

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1122]
**Describe the bug**

Various tutorials, docstrings, etc still mention that session data is cached (for example, [here](https://qiskit.org/ecosystem/ibm-runtime/tutorials/how-to-getting-started-with-estimator.html#Session) and [here](https://qiskit.org/ecosystem/ibm-runtime/stubs/qiskit_ibm_runtime.Sampler.html#qiskit_ibm_runtime.Sampler)). This hasn't been true since we removed data caching a while ago (due to performance problem), so the doc should be updated. 

[This page](https://qiskit.org/ecosystem/ibm-runtime/sessions.html#benefits-of-using-sessions) also says 

`Since data from the first session job is cached and used by subsequent jobs, if the first job is cancelled, subsequent session jobs will all fail.`

There is no data caching, and subsequent session jobs won't fail. _However_, this behavior is expected to change at end of Oct, so it may need to be updated again if this fix comes first. 

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by daredevil3435** [comment]
I want to work on this. I am just starting with documentation but I want to get into code section as well. Please guide me about how do I get started and all.
