### ISSUE TITLE
Passing datetime to backend.properties doesn't work

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1127]
**Describe the bug**

Passing `datetime` to `backend.properties()` raises `NotImplementedError: 'datetime' is not supported by cloud runtime.`

**Steps to reproduce**

```
from qiskit_ibm_runtime import QiskitRuntimeService
from datetime import datetime

service = QiskitRuntimeService(channel="ibm_quantum")
backend = service.backend("ibm_cleveland")
dt = datetime(2023, 9, 28, 15, 54, 21)
p = backend.properties(datetime=dt)
```

**Expected behavior**

It should return backend properties for the given datetime. It's also unclear what "cloud runtime" means. 

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by kt474** [comment]
This was fixed in #1070, should work if you update qiskit-ibm-provider 

<img width="693" alt="Screenshot 2023-10-04 at 10 54 45 AM" src="https://github.com/Qiskit/qiskit-ibm-runtime/assets/20911417/8dcf5611-40e8-41f9-8a66-4959c6e79991">
