### ISSUE TITLE
Merge qiskit-ibm-provider into qiskit-ibm-runtime

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit-ibm-runtime#1128]
Currently there are two Qiskit "providers" for Qiskit Runtime - `qiskit-ibm-runtime` and `qiskit-ibm-provider`. The former supports all channels but does not support `backend.run` (i.e. primitives only). The latter supports `backend.run` but only supports IQP channel. 

Since we are adding `backend.run()` to this repo, we will merge the two providers since they'd essentially do the same thing. 

This means we will also deprecate and eventually archive `qiskit-ibm-provider`

- [ ] Make sure there are no instances/uses of `qiskit-ibm-provider` in this repo

**Comment by jyu00** [comment]
@1ucian0 The plan is to hold off until v2 Sampler becomes available, which will replace `backend.run`. So people can migrate from `backend.run` in `ibm-provider` directly to Sampler in `ibm-runtime`.
