### ISSUE TITLE
Program Sampler - M3 calibration failed

### ISSUE THREAD

**Issue by Jacck** [Qiskit/qiskit-ibm-runtime#1142]
**Describe the bug**
Hello, I've run the following code on ibm_brisbane (job status: https://quantum-computing.ibm.com/jobs/cmhwa7g8b8mg008vqgcg), that is based on tutorial: https://qiskit.org/ecosystem/ibm-runtime/tutorials/qaoa_with_primitives.html. I have used operator that works on 12 circuit, that solves my QUBO problem. I got the following error: Details: program Sampler, status: Failed - M3 calibration failed: Failure during build: Problem uploading payload over NATS: NoRespondersError().

**Steps to reproduce**
Here is the code: 
from qiskit.circuit.library import QAOAAnsatz
from qiskit.quantum_info import SparsePauliOp
from qiskit.visualization import plot_distribution
from qiskit_ibm_runtime import QiskitRuntimeService, Estimator, Sampler, Session
from scipy.optimize import minimize

service = QiskitRuntimeService()
backend = service.get_backend("ibm_brisbane")  # Change this to a real quantum device if available

hamiltonian = SparsePauliOp.from_list(here is definition of hamiltonian)
ansatz = QAOAAnsatz(hamiltonian, reps=2)

def cost_func(params, ansatz, hamiltonian, estimator):
    cost = estimator.run(ansatz, hamiltonian, parameter_values=params).result().values[0]
    return cost

session = Session(backend=backend)
estimator = Estimator(session=session, options={"shots": 2**10})
sampler = Sampler(session=session, options={"shots": 2**10})

x0 = 2 * np.pi * np.random.rand(ansatz.num_parameters)
res = minimize(cost_func, x0, args=(ansatz, hamiltonian, estimator), method="COBYLA")

qc = ansatz.assign_parameters(res.x)
qc.measure_all()
samp_dist = sampler.run(qc, shots=int(1e4)).result().quasi_dists[0]
session.close()

print(samp_dist.binary_probabilities())
**Expected behavior**
It should find optimal solution of my QUBO problem.

**Suggested solutions**
no clue

**Additional Information**
Error message: Traceback (most recent call last):
  Cell In[4], line 109
    res = minimize(cost_func, x0, args=(ansatz, hamiltonian, estimator), method="COBYLA")
  File /opt/conda/lib/python3.10/site-packages/scipy/optimize/_minimize.py:705 in minimize
    res = _minimize_cobyla(fun, x0, args, constraints, callback=callback,
  File /opt/conda/lib/python3.10/site-packages/scipy/optimize/_cobyla_py.py:34 in wrapper
    return func(*args, **kwargs)
  File /opt/conda/lib/python3.10/site-packages/scipy/optimize/_cobyla_py.py:273 in _minimize_cobyla
    xopt, info = cobyla.minimize(calcfc, m=m, x=np.copy(x0), rhobeg=rhobeg,
  File /opt/conda/lib/python3.10/site-packages/scipy/optimize/_cobyla_py.py:261 in calcfc
    f = fun(np.copy(x), *args)
  Cell In[4], line 100 in cost_func
    cost = estimator.run(ansatz, hamiltonian, parameter_values=params).result().values[0]
  File /opt/conda/lib/python3.10/site-packages/qiskit_ibm_runtime/runtime_job.py:224 in result
    raise RuntimeJobFailureError(f"Unable to retrieve job result. {error_message}")
RuntimeJobFailureError: 'Unable to retrieve job result. FAILURE DURING BUILD: PROBLEM UPLOADING PAYLOAD OVER NATS: NORESPONDERSERROR()'

Use %tb to get the full traceback.
capi_return is NULL
Call-back cb_calcfc_in__cobyla__user__routines failed.
- **qiskit-ibm-runtime version**: IBM brisbane
- **Python version**: IBM brisbane
- **Operating system**: IBM brisbane

**Comment by ElePT** [comment]
I am running into a similar issue, with a slightly different error message: `Failed - M3 calibration failed: 'Timed out waiting for job to finish.` In my case it's a 127 qubit QAOA job on Nazca with 100 shots using the sampler with the default resilience level, `job_id = cmkxj0g12ghg0088wqsg`. The exact same code would run without issues an hour earlier when I was not instantiating a session (`job_id = cmkwaa12hnf000830aeg`), I don't know if this was a coincidence or whether the session had something to do with the failure. You can attempt to reproduce the behavior commenting out the `resilience_level=0` line [on this file ](https://github.com/qiskit-community/qopt-best-practices/blob/experiments/test/hw_native_test_2_few_iters.py)

**Comment by jyu00** [comment]
> Failure during build: Problem uploading payload over NATS: NoRespondersError()

We had an issue with a backend component on `ibm_brisbane`, which should be fixed now. Please try again and see if you still see the same problem. 

@ElePT The failure is not related to session, so it was just a coincidence 🙂

**Comment by mberna** [comment]
Please reopen if you see this problem again.
