### ISSUE TITLE
[docs] Deprecation & Subsequent Removal of Custom Programs

### ISSUE THREAD

**Issue by drew-distefano** [Qiskit/qiskit-ibm-runtime#1149]
Make changes described in https://github.com/Qiskit/documentation/issues/142

Will provide updates / changes to that ticket to maintain a single source of truth.

@beckykd @javabster

**Comment by drew-distefano** [comment]
@beckykd @javabster The custom program deprecation has been pushed back to Nov 2. Please hold off on publishing these changes until after the announcement has been made. cc @jyu00

**Comment by kt474** [comment]
All mentions of custom programs have been removed from the docs and the migration guide is live https://docs.quantum.ibm.com/api/migration-guides/qiskit-runtime#upload-view-or-delete-custom-prototype-programs

@beckykd @javabster are there any specific docs updates you wanted to make regarding the custom programs removal?

**Comment by beckykd** [comment]
@kt474 I don't see anything additional that needs to be changed.
