### ISSUE TITLE
Check if there is duplication between test/fake_account_client.py and other test method

### ISSUE THREAD

**Issue by merav-aharoni** [Qiskit/qiskit-ibm-runtime#1160]
**What is the expected feature or enhancement?**
`test/fake_account_client.py` was copied from the provider. Check if there already similar functionality here and unite them as suitable.

**Acceptance criteria**

**Comment by merav-aharoni** [comment]
- `BaseFakeRuntimeJob` in `fake_runtime_client.py` is somewhat similar to `BaseFakeJob` in `fake_account_client.py`. The latter has more features.
- Likewise for all the subclasses of the above.
- It would probably be a good idea to merge the former into the latter, but it is not entirely trivial.
- `BaseFakeRuntimeClient` in `fake_runtime_client.py` seems to have the same functionality as `BaseFakeAccountClient` in `fake_account_client.py` but the two classes are quite different.
- There is no urgency in uniting these, but may be nice in the long run.

**Comment by kt474** [comment]
`fake_account_client.py` has already removed, closing this issue.
