### ISSUE TITLE
Filtering backends by simulator takes forever

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#1171]
**What is the expected feature or enhancement?**
It takes forever to filter backends by whether they are a simulator or not because the target for each device must be built.  Also, if a backend is not fully released, then building the target can fail giving an exception

**Acceptance criteria**
it is fast to filter by real backends

**Comment by kt474** [comment]
It looks like when retrieving and filtering backends with `backends()`, the target is not built, but the configuration is retrieved (which is how we check for `simulator`) which can take a long time if you have access to a lot of backends. 

The target is only built when retrieving a backend individually with `backend()`

**Comment by kt474** [comment]
Closing this for now, especially since simulators are being sunset
