### ISSUE TITLE
Broken docs link in `Session maximum execution time` section

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-ibm-runtime#1172]
**Describe the bug**

The link to `[Specify the session length](https://qiskit.org/ecosystem/ibm-runtime/how_to/run_session#session_length.html)` on this page https://qiskit.org/ecosystem/ibm-runtime/faqs/max_execution_time.html#session-maximum-execution-time is broken, I get a 404 following it.

**Steps to reproduce**

click the link

**Expected behavior**

link should work

**Suggested solutions**

fix the link

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by mriedem** [comment]
cc @beckykd

**Comment by mriedem** [comment]
There is also a broken link here: https://qiskit.org/ecosystem/ibm-runtime/sessions.html#maximum-session-timeout

The link to `[Determine session details](https://qiskit.org/ecosystem/ibm-runtime/how_to/run_session#determine-session-details.html).`.

**Comment by Erickype** [comment]
The links are up, maybe the time you were trying to load the page the system was updating.

**Comment by mriedem** [comment]
I'm still getting a 404 not found error page clicking the links in the page above.

**Comment by kt474** [comment]
@mriedem I believe all the broken links you mentioned are now fixed 

Specify the session length - https://docs.quantum.ibm.com/run/run-jobs-in-session#specify-length
Determine session details - https://docs.quantum.ibm.com/run/run-jobs-in-session#session-details
