### ISSUE TITLE
Out of place sub-section in docs

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-ibm-runtime#1234]
**Describe the bug**

This seems to be a random sub-section in the docs:

https://github.com/Qiskit/qiskit-ibm-runtime/blob/c8eb7c9c7b33b7fb299025256e71ca15bf5f7f3f/docs/how_to/run_session.rst#cancel-a-session

![image](https://github.com/Qiskit/qiskit-ibm-runtime/assets/3237936/f06c6805-77e0-45f6-85c4-027386eac1f2)

I wonder why that's there when there is this other rendered and linkable sub-section:

https://github.com/Qiskit/qiskit-ibm-runtime/blob/c8eb7c9c7b33b7fb299025256e71ca15bf5f7f3f/docs/how_to/run_session.rst#for-qiskit-runtime-releases-013-or-later

cc @beckykd @abbycross

**Comment by Eric-Arellano** [comment]
These docs will be going away Nov 29 and replaced by https://docs.quantum-computing.ibm.com. That specific content now lives in https://docs.quantum-computing.ibm.com/run/run-jobs-in-session#cancel-a-session.
