### ISSUE TITLE
Retrieve backend functionality of retired qiskit device

### ISSUE THREAD

**Issue by adrianor** [Qiskit/qiskit-ibm-runtime#1265]
### What is the expected enhancement?

It is always useful to access the device functionality even if certain devices are retired. For instance, I would like to keep doing my analysis on the transpilation procedure in a retired device, but I don't have access to it (lima) anymore. In my case, I would like to transpile, print the circuit, and do callbacks without requesting to run new jobs in an obviously retired device.

How can this be done? I'm almost sure the code should be available somewhere in qiskit. It is also not optimal if the whole "logic" from a device is retired. One should be able to keep using such constructions, even if new experiments cannot be submitted.

Note that I don't want to retrieve past jobs. I want to e.g. keep sending circuits and seeing how a certain device would have implemented it.

**Comment by ElePT** [comment]
@adrianor could you elaborate on what fake backends have you tried and what part of the transpilation is not the same? This would be useful feedback for future improvements.

**Comment by kt474** [comment]
It's also possible to retrieve the backend properties of the backend at the time the job was run with `backend.run()`.

Going to close this issue for now, feel free to reopen if it's still an issue.
