### ISSUE TITLE
Create happy path E2E test suite to run against simulators or real devices every night

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibm-runtime#127]
**What is the expected feature or enhancement?*
We used to run slow tests against real devices every night. PR https://github.com/Qiskit/qiskit-ibm-runtime/pull/114 removes running slow tests.

We should create a critical path minimal E2E test suite tailored to run against simulators as well as real devices. (We can discuss in comments what that critical path is).

**Acceptance criteria**
1. Runs nightly against a least busy simulator or real backend.
1. Tutorial notebooks are automatically executed as test case and they run through
 
Bonus points:
Certain people can trigger this manually against a specific simulator or backend of choice on demand. (Selectable from a dropdown list of simulators or backends). So if a new simulator or backend is sprung up and if we are asked to do a sanity check, we can run this suite.

**Comment by daka1510** [comment]
Basic e2e test coverage is enabled and tests run on a daily basis (https://github.com/Qiskit/qiskit-ibm-runtime/actions/workflows/e2e-tests.yml). Closing.
