### ISSUE TITLE
Allow `QiskitRuntimeService` with no token

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit-ibm-runtime#1271]
**What is the expected feature or enhancement?**

To get public information without needing a token. This would be useful for testing code in CI without risking sending off jobs.

**Acceptance criteria**

The following code works

```python
from qiskit_ibm_runtime import QiskitRuntimeService

QiskitRuntimeService.save_account(channel="ibm_quantum", token=None, set_as_default=True)
service = QiskitRuntimeService()
service.backends()
```

With a helpful error message if a user tries to submit a job without a token.

**Comment by kt474** [comment]
I don't think this is possible without significant overhaul, we cannot initialize an account without a token. Are there issues with using a normal account and just not running any jobs?
