### ISSUE TITLE
Update migration guide for backend.run()

### ISSUE THREAD

**Issue by merav-aharoni** [Qiskit/qiskit-ibm-runtime#1284]
**What is the expected feature or enhancement?**
After #1280 is completed, we should update the migration guide - see issue #1214, because now `backend.run()` and `sampler.run` will run in the same session.
Does it make sense to modify the existing guide, or do we need a new one?

**Acceptance criteria**

**Comment by kt474** [comment]
With the upcoming deprecation of backend.run(), closing this for now
