### ISSUE TITLE
Got error 'The control-flow constructs [] are not supported by the backend.' when running a generated pass manager

### ISSUE THREAD

**Issue by zuguangh** [Qiskit/qiskit-ibm-runtime#1288]
**Describe the bug**
I didn't find a default pass manager only for mapping in Qiskit, so I call generate_preset_pass_manager to get a staged pass manager with optimization, layout and routing. Then I try to move all the actions except optmization to an empty pass manager and call it.

**Steps to reproduce**
Call run method of the generated pass manager to get the mapping of an input circuit. 

**Expected behavior**
Should be able to run the pass manager with the circuit. 

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.44.2
- **Python version**: 3.11.5
- **Operating system**: Windows

**Comment by jyu00** [comment]
@zuguangh can you provide more information? Like which backend were you using, and the stack trace of the error?

**Comment by mberna** [comment]
Please reopen with more information.
