### ISSUE TITLE
Clean up backend.run(...) interface

### ISSUE THREAD

**Issue by blakejohnson** [Qiskit/qiskit-ibm-runtime#1297]
The `backend.run(...)` interface has accumulated a lot of cruft over the years. We need to start paring down this interface to only things which are essential.

Some things that I think can go (should validate all of these):
* remove `Schedule` and `List[Schedule]` from the allowed types of `circuits`. We nominally stopped supporting these types already in January 2022.
* `qubit_lo_freq`
* `meas_lo_freq`
* `schedule_los`
* `noise_model` - should be attached to the Backend, not to the call to `run()`.
* `seed_simulator` - again should be an argument on the simulator/backend

More controversial, but I think still worthwhile:
* drop the `memory` argument and only expose the behavior of `memory=True`. Rationale: if you really want statistics, use the `Sampler` instead.
* `meas_return` - if we only support `memory=True`, then it only makes sense for this to be `'single' `

For future consideration:
* `meas_level` - OpenQASM 3 allows expressing different measurement levels with separate `measure` commands in the OpenPulse grammar. I think it makes sense to develop equivalents in Qiskit and then read out the requested measurement level from the circuit itself

**Comment by jyu00** [comment]
Closing since `backend.run` is deprecated.
