### ISSUE TITLE
Add max_execution_time parameter to backend.run

### ISSUE THREAD

**Issue by Matt-Stypulkoski** [Qiskit/qiskit-ibm-runtime#1299]
When using backend.run(), jobs are converted into circuit-runner jobs. By default, circuit-runner jobs have max_execution_times of around 4 hours.

It is possible to manually set the max_execution_time for jobs submitted through the `QiskitRuntimeService`, so this functionality could also be moved to backend.run().
 
### What is the expected behavior?
Have `backend.run()` accept a max_execution_time parameter. This will work the same as if you manually created the circuit-runner job and manually set a max_execution_time.

**Comment by jyu00** [comment]
Closing since `backend.run` is deprecated.
