### ISSUE TITLE
"ibmq_ehningen" device alone results in missing 1  required positional argument error

### ISSUE THREAD

**Issue by maniraman-periyasamy** [Qiskit/qiskit-ibm-runtime#1306]
**Describe the bug**

Running estimator primitive session on "ibmq_ehningen" device  results in the following error:
"ERROR Failed to execute program: main() missing 1 required positional argument: 'observable_indices'"

however running the same script on any US-hub devices such as ibmq_mumbai, ibm_hanoi etc., works as it is supposed to.

**Steps to reproduce**
I have attached a simple script "test_file.txt" containing the python code.
[test_file.txt](https://github.com/Qiskit/qiskit-ibm-runtime/files/13851614/test_file.txt)

**Expected behavior**
Algorithm running without any error.

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.17.0 
- **Python version**: 3.10.8
- **Operating system**: ubuntu 22.04

**Comment by jyu00** [comment]
@maniraman-periyasamy `qiskit-ibm-runtime` version >= 0.13.0 is not compatible with the Ehningen environment. This was communicated via support a while back, and [a warning should be issued](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/qiskit_runtime_service.py#L212-L216).
