### ISSUE TITLE
Qubits are not reset correctly on a real backends

### ISSUE THREAD

**Issue by sorin-bolos** [Qiskit/qiskit-ibm-runtime#1310]
**Describe the bug**
I'm creating two circuits on *one qubit* each:
* circuit 1 adds a single X gate (no measurement)
<img src="https://github.com/Qiskit/qiskit-ibm-provider/assets/11334574/b8975f4a-da24-46dd-8b8e-1a5f397de4f0" width="100">

* circuit 2 has just a measurement
<img src="https://github.com/Qiskit/qiskit-ibm-provider/assets/11334574/1a3b9b2a-666a-4805-8585-896e662437d8" width="100">

Run these circuits in a list on a single job **on a real IBM backend** (I used 'ibm-osaka', but It was reproduced on other systems)
```
job = backend.run([circ1, circ2], shots=100)
```

The resulting counts for the second circuit should be all "0" since it only does a measurement, but they are 50% "1" and 50% "0"
```
Total counts (for both circuits) are: [{'0': 100}, {'0': 52, '1': 48}]
```

**Steps to reproduce**
Run the following circuit
```
from qiskit import QuantumCircuit, transpile
from qiskit_ibm_runtime import QiskitRuntimeService

service = QiskitRuntimeService(channel="ibm_quantum")
backend = service.get_backend('ibm_osaka')

circ1 = QuantumCircuit(1, 1)
circ1.x(0)
display(circ1.draw('mpl'))

circ2 = QuantumCircuit(1, 1)
circ2.measure(0, 0)
display(circ2.draw('mpl'))

job = backend.run([circ1, circ2], shots=100)
results = job.result()
counts = results.get_counts()
print("\nTotal counts are:", counts)
```

**Expected behavior**
The returned counts should be `[{'0': 100}, {'0': 100}]`

**Suggested solutions**

**Additional Information**
This happens consistently on every job with this configuration.
I tried adding the circuits in alternation [circuit1, circuit2, circuit1, circuit2] and the 50/50 measurement only happens at odd alternations.
I also tried transpiling the circuits against the real backend to make sure the same qubit is used on both circuits. Same result.

I opened [a similar bug on qiskit-ibm-provider](https://github.com/Qiskit/qiskit-ibm-provider/issues/788), but I saw that project was being deprecated. The bug happens for both projects.

- **qiskit-ibm-runtime version**: 0.17.0
- **Python version**: 3.12.0
- **Operating system**: Windows 11

**Comment by taalexander** [comment]
Hi Sorin, this issue should now be resolved. Please feel free to verify this and report back if this is not the case and I will reopen.
