### ISSUE TITLE
Primitive interface updates for SamplerV2

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit-ibm-runtime#1313]
Part of https://github.com/Qiskit/qiskit-ibm-runtime/issues/1131 

Support SamplerV2 input/output:
- [RFC](https://github.com/Qiskit/RFCs/pull/56)
- Input/output would also be PUB based
- Output is per shot measurement, with convenience functions to returns counts/probabilities

Based on the following Qiskit PRs https://github.com/Qiskit/qiskit/pull/11566 (replaced https://github.com/Qiskit/qiskit/pull/11264)
- SamplerV2 Container https://github.com/Qiskit/qiskit/pull/11542
- BaseSamplerV2 https://github.com/Qiskit/qiskit/pull/11529

Work should be done off the experimental [branch](https://github.com/Qiskit/qiskit-ibm-runtime/tree/experimental-0.2) where some of the work is already done (https://github.com/Qiskit/qiskit-ibm-runtime/pull/1224)

**Comment by kt474** [comment]
cc: @gadial

**Comment by ihincks** [comment]
The [BaseSamplerV2](https://github.com/Qiskit/qiskit/pull/11529) has been closed, and the [BaseEstimatorV2](https://github.com/Qiskit/qiskit/pull/11527) is in the merge queue. My guess is that the runtime repo should not be blocked two state vector implementations (https://github.com/Qiskit/qiskit/pull/11566 and https://github.com/Qiskit/qiskit/pull/11227) but only on  [BaseEstimatorV2](https://github.com/Qiskit/qiskit/pull/11527).

That being said, the two state vector implementations will hopefully be merged tomorrow.

**Comment by kt474** [comment]
Completed in `0.21.0` release
