### ISSUE TITLE
add testing for `qiskit_ibm_runtime/fake_provider/`

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-ibm-runtime#1316]
With the move of the [fake providers from qiskit to qiskit-ibm-runtime](https://github.com/Qiskit/qiskit-ibm-runtime/pull/1270), the tests were not moved yet. This issue is to account for that, as the code has currently 0% coverage:

![Screenshot 2024-01-15 at 12 58 36](https://github.com/Qiskit/qiskit-ibm-runtime/assets/766693/6733bf56-4f40-41c7-b961-9fb96adf5f8e)

Tagging this as `help wanted` as a community member with some experience could move and adapt the tests from Qiskit.

**Comment by ElePT** [comment]
The tests were moved in https://github.com/Qiskit/qiskit-ibm-runtime/pull/1140, the base class PR is a follow-up of this one. As far as I know, there are no base class unit tests to move.

**Comment by jyu00** [comment]
We should verify if tests exist

**Comment by kt474** [comment]
Tests already exist for `fake_provider`

![Image](https://github.com/Qiskit/qiskit-ibm-runtime/assets/20911417/cd0d584a-7d85-4ec5-a66c-af70f8805c2a)
