### ISSUE TITLE
qiskit-ibm-runtime release necessary before qiskit 0.46 release date (Feb 1st 2024)

### ISSUE THREAD

**Issue by ElePT** [Qiskit/qiskit-ibm-runtime#1317]
**What is the expected feature or enhancement?**
This is a friendly reminder that the deprecation of the fake backends in qiskit 0.46 (https://github.com/Qiskit/qiskit/pull/11381) is partially blocked on a runtime release that includes (https://github.com/Qiskit/qiskit-ibm-runtime/pull/1270), a PR that didn't make it to 0.17.0.

#1270 decouples the runtime fake provider base classes from the qiskit fake provider base classes, so that the deprecation warning that will be raised on qiskit 0.46 does not affect the runtime classes.

The 0.46 release is scheduled on February 1st. 

**Acceptance criteria**

**Comment by kt474** [comment]
Thanks @ElePT - I'll do a release next week

**Comment by ElePT** [comment]
Thank you @kt474!

**Comment by kt474** [comment]
@ElePT - Released 0.18.0!
