### ISSUE TITLE
Missing config files for fake backends on qiskit_ibm_runtime.fake_provider

### ISSUE THREAD

**Issue by mrvee-qC-bee** [Qiskit/qiskit-ibm-runtime#1318]
**Describe the bug**
`FileNotFound` error while calling a fake backend from `qiskit_ibm_runtime.fake_provider`

**Steps to reproduce**
```python3
from qiskit import QuantumCircuit
from qiskit import transpile
from qiskit_ibm_runtime.fake_provider import FakeManilaV2

# Get a fake backend from the fake provider
backend = FakeManilaV2()
```

**Expected behavior**
`backend` variable should initialise successfully without error

**Additional Information**

```python3
Traceback (most recent call last):
  Cell In[3], line 6
    backend = FakeManilaV2()
  File /opt/conda/lib/python3.10/site-packages/qiskit/providers/fake_provider/fake_backend.py:76 in __init__
    self._conf_dict = self._get_conf_dict_from_json()
  File /opt/conda/lib/python3.10/site-packages/qiskit/providers/fake_provider/fake_backend.py:137 in _get_conf_dict_from_json
    conf_dict = self._load_json(self.conf_filename)
  File /opt/conda/lib/python3.10/site-packages/qiskit/providers/fake_provider/fake_backend.py:155 in _load_json
    with open(os.path.join(self.dirname, filename)) as f_json:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.10/site-packages/qiskit_ibm_runtime/fake_provider/backends/manila/conf_manila.json'
```

- **qiskit-ibm-runtime version**: 0.17.0
- **Python version**:  3.10.8
- **Operating system**: Linux

**Comment by kt474** [comment]
What version of Qiskit are you using? The code snippet works for me.  

<img width="1063" alt="Screenshot 2024-01-16 at 10 40 32 PM" src="https://github.com/Qiskit/qiskit-ibm-runtime/assets/20911417/e97cd20d-d09a-473a-aa98-bc9729b72d3a">

**Comment by mrvee-qC-bee** [comment]
Hi @kt474! This was on qiskit version` 0.45.1`

**Comment by ElePT** [comment]
Hi @mrvee-qC-bee, I think that this might an installation issue (something related to the interaction between `qiskit` and `qiskit-ibm-runtime`). In principle, the error should not happen. It might help to try installing `qiskit-ibm-runtime` from source, as https://github.com/Qiskit/qiskit-ibm-runtime/pull/1270 moved the fake backend base classes to `qiskit-ibm-runtime`, so maybe that would help reduce Python's confusion finding the files.

**Comment by mtreinish** [comment]
The root cause of this issue is that the json response snapshots aren't being included in the package files. The manifest list: https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/MANIFEST.in will need to be updated to include the json files. Without including the json files in the manifest then when you install via a hosted package the JSON files which are in the source repo aren't present and you'll encounter an error like this.

**Comment by ElePT** [comment]
Sorry for that, here is the fix: https://github.com/Qiskit/qiskit-ibm-runtime/pull/1319.
