### ISSUE TITLE
Tutorials containing deprecated code and broken links

### ISSUE THREAD

**Issue by vaishnav-mk** [Qiskit/qiskit-ibm-runtime#1334]
### URL to the relevant documentation

https://learning.quantum.ibm.com/tutorial/variational-quantum-eigensolver
https://learning.quantum.ibm.com/tutorial/grovers-algorithm
https://learning.quantum.ibm.com/tutorial/quantum-approximate-optimization-algorithm
https://learning.quantum.ibm.com/tutorial/chsh-inequality

### Select all that apply

- [ ] typo
- [X] code bug
- [X] out-of-date content
- [X] broken link
- [ ] other

### Describe the fix.

I'll go through each tutorial one by one and highlight the issues that I've found.
### [Variational Quantum Eigensolver](https://learning.quantum.ibm.com/tutorial/variational-quantum-eigensolver)
* The code for [Step 2: Optimize problem for quantum execution](https://learning.quantum.ibm.com/tutorial/variational-quantum-eigensolver#step-2-optimize-problem-for-quantum-execution) contains a non-existent import `qiskit_ibm_runtime.transpiler`
![image](https://github.com/Qiskit/documentation/assets/84540554/eea9b081-c6c5-4eea-9081-cc2a2bdbdcfe)
* The link for **[Dynamical Decoupling](https://docs.quantum-computing.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_provider.transpiler.passes.scheduling.PadDynamicalDecoupling)** is a broken link
* As the transpiler cannot be imported, rest of the codeblocks don't work as expected
![image](https://github.com/Qiskit/documentation/assets/84540554/c5c83290-7eb2-45ec-8447-bc3264fb1479)
![image](https://github.com/Qiskit/documentation/assets/84540554/f2bfeba1-2687-4ebb-8a9b-36f52f942f9f)

### [Grover's Algorithm](https://learning.quantum.ibm.com/tutorial/grovers-algorithm)
* Similar to the first issue, you cannot import `Batch` from `qiskit_ibm_runtime`
![image](https://github.com/Qiskit/documentation/assets/84540554/b57fd3f3-9d49-401d-8298-beff751cb257)
![image](https://github.com/Qiskit/documentation/assets/84540554/cda916e8-75eb-4175-8732-310f190f8dab)

### [Quantum approximate optimization algorithm](https://learning.quantum.ibm.com/tutorial/quantum-approximate-optimization-algorithm)
* Similar to the 1st and 2nd pages, `qiskit_ibm_runtime.transpiler` is undefined
![image](https://github.com/Qiskit/documentation/assets/84540554/86dcd2d4-2e79-40a0-9765-c3b3392103fb)
* For [Step 2: Optimize problem for quantum execution](https://learning.quantum.ibm.com/tutorial/quantum-approximate-optimization-algorithm#step-2-optimize-problem-for-quantum-execution), the link for [Dynamic Decoupling](https://docs.quantum-computing.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_provider.transpiler.passes.scheduling.PadDynamicalDecoupling) is a broken link and leads to a 404 page

### [CHSH inequality](https://learning.quantum.ibm.com/tutorial/chsh-inequality)
* The Quantum Lab contains code that tries to import `Batch` from `qiskit_ibm_runtime` but is nonexistent, similar to the previous issues
![image](https://github.com/Qiskit/documentation/assets/84540554/221ab984-36e8-4bab-bf6f-ca12b073eb57)
![image](https://github.com/Qiskit/documentation/assets/84540554/e55ca46d-51c8-4be7-b28f-e9b965cb3787)

These are the issues that I've come across in the Quantum Lab

**Comment by frankharkins** [comment]
We've transferred this from [Qiskit/documentation](https://github.com/Qiskit/documentation), the source files are in this repo under [`docs/tutorials`](https://github.com/Qiskit/qiskit-ibm-runtime/tree/main/docs/tutorials).

**Comment by kt474** [comment]
These tutorials were recently updated in https://github.com/Qiskit/qiskit-ibm-runtime/pull/1469, I believe we can close this issue
