### ISSUE TITLE
Changes in Python 3.12 that might affect virtual environments created by venv

### ISSUE THREAD

**Issue by shravanpatel30** [Qiskit/qiskit-ibm-runtime#1344]
**Describe the bug**

I'm new here and so I'm sorry if this is not the place to discuss this topic.

In python version 3.12, `setuptools` will not be available by default in virtual environments created with [venv](https://docs.python.org/3/library/venv.html#module-venv). Here is the link for [What's new in python 3.12](https://docs.python.org/3/whatsnew/3.12.html), and under "Important deprecations, removals or restrictions" they have mentioned this change. 

Does this mean we will have to add `setuptools` to "requirements.txt" of `qiskit-ibm-runtime` for people who want to contribute using a virtual environment?

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by kt474** [comment]
Hi @shravanpatel30 yes you are correct -  we don't officially support python `3.12` yet, but when we do, we can make sure to update the requirements appropriately.

**Comment by jyu00** [comment]
We should support python 3.12 since Qiskit now supports it. I opened [an issue](https://github.com/Qiskit/qiskit-ibm-runtime/issues/1345) for that.

**Comment by kt474** [comment]
fixed by #1347
