### ISSUE TITLE
Switch to using BasePrimitiveJob for v2 primitives

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1352]
**What is the expected feature or enhancement?**

V2 primitives `run()` method now returns an instance of `BasePrimitiveJob`, which does _not_ inherit from `JobV1`. `RuntimeJob` needs to be updated to inherit this (plus `JobV1` to support `backend.run` still, if the same class is used). 

**Acceptance criteria**

**Comment by kt474** [comment]
Fixed by #1450
