### ISSUE TITLE
Define our own JobStatus for v2 primitive jobs

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1366]
**What is the expected feature or enhancement?**

V2 primitives return `BasePrimitiveJob`, which, unlike `JobV1`, no longer defines what needs to be returned by `job.status()`. This opens the door for us to return statuses not defined in Qiskit's [JobStatus class](https://github.com/t-imamichi/qiskit-terra/blob/04d9450057ce52d0e2cada21f6aa60ae74305b06/qiskit/providers/jobstatus.py#L18). See some discussion [here](https://github.com/Qiskit/qiskit/issues/11541). 

This is related to #1352 

**Acceptance criteria**

Define our own job status class or type for only the statuses we return today. It also needs to allow future expansion and backward compatibility for when we introduce additional statuses.

**Comment by kt474** [comment]
Fixed by #1450
