### ISSUE TITLE
Verify execution mode in from_id()

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1369]
**What is the expected feature or enhancement?**

Today `Batch` and `Session` both use the same `from_id()` method, and it doesn't verify if the execution mode matches the class. For example I can do 

```
session = Session(...)
batch = Batch.from_id(session.session_id)
```

while this is technically supported by the server and a user error, it'd be nice to let the user know especially since we (will) already query session details upon initialization.

Note that this needs to wait for execution mode being returned by the server. 

**Acceptance criteria**

An error is raise if one tries to use `Batch.from_id()` to initialize a session, and vice versa.

**Comment by kt474** [comment]
I don't think it's currently possible to check the `execution` mode given a session id and service - or at all for that matter. 

Should it be added to session details?

**Comment by jyu00** [comment]
It's returned by MCS API and runtime (paygo) APIs, so yeah it should be added to IQP API.

**Comment by kt474** [comment]
Thanks for creating the issue, beat me to it
