### ISSUE TITLE
Backport fake backend fix to 0.17

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1371]
**What is the expected feature or enhancement?**

Backport https://github.com/Qiskit/qiskit-ibm-runtime/pull/1319 to 0.17. While people can upgrade to 0.18 which has the fix, 0.18 requires Qiskit 0.45, which has a lot of deprecation/removal that'd take time to upgrade. 

**Acceptance criteria**

Backport https://github.com/Qiskit/qiskit-ibm-runtime/pull/1319 to 0.17.

**Comment by chriseclectic** [comment]
I managed to find a temporary work around (just installed version 0.18 with no-deps for an 'incompatible' version of qiskit) so this doesn't need to be high priority

**Comment by kt474** [comment]
fixed by #1374
