### ISSUE TITLE
qpy serialization fails with faulty qubits

### ISSUE THREAD

**Issue by AzizNgoueya** [Qiskit/qiskit-ibm-runtime#1384]
**Describe the bug**
Today when submitting a job on ibm_osaka using backend.run() produces the following error:
 File "/usr/local/lib/python3.10/dist-packages/qiskit_ibm_provider/qpy/binary_io/circuits.py", line 917, in _write_layout
    virtual_bit = final_layout_physical[i]
KeyError: 16

**Steps to reproduce**
```
service = QiskitRuntimeService()    
backend = service.get_backend('ibm_osaka')
qcT = transpile(qc, backend=backend)
job =  backend.run(qcT,shots=1000)
```

**Expected behavior**
Should works

**Suggested solutions**
The backend reports two faulty qubits on osaka today, **backend.properties().faulty_qubits() : [16, 106]** and they are missing in the physical layout. I added an exception here https://github.com/Qiskit/qiskit-ibm-provider/blob/f537ad7ece1d325e496fcce29712d50605b5080e/qiskit_ibm_provider/qpy/binary_io/circuits.py#L963

```
for i in range(circuit.num_qubits):
            try:
                virtual_bit = final_layout_physical[i]
                final_layout_array.append(circuit.find_bit(virtual_bit).index)
            except KeyError:
                continue
```
**Additional Information**

- **qiskit-ibm-runtime version**: 0.18.0
- **qiskit-ibm-provider version**: 0.8.0
- **Python version**: 3.8.18
- **Operating system**: macos

**Comment by kt474** [comment]
Hi @AzizNgoueya, the changes in https://github.com/Qiskit/qiskit-ibm-runtime/pull/1377 removed the qpy module from our codebase. If you are still having this issue with the latest version (`> 0.19.0`), the qpy issue would be fixed in https://github.com/Qiskit/qiskit.

**Comment by AzizNgoueya** [comment]
Hi @kt474, I am still having the issue with the latest version of qiskit-ibm-runtime but we will wait for the qiskit 1.0.0 release, Thanks.

**Comment by AzizNgoueya** [comment]
Closing this issue since it works with qiskit 1.0.0
