### ISSUE TITLE
Using Sessions for local simulator

### ISSUE THREAD

**Issue by bahar2040phy** [Qiskit/qiskit-ibm-runtime#1393]
**Describe the bug**
I am using the "sessions" command in qiskit runtime for a local simulator backend. It leads to the following error:
"QiskitBackendNotFoundError: 'No backend matches the criteria.'"

**Steps to reproduce**
`from qiskit.circuit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit_ibm_runtime import Sampler, Session, Options
 
# Bell Circuit
qr = QuantumRegister(2, name="qr")
cr = ClassicalRegister(2, name="cr")
qc = QuantumCircuit(qr, cr, name="bell")
qc.h(qr[0])
qc.cx(qr[0], qr[1])
qc.measure(qr, cr)
 
options = Options(optimization_level=3)
qasm_sim = AerSimulator()
with Session(backend='qasm_sim') as session:
    sampler = Sampler(session=session, options=options)
    job = sampler.run(qc)
    print(f"Sampler job ID: {job.job_id()}")
    print(f"Sampler job result: `{job.result()}")`

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:0.17.0
- **Python version**:3.10
- **Operating system**:Mac

**Comment by kt474** [comment]
Hi @bahar2040phy, sessions do not support local simulators (or any simulators for that matter) - you can find more information [here](https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.Session)

You can also see a list of your available backends with `service.backends()`
