### ISSUE TITLE
ECR gate on ibm_brisbane not supported??

### ISSUE THREAD

**Issue by tralala87** [Qiskit/qiskit-ibm-runtime#1462]
When I run my code on ibm_brisbane backend, I get:
Failed - Instruction not in basis gates: instruction: ecr, qubits: [0, 1], params: []

I thought that this gate is supported by the backend? At least it says that under specification for computer resources on ibm quantum experience platform.

**Comment by ihincks** [comment]
The ECR gates are directional, and you can find out their directions in the backends coupling map or target. In this particular case, brisbane's coupler on 0-1 happens to be the other direction:

```
circuit.ecr(1, 0)
```

**Comment by ihincks** [comment]
I'm going to close this because I think my previous comment addresses the issue. If you have any follow-up comments or questions, please do make another comment.

**Comment by kielpins-qctrl** [comment]
Even after transpiling my circuit against `ibm_brisbane`, I still get the same error. I would regard this as a bug in `transpile`.
