### ISSUE TITLE
Inline documentation for Sessions includes example using code that is no longer accessible with Qiskit 1.0

### ISSUE THREAD

**Issue by choerst-ibm** [Qiskit/qiskit-ibm-runtime#1463]
**Describe the bug**
The following example code is currently contained in the Session class documentation
https://github.com/Qiskit/qiskit-ibm-runtime/blob/ee086b0bbefe1fde4e1c4139ac2f9c10ff4789ae/qiskit_ibm_runtime/provider_session.py#L34-L55

With Qiskit 1.0, the `qiskit.test` package is no longer publicly visible, see [release notes](https://docs.quantum.ibm.com/api/qiskit/release-notes/1.0#misc-upgrade-notes)

> The qiskit.test module is no longer a public module. This was never intended to be public, nor used outside of Qiskit’s own test suite. All functionality was specific to Qiskit and no alternative is provided; if you needed similar functionality, you should include it 

**Suggested solutions**
Change the inline code example to run a different circuit.

**Additional Information**

- **qiskit-ibm-runtime version**: 0.20.0
- **Python version**: 3.11

**Comment by jyu00** [comment]
Fixed in https://github.com/Qiskit/qiskit-ibm-runtime/pull/1465
