### ISSUE TITLE
service.job() doesn't know about job version

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1471]
**Describe the bug**

If I submit a primitive V2 job then do `service.job()`, it will return a V1 `RuntimeJob` instead of `RuntimeJobV2`. This applies to `service.jobs()` as well. 

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

Unfortunately there is no good solution since the version number is only in inputs and results, which means potentially download the entire circuit inputs. 

**Additional Information**

- **qiskit-ibm-runtime version**: main
- **Python version**:
- **Operating system**:

**Comment by kt474** [comment]
Created issue on the ntc side - 3938

**Comment by jyu00** [comment]
I think for now we can just query the job inputs until the ntc issue is fixed. If the job has completed, the version number is also in the results.
