### ISSUE TITLE
401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by cqc-melf** [Qiskit/qiskit-ibm-runtime#1491]
### What is happening?

All login attempts get rejected with:
```
qiskit_ibm_runtime.exceptions.IBMNotAuthorizedError: '401 Client Error: Unauthorized for url: https://api.quantum.ibm.com/runtime/jobs. {"errors":[{"code":1201,"message":"Invalid credentials.","solution":"Verify your credentials and try again.","more_info":"https://cloud.ibm.com/apidocs/quantum-computing#error-handling"}],"trace":"..."}'
```

The job shows up shortly on the dashboard, but that crashes as well after that.

### How can we reproduce the issue?

```
from qiskit import QuantumCircuit
from qiskit_ibm_runtime import QiskitRuntimeService, Session, Sampler
import os
num_qubits = 32
qc = QuantumCircuit(num_qubits)
qc.h(0)
qc.cx(0, 1)
qc.measure_all()
_service = QiskitRuntimeService(
    channel="ibm_quantum",
    instance="ibm-q/open/main",
    token="your token",
)
_session = Session(service=_service, backend="ibmq_qasm_simulator")
sampler = Sampler(session=_session)
job = sampler.run(circuits=qc)
job.result()
```

### What should happen?

Login should work?

- **qiskit-ibm-runtime version**: tested with: 0.21.1, 0.21.0, 0.20.0 0.19.1
- **Python version**: 3.11
- **Operating system**: linux, mac

**Comment by kt474** [comment]
@cqc-melf are you still having this issue? It should be resolved now

**Comment by richrines1** [comment]
i'm also getting a 401 when i try to instantiate a QiskitRuntimeService with an ibm_quantum account (it seems to be fine if i use my ibm_cloud account though?)

**Comment by anandukmadhu** [comment]
I'm also getting the same error. Still not resolved. I also tried using the IBM Quantum Learning Lab to run the code. The issue still persists.

**Comment by Chuckio1212** [comment]
I am also getting the same error, trying to use IBM-quantum API Token to log in but get
` '401 Client Error: Unauthorized for url: https://api.quantum.ibm.com/runtime/backends/simulator_stabilizer/status. {"errors":[{"code":1201,"message":"Invalid credentials.","solution":"Verify your credentials and try again.","more_info":"https://cloud.ibm.com/apidocs/quantum-computing#error-handling"}],"trace":"cnle5qf9dnnkolqbaadg"}'`

Tried to regenerate the token but the problem persists. 
About 10h ago, re-run the job without changing anything worked, but now I couldn't log in no matter what.

**Comment by repettovaleria** [comment]
I encountered the same issue yesterday, however it seems to be fixed up until now where I keep getting the same message once again:

`qiskit_ibm_runtime.exceptions.IBMNotAuthorizedError: '401 Client Error: Unauthorized for url: https://api.quantum.ibm.com/runtime/backends?provider=partner-cnr%2Fiit%2Fqml-for-genomics. {"errors":[{"code":1201,"message":"Invalid credentials.","solution":"Verify your credentials and try again.","more_info":"https://cloud.ibm.com/apidocs/quantum-computing#error-handling"}],"trace":"cnlevfdtjerd52hipng0"}' `

**Comment by cqc-melf** [comment]
> @cqc-melf are you still having this issue? It should be resolved now

I am still having the same issue, it was working for a very short time today in the morning.

**Comment by kt474** [comment]
Sorry for all the issues with our API recently - we've been working hard to resolve these issues as quickly as possible and make sure they don't happen again. Everything should be running smoothly now, the unauthorized url issue has been fixed.

**Comment by Jay03112000** [comment]
I am also getting this error :IBMNotAuthorizedError: '401 Client Error: Unauthorized for url: https://auth.quantum-computing.ibm.com/api/users/loginWithToken. Login failed., Error code: 3446.'

I have used this code and generate API token Than also the error is coming 
from qiskit_ibm_runtime import QiskitRuntimeService

service = QiskitRuntimeService(
    channel='ibm_quantum',
    instance='ibm-q/open/main',
    token=' '
)

**Comment by rdguerrerom** [comment]
Hi, 

I am experiencing the same access issues.

Is this fixed?

How can I handle this issue?
