### ISSUE TITLE
Update 4 tutorial notebooks to primitives-v2

### ISSUE THREAD

**Issue by ashsaki** [Qiskit/qiskit-ibm-runtime#1497]
**What is the expected feature or enhancement?**
The following $4$ tutorials use `V1` `Estimator` and `Sampler`. Update them to use `EstimatorV2` and `SamplerV2` primitives.

1. [CHSH](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/tutorials/chsh_inequality/chsh_with_estimator.ipynb)
2. [Grover's](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/tutorials/grovers_algorithm/grover_with_sampler.ipynb)
3. [VQE](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/tutorials/variational_quantum_eigensolver/vqe_with_estimator.ipynb)
4. [QAOA](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/tutorials/quantum_approximate_optimization_algorithm/qaoa_with_primitives.ipynb)

**Acceptance criteria**
Tutorial notebooks updated to use `EstimatorV2` and `SamplerV2` successfully.

**Comment by kt474** [comment]
Fixed in #1469
