### ISSUE TITLE
SamplerV2: emit a warning when a circuit has no cregs

### ISSUE THREAD

**Issue by mberna** [Qiskit/qiskit-ibm-runtime#1504]
**What is the expected feature or enhancement?**
If the circuits used in SamplerV2 queries don't have any cregs, it would almost certainly be accidental and we should emit a warning. In this case, the DataBin returned will be empty and we should spare the user the surprise and give them a chance to cancel the job.

**Acceptance criteria**
A warning is emitted when using circuits without cregs with SamplerV2.

**Comment by kt474** [comment]
I think this is already done here - is it not working as expected? 

https://github.com/Qiskit/qiskit-ibm-runtime/blob/5625e98c4c7a6e215c252aca72c2f871fed9bc17/qiskit_ibm_runtime/sampler.py#L116-L121

**Comment by mberna** [comment]
You are right, I see the warning now. I was using an old (custom) version of the library.
