### ISSUE TITLE
Incorrect program options take 30-45sec to error on the cloud

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#151]
**Describe the bug**
If you pass an incorrect set of `program_inputs` to a runtime program it takes between 30-45sec to tell you the input was invalid.

**Steps to reproduce**
Call sampler with 

```python
program_inputs = {"circuits": qc, "use_measurement_mitigation": True, "hello": True}
````

**Expected behavior**
I would expect there to be some validation and an error thrown almost immediately. 

**Suggested solutions**
I know there is some metadata that can be used as a schema.

**Additional Information**

- **Qiskit IBM Runtime version**: `'0.1.0rc1'`
- **Python version**:
- **Operating system**:

**Comment by renier** [comment]
We opted to defer validation to the runtime programs themselves. Validating parameters for custom programs in general right in the API is problematic.

In the future, there won't be a programs API to allow these definitions of the schema. I foresee then the validation for primitive inputs to be done down in the client.

**Comment by nonhermitian** [comment]
Ok, then will close this.  Thanks for the insight.
