### ISSUE TITLE
Initialize, StatePreparation functions do not work in qiskit runtime

### ISSUE THREAD

**Issue by derenliu** [Qiskit/qiskit-ibm-runtime#1517]
**Describe the bug**
When running circuits with ''initialize', 'StatePreparation', the code returns "Circuits that do not match the target hardware definition are no longer supported after March 4, 2024."

Therefore, is there any other way to freely initialize complex amplitudes for the qubits and run on real quantum device?

**Comment by ElePT** [comment]
Hi @derenliu, it looks like you are missing the transpilation step, try running:

```
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager

# Transpile the circuit
pass_manager = generate_preset_pass_manager(optimization_level=1, backend=backend)
transpiled_circ = pass_manager.run(circuit)

#send transpiled_circ to the primitive, it now matches the target hw definition
```

**Comment by ElePT** [comment]
@derenliu this error suggests that the instruction has not been transpiled, do you want to share a minimal reproducible example to see what is going on?
