### ISSUE TITLE
It takes ~75 sec for a job to error

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#152]
**Describe the bug**
If you send an empty circuit with no shots the service is in `running` mode for ~75sec before actually raising an error

**Steps to reproduce**
Pass an empty circuit with no shots to the `sampler`
**Expected behavior**

**Suggested solutions**
It should error sooner

**Additional Information**

- **Qiskit IBM Runtime version**: 0.1.0rc1
- **Python version**:
- **Operating system**:

**Comment by rathishcholarajan** [comment]
@nonhermitian Assuming you ran this against a real backend? Could you provide the sample code you used to test this scenario?

**Comment by nonhermitian** [comment]
It seems there have been some improvements in performance since I lasted tested this.  This one errors in ~15sec: `'c8bmvm66859eus3g3q60'`

**Comment by rathishcholarajan** [comment]
This should be better now. Please re-open if not.
