### ISSUE TITLE
It should not take 70sec to run a empty circuit with 1 shot

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#153]
**What is the expected feature or enhancement?**
Currently the service takes ~70sec in the `running` mode to execute an empty circuit with a single shot.  It should not take this long to do so.

**Acceptance criteria**
Going through the current "legacy" pipeline is about an order of magnitude faster

**Comment by rathishcholarajan** [comment]
@nonhermitian Could you please provide the job id? cc: @renier

**Comment by nonhermitian** [comment]
Here is one.  This one took ~40sec `'c8bmuce6859eus3g3ni0'`

**Comment by nonhermitian** [comment]
This one took over 90sec in "running" on a simulator in the test cloud: `'c8bnkjiss066rcv2ndhg'`

**Comment by rathishcholarajan** [comment]
Thanks! @renier Could you please help check?

**Comment by renier** [comment]
This should be better @nonhermitian . Try and let me know.

**Comment by rathishcholarajan** [comment]
This should be better now. Please re-open issue if not.
