### ISSUE TITLE
Fake bakends and BasicAer

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-ibm-runtime#1548]
In the fake backend a warning is raised about Aer not being found and instead BasicAer is being used.

https://github.com/Qiskit/qiskit-ibm-runtime/blob/503e76ed8f4805d74bef6be33aef0c63165149e0/qiskit_ibm_runtime/fake_provider/fake_backend.py#L570

BasicAer was renamed in Qiskit 1.0 so perhaps this could be updated too. Maybe give the new name and include formerly BasicAer - I say that as I see there is some conditional logic around the import, presumably to support versions prior to 0.46, yet the requirements.txt file states qiskit>=1.0.0 so its unclear around the backwards compatibility aspect there.

**Comment by ElePT** [comment]
I also noticed this warning (the core qiskit version of this warning was reformulated to say `BasicSimulator`), but at the time `qiskit-ibm-runtime` was supporting 0.46 too, so it was too early. I can update it now.

**Comment by JessicaJohnBritto** [comment]
I got this warning while following the code from (Alternative: run the example using a simulator) ["Hello World" Tutorial.](https://docs.quantum.ibm.com/guides/hello-world).
`/opt/conda/lib/python3.11/site-packages/qiskit_ibm_runtime/fake_provider/fake_backend.py:468: RuntimeWarning: Aer not found, using qiskit.BasicSimulator and no noise.
  warnings.warn(`

**Comment by rohansk1** [comment]
> I got this warning while following the code from (Alternative: run the example using a simulator) ["Hello World" Tutorial](https://docs.quantum.ibm.com/guides/hello-world). Qiskit - version: `1.2.0` `/opt/conda/lib/python3.11/site-packages/qiskit_ibm_runtime/fake_provider/fake_backend.py:468: RuntimeWarning: Aer not found, using qiskit.BasicSimulator and no noise. warnings.warn(`

You might need to `pip install qiskit-aer`
