### ISSUE TITLE
Circuit metadata is missing from Sampler results on fake backend

### ISSUE THREAD

**Issue by kielpins-qctrl** [Qiskit/qiskit-ibm-runtime#1551]
**Describe the bug**

When running a circuit via `SamplerV2` on a real QPU, the `PubResult` corresponding to the circuit contains a `metadata` attribute that reproduces the original circuit metadata. However, when running that circuit on a fake backend, the `metadata` attribute is not present in the `PubResult`.

**Steps to reproduce**

Run the script below. The script duplicates the example script in the [fake backend documentation](https://github.com/Qiskit/documentation/blob/main/docs/api/migration-guides/local-simulators.mdx) and simply adds metadata to the circuit. The first `print` line correctly prints the circuit metadata, which survives transpilation. The second `print` line prints an empty dictionary, rather than the circuit metadata.

```
from qiskit.circuit import QuantumCircuit
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from qiskit_ibm_runtime import SamplerV2 as Sampler
from qiskit_ibm_runtime.fake_provider import FakeManilaV2

# Bell Circuit
qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.measure_all()
qc.metadata = {0: 1}

# Run the sampler job locally using FakeManilaV2
fake_manila = FakeManilaV2()
pm = generate_preset_pass_manager(backend=fake_manila, optimization_level=0)
isa_qc = pm.run(qc)
print(f'circuit metadata: {isa_qc.metadata}')

# You can use a fixed seed to get fixed results.
options = {"simulator": {"seed_simulator": 42}}
sampler = Sampler(backend=fake_manila, options=options)
result = sampler.run([isa_qc]).result()
print(f'circuit metadata: {result.metadata}')
```

**Expected behavior**

Retain circuit metadata in `SamplerV2` when running fake backend, identically to behaviour on real QPU.

- **qiskit-ibm-runtime version**: 0.22.0
- **Python version**: 3.11.6
- **Operating system**: macOS Sonoma 14.4

**Comment by kielpins-qctrl** [comment]
The same issue occurs when using the `AerSimulator` migration script [here](https://docs.quantum.ibm.com/api/migration-guides/local-simulators#aersimulator). Happy to file a separate ticket if that is helpful.

**Comment by kt474** [comment]
Hi @gzquse, the metadata in this example would be in the `SamplerPubResult` so you should see it in 
`job.result()[0].metadata`.

**Comment by gzquse** [comment]
Hi @kt474 
```
if job.status() == 'DONE':
        print(job.result()[0])
        counts = job.result()[0].data.meas.get_counts()
        path = args.outPath+args.backend+'_'+str(args.numShots)+'_bitstrings.pdf'
        his = plot_histogram(counts, sort='value_desc', figsize=(5, 7.5), filename=path)
        print('bitstrings saved to', path)

```
My output:

SamplerPubResult(data=DataBin(meas=BitArray(<shape=(), num_shots=1024, num_bits=5>)), metadata={'circuit_metadata': {}})

Seems my previous saved metadata does not show in the samPub

I was used ibm_kyiv
