### ISSUE TITLE
Use of EstimatorV1 with QiskitRuntimeLocalService and DynamicsBackend does not work

### ISSUE THREAD

**Issue by arthurostrauss** [Qiskit/qiskit-ibm-runtime#1559]
**Describe the bug**

When using EstimatorV1 (from Qiskit Runtime), and declaring a localService and a DynamicsBackend, the method _run_backend_primitive_v1 does effectively try to extract a noise_model option from the options dictionary. Even though no noise model is passed, the dictionary run_options (then passed to the backend.run method through the BackendEstimator under the hood) contains a noise_model keyword argument (set to None). This keyword raises an error when passed to the DynamicsBackend as it does not accept noise_model as a valid option to be set.  My workaround at the moment is to go through EstimatorV2, which does not try to call the same noise_model option (I’m actually not sure in what context it should be here in the first place, perhaps could you give a hint on what backend this noise_model run option is supposed to act, like is it AerBackend or Cloud simulator?).
**Steps to reproduce**
- Declare a DynamicsBackend instance (as done in here: https://qiskit-extensions.github.io/qiskit-dynamics/tutorials/dynamics_backend.html)
- Declare a RuntimeEstimatorV1 with backend set to a DynamicsBackend (will therefore leverage QiskitRuntimeLocalService)
- Call Estimator.run() method for an arbitrary input.
**Expected behavior**
Should call the backend.run from DynamicsBackend normally under the hood and return the expectation value of the provided observable.

**Suggested solutions**
Remove systematic keyword argument noise_model that is not compatible with an arbitrary BackendV1|BackendV2 instance. The usage of EstimatorV2 in the same workflow typically works correctly.

**Additional Information**

- **qiskit-ibm-runtime version**: 0.22.0
- **Python version**: 3.10
- **Operating system**: Mac OS Sonoma

**Comment by jyu00** [comment]
As documented, Qiskit Runtime local testing mode only supports fake backends and Aer backends.
