### ISSUE TITLE
FakeSherbrooke is missing reset in its properties

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1570]
**Describe the bug**

FakeSherbrooke properties dictionary is missing `reset` in its list of gates. Consequently, a circuit with a `reset` will not pass the ISA validation. The real ibm_sherbrooke has `reset`.

We should also check all the other fake backends (that still have a real counterpart) to see if their `target.operation_names` match the real ones.

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by gregbyrd** [comment]
Yes, this appears to be a problem with all of the V2 backends. I added a comment to #975 yesterday rather than opening up a new issue. I saw the problem with FakeAlmadenV2 and with FakeCusco.

**Comment by nonhermitian** [comment]
It would be nice if this can be prioritized a bit as the lack of reset support is breaking a lot of our internal benchmarking codes

**Comment by jyu00** [comment]
@nonhermitian Yes this is planned for this sprint (next 2 weeks)

**Comment by kt474** [comment]
Fixed by #1624 #1600
