### ISSUE TITLE
cannot import name ValidationInfo from pydantic

### ISSUE THREAD

**Issue by ArslanH22** [Qiskit/qiskit-ibm-runtime#1577]
**Describe the bug**
An error occurs when you try to import QuantumRuntimeServices from qiskit_ibm_runtim. It originates from qiskit_ibm_runtime\options\utlis.py at line 23. It says it cannot import the name 'ValidationInfo' from 'pydantic'.

**Steps to reproduce**
from qiskit_ibm_runtime import QuantumRuntimeServices

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.22.0
- **qiskit version**: 1.0.2
- **Python version**: 3.11.7
- **Operating system**: 64 bit (AMD64)

**Comment by kt474** [comment]
Hi @ArslanH22, this was fixed in #1500 - you can fix the error by installing pydantic `pip install pydantic`

**Comment by soly33tworks** [comment]
> Hi @ArslanH22, this was fixed in #1500 - you can fix the error by installing pydantic `pip install pydantic`

Tried. Doesn't work, getting the exact same error.

**Comment by Quartermain91** [comment]
@ArslanH22  Bump, same issue

**Comment by Quartermain91** [comment]
@kt474  bump still facing this issue

**Comment by kaisarmasum** [comment]
Doesn't work.

**Comment by kt474** [comment]
@Quartermain91 @kaisarmasum can you post your error log?

**Comment by kaisarmasum** [comment]
> @Quartermain91 @kaisarmasum can you post your error log?

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[7], line 1
----> 1 from qiskit_ibm_runtime import QiskitRuntimeService, Sampler, Batch

File ~\anaconda3\Lib\site-packages\qiskit_ibm_runtime\__init__.py:220
    217 from .utils.utils import setup_logger
    218 from .version import __version__
--> 220 from .estimator import (  # pylint: disable=reimported
    221     EstimatorV2,
    222     EstimatorV1,
    223     EstimatorV1 as Estimator,
    224 )
    225 from .sampler import (  # pylint: disable=reimported
    226     SamplerV2,
    227     SamplerV1,
    228     SamplerV1 as Sampler,
    229 )
    230 from .options import Options, EstimatorOptions, SamplerOptions, OptionsV2

File ~\anaconda3\Lib\site-packages\qiskit_ibm_runtime\estimator.py:30
     28 from .runtime_job_v2 import RuntimeJobV2
     29 from .ibm_backend import IBMBackend
---> 30 from .options import Options
     31 from .options.estimator_options import EstimatorOptions
     32 from .base_primitive import BasePrimitiveV1, BasePrimitiveV2

File ~\anaconda3\Lib\site-packages\qiskit_ibm_runtime\options\__init__.py:98
      1 # This code is part of Qiskit.
      2 #
      3 # (C) Copyright IBM 2022, 2024
   (...)
     10 # copyright notice, and modified files need to carry a notice indicating
     11 # that they have been altered from the originals.
     13 """
     14 =====================================================
     15 Primitive options (:mod:`qiskit_ibm_runtime.options`)
   (...)
     95 
     96 """
---> 98 from .environment_options import EnvironmentOptions
     99 from .execution_options import ExecutionOptions
    100 from .execution_options import ExecutionOptionsV2

File ~\anaconda3\Lib\site-packages\qiskit_ibm_runtime\options\environment_options.py:17
     13 """Options related to the execution environment."""
     15 from typing import Optional, Callable, List, Literal
---> 17 from .utils import primitive_dataclass
     19 LogLevelType = Literal[
     20     "DEBUG",
     21     "INFO",
   (...)
     24     "CRITICAL",
     25 ]
     28 @primitive_dataclass
     29 class EnvironmentOptions:

File ~\anaconda3\Lib\site-packages\qiskit_ibm_runtime\options\utils.py:23
     20 from dataclasses import is_dataclass, asdict
     21 from numbers import Real
---> 23 from pydantic import ConfigDict, ValidationInfo, field_validator
     24 from pydantic.dataclasses import dataclass
     26 from qiskit.providers.backend import Backend

ImportError: cannot import name 'ValidationInfo' from 'pydantic'

**Comment by EthanJns** [comment]
Possible its some type of environment issue cause on my machine not using conda or virtualenv, I get this same error.
However when I create a fresh enviornment in conda, install the required packages via pip, I have no problems. Wondering if that may work for others.

**Comment by ihincks** [comment]
We should check when `ValidationInfo` was added to the main namespace of `pydantic`. It could be that our minimum version 2.5 is too low.

**Comment by HuangJunye** [comment]
A few users are reporting this issue in the IBM Quantum Challenge 2024 and I just saw[ another one](https://qiskit.slack.com/archives/CJG2E9LQP/p1718396876475139) on slack. Can you please reopen the issue?

**Comment by rainemmxxiv** [comment]
hi, i'm facing a similar issue

from pydantic import ConfigDict, ValidationInfo, field_validator
     [24]... from pydantic.dataclasses import dataclass
     [26... from qiskit.providers.backend import Backend

ImportError: cannot import name 'ConfigDict' from 'pydantic'

**Comment by kt474** [comment]
@rainemmxxiv I believe you're using an outdated version of pydantic, please try upgrading to the latest version 

```
pip install pydantic -U
```

We'll update the version required in our `setup.py` file so this shouldn't be a problem in the future. This should also fix the issue others were having in the Quantum Challenge @HuangJunye.

**Comment by shekoufehalavi** [comment]
same error. I yesterday run the code without error and now it can't be run...

**Comment by kt474** [comment]
> same error. I yesterday run the code without error and now it can't be run...

@shekoufehalavi what version of pydantic do you have installed?
