### ISSUE TITLE
Inconsistent behavior of Session initializers

### ISSUE THREAD

**Issue by tachikoma-li** [Qiskit/qiskit-ibm-runtime#1582]
**Describe the bug**

When creating a `Session` from `id` using `Session.from_id`, a deprecation [warning](https://github.com/Qiskit/qiskit-ibm-runtime/blob/20d810eefa35b5b9fe06c86ae95648288e7dfd25/qiskit_ibm_runtime/session.py#L348) is raised if one passes a `backend` argument. However, if one doesn't pass a `backend`, the default `Session` initializer (which is called from `Session.from_id`) would raise another deprecation [warning](https://github.com/Qiskit/qiskit-ibm-runtime/blob/20d810eefa35b5b9fe06c86ae95648288e7dfd25/qiskit_ibm_runtime/session.py#L136) or [error](https://github.com/Qiskit/qiskit-ibm-runtime/blob/20d810eefa35b5b9fe06c86ae95648288e7dfd25/qiskit_ibm_runtime/session.py#L135).

It's not clear what's the expected behavior from the [docs](https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.Session). Might be good to make the two initializers consistent.

If the default Session initializer now does require `backend`, it might be also good to update the type hints and the docs of the `backend` parameter.

**Steps to reproduce*

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.22.0
- **Python version**: 3.11
- **Operating system**:  macOS Sonoma

**Comment by kt474** [comment]
Hi @tachikoma-li - there is an open PR for updating the `from_id` method (https://github.com/Qiskit/qiskit-ibm-runtime/pull/1311). It will take care of the inconsistencies you have mentioned here.

**Comment by tachikoma-li** [comment]
@kt474, nice to see it's tracked. Hopefully this could be addressed in the next release.

Closed as there is already a PR on it.

**Comment by kt474** [comment]
> @kt474, nice to see it's tracked. Hopefully this could be addressed in the next release.
> 
> Closed as there is already a PR on it.

We will try to have it in before the next release

**Comment by kt474** [comment]
#1311 Has been merged, it'll be in the next release, planned for this Monday
