### ISSUE TITLE
Nested experimental suboptions override non-experimental suboptions

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-ibm-runtime#1602]
**Describe the bug**

If a sub-options field is contained in `experimental` options, it will override any values specified in the main options.

**Steps to reproduce**

This is a minimal example to reproduce, using a non-experimental option initialized as if it were an experimental options:

```python
options = {
    "resilience": {
        "zne_mitigation": True, 
        "zne": {"noise_factors": [1, 1.5, 2]}
    },
}
estimator = EstimatorV2(backend=backend, options=options)
result = estimator.run([pub]).result()
```

We can confirm the noise factors in result metadata
`print(result.metadata["resilience"]["zne"]["noise_factors"])` -> `[1.0, 1.5, 2.0]`

Now if we ad an experimental ZNE option

```python
options = {
    "resilience": {
        "zne_mitigation": True, 
        "zne": {"noise_factors": [1, 1.5, 2]}
    },
    "experimental": {
        "resilience": {"zne": {"extrapolator": ["linear"]}},
    }
}
estimator = EstimatorV2(backend=backend, options=options)
result = estimator.run([pub]).result()
```
The specified noise factors are discarded and the default ones are used:
`print(result.metadata["resilience"]["zne"]["noise_factors"])` -> `[1.0, 3.0, 5.0]`

**Expected behavior**

The second case should merge the experimental ZNE options into the regular ones (and similarly for any other suboptions) without discarding the fields in the original one.

**Suggested solutions**

There is likely a bug in the way experimental options are merged with regular options

**Additional Information**

- **qiskit-ibm-runtime version**: 0.22
- **Python version**: 3.11
- **Operating system**: MacOS

**Comment by kt474** [comment]
fixed in #1731
