### ISSUE TITLE
JSONDecoder error when retrieving IQP job

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1603]
**Describe the bug**

Retrieving job 

<img width="928" alt="image" src="https://github.com/Qiskit/qiskit-ibm-runtime/assets/28284230/f6d4d0ea-3937-4ebf-b6d6-06d24aeb1654">

raised a JSONDecoder error

![image](https://github.com/Qiskit/qiskit-ibm-runtime/assets/28284230/789dc615-9a11-4979-9e70-551e9b12e38c)

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.22
- **Python version**: 3.10
- **Operating system**:

I didn't look too much into this, but a quick Google search says it may be an incompatibility between `request` and Python 3.10.

**Comment by danipombo** [comment]
For context, the above error was generated when running the code on the IBM Watson Studio. However, It ran smoothly when executing in my local environment.

**Comment by pacomf** [comment]
I replicated the issue in Watson Studio and I resolved uninstalling the simplejson dependency:

`!yes | pip uninstall simplejson`

For context: https://github.com/Qiskit/qiskit-ibm-provider/pull/649#issuecomment-1572362758

**Comment by kt474** [comment]
Thank you @pacomf - yes this same issue we discovered a while back in `qiskit-ibm-provider`. 

>It appears that when simplejson is in the environment requests preferentially imports it. However, the arguments accepted by JSONDecoder are inconsistent between the standard library json and simplejson leading to errors when using the standard json.JSONDecoder when simplejson is in the environment.

Closing as resolved

**Comment by HuangJunye** [comment]
This issue was reported during the quantum challenge when people were running the notebook on qBraid. Is there a plan to add some checks of whether simplejson exist in the environment and raise warnings? This bug is rather hard to debug unless user search on the github repo.

**Comment by rryoung98** [comment]
Thanks @HuangJunye it's certainly a non-obvious bug we'll try and fix it asap.

**Comment by JaganNatarajan** [comment]
@rryoung98 is this issue fixed. I am still seeing this happen in qBraid. Could you please update?

**Comment by kt474** [comment]
Hi @JaganNatarajan I'm working on a fix in #1800
