### ISSUE TITLE
Make fake backends more like IBMBackend

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1605]
**What is the expected feature or enhancement?**

The fake backends in this repo are meant to represent IBM backends and be similar to `IBMBackend`. In addition to inheriting `BackendV2`, `IBMBackend` also has a number of additional methods that should be added to fake backends. Note that this update only needs to apply to V2 fake backends (since we are [deprecating V1](https://github.com/Qiskit/qiskit-ibm-runtime/issues/1604)).

**Acceptance criteria**

- Add additional `IBMBackend` methods to V2 fake backends, including
    - service (this should return `QiskitRuntimeLocalService`
    - properties, defaults, configuration
    - status
    - check_faulty

**Comment by HuangJunye** [comment]
Just randomly came across a user trying to create a fake backend with latest calibration results by monkey patching with calibration results downloaded from IQP computer resource page: https://egrettathula.wordpress.com/2023/01/10/refreshable-fake-backends/

**Comment by yaelbh** [comment]
Since #1676 has been closed as a duplicate, I'm linking here a comment that I left there: https://github.com/Qiskit/qiskit-ibm-runtime/issues/1676#issuecomment-2111656759.
