### ISSUE TITLE
There should be a FakeTorino backend

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#1623]
**What is the expected feature or enhancement?**
There should be a FakeTorino backend

**Acceptance criteria**
There is a FakeTorino backend

**Comment by mtreinish** [comment]
https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/fake_provider/backends/torino/fake_torino.py#L21
