### ISSUE TITLE
Return more helpful exception if Quantum Service is in maintenance

### ISSUE THREAD

**Issue by sdague** [Qiskit/qiskit-ibm-runtime#1647]
**What is the expected feature or enhancement?**

In the rare times when the IBM Quantum service is in maintenance, there is no longer any API available to the user, and the site is fully replaced with a maintenance page - html, returns a 200. 

The runtime client should catch these items as a specific exception when expecting JSON, and convert to an exception that the service is in maintenance mode with a link to the page.

**Acceptance criteria**

**Comment by ihincks** [comment]
To make sure I understand, a 200 is expected when in maintenance mode, and there isn't a plan to change it to, eg, 503?

See also https://github.com/Qiskit/qiskit-ibm-runtime/issues/1637

**Comment by sdague** [comment]
> To make sure I understand, a 200 is expected when in maintenance mode, and there isn't a plan to change it to, eg, 503?
> 
> See also #1637

When in maintenance mode, there is no service to return a 503. It's a static html page that replaces everything on the domain, done at the Cloudflare level.

**Comment by kt474** [comment]
After #1640 we now catch the exception and return `Unexpected response received from server`. 

We can update to message to return something like this? 

```
Unexpected response received from server. Please check if the service is in maintenance mode https://docs.quantum.ibm.com/announcements/service-alerts. 
```
