### ISSUE TITLE
Qiskit IBM Runtime EstimatorV2 changes the user specified default number of shots

### ISSUE THREAD

**Issue by DilhanM** [Qiskit/qiskit-ibm-runtime#1657]
**Describe the bug**
Related [SE post](https://quantumcomputing.stackexchange.com/questions/38134/qiskit-ibm-runtime-estimatorv2-has-changed-the-user-specified-default-number-of).

While I am running some simulations on IBM hardware, I've noticed that the number of shots recorded in the metadata of the job is different from the number of shots I've specified.

**Steps to reproduce**

For example, I've run three circuits (with no gates, equivalent to Hartree Fock states in the Fermionic space) to calculate the expectation value of some Hamiltonian (which contains about 5000 Pauli words). I'm specifying the number of shots by

```
from qiskit_ibm_runtime import EstimatorV2 as Estimator
from qiskit_ibm_runtime import QiskitRuntimeService


shots = 4096
service = QiskitRuntimeService()
backend = service.backend("ibm_cusco")

estimator = Estimator(backend=backend) 
estimator.options.default_shots = shots
```

Looking at the metadata of the completed job, I see that the number of shots stored in job.result()[0].metadata['shots'] is different from the shots I specify. For instance, on IBM_cusco, I notice the job is executed with 8192, 4096, and 4096 shots respectively for a job where the number of shots I've specified is 4096.

**Expected behavior**

I would expect `job.result()[0].metadata['shots']` to have the same number I specify as `estimator.options.default_shots`.

**Suggested solutions**

**Additional Information**

I observe the following trends, even though I've admittedly only performed a handful of calculations on each device.

This seems to occur only on the Eagle processors.
Number of shots performed only has increased (doubled) or stayed the same. It has not decreased.
If the number of shots have doubled, the number of randomisations have doubled as well. The default value for randomisations is 32, but it has been increased to 64 in all the calculations where the shots have doubled.

- **qiskit-ibm-runtime version**: 0.23.0
- **Python version**: 3.11.9
- **Operating system**: MacOS Sonoma 14.4.1

**Comment by ptristan3** [comment]
@DilhanM I ran the following code (similar to the snippet you mentioned)

```
from qiskit_ibm_runtime import EstimatorV2 as Estimator
from qiskit_ibm_runtime import QiskitRuntimeService
service = QiskitRuntimeService()
backend = service.backend("ibm_cusco")

shots = 40000
estimator = Estimator(backend=backend)
estimator.options.default_shots = shots

circuit = QuantumCircuit(2)
circuit.cx(0, 1)
circuit.measure_all()

isa_circuit = transpile(circuit, backend)
observable = SparsePauliOp("II").apply_layout(isa_circuit.layout)

job = estimator.run([
    (isa_circuit, observable,),
    (isa_circuit, observable,),
    (isa_circuit, observable,)
])

result = job.result()

print('result[0].metadata[shots] = ', result[0].metadata['shots'])
print('result[1].metadata[shots] = ', result[1].metadata['shots'])
print('result[2].metadata[shots] = ', result[2].metadata['shots'])
```
and the number of shots in the results metadata is the same as I set as an option.

```
result[0].metadata[shots] =  40000
result[1].metadata[shots] =  40000
result[2].metadata[shots] =  40000
```

**Comment by kt474** [comment]
When using `EstimatorV2`, by default, twirling will calculate the shots per sample by calculating `ceil(5000/num_samples)=shots_per_sample` and then multiplying `shots_per_sample*num_samples`. Disabling twirling will result in the exact number of shots passed in with `default_shots`. 

The docs [here](https://docs.quantum.ibm.com/guides/specify-runtime-options#shots-sampler-only) go over how the shots are specified - we'll update them to be more clear
