### ISSUE TITLE
Raise warning when user attemps mitigation with local simulator

### ISSUE THREAD

**Issue by ihincks** [Qiskit/qiskit-ibm-runtime#1663]
**What is the expected feature or enhancement?**

A user has reported (but I have not confirmed; please tell me if this is wrong) that running in local simulation mode with mitigation turned on silently ignores these options. This might be confusing to users if they expect the noise profile of the simulation to be different when these options are turned on.

The request is to raise a warning in this case.

I expect there are some open questions here: is running with fake backends supposed to completely spoof the runtime execution, like cloud simulators would, and emulate all of the metadata and so forth? Or are they only required to obey the minimum contract of the base primitive classes, and put _something_ in the databin?

**Comment by jyu00** [comment]
> running in local simulation mode with mitigation turned on silently ignores these options.

It [should](https://github.com/Qiskit/qiskit-ibm-runtime/blob/1f6922c7fd21f2f9f4a14e9953d7d5e4809fe48e/qiskit_ibm_runtime/fake_provider/local_service.py#L242-L243) already raise a warning if an unsupported option is used.

**Comment by kt474** [comment]
Is this asking about mitigation in general or specific options related to mitigation? For example, setting `zne_mitigation` or `measure_mitigation` explicitly to `True` will raise a warning, but setting something like the `resilience_level` will not.

![Image](https://github.com/user-attachments/assets/d395f0fc-49cc-459d-ba76-0e6659a60266)
