### ISSUE TITLE
Failed to create QiskitRuntimeService instance if QISKIT_IBM_URL is not set

### ISSUE THREAD

**Issue by ohtanim** [Qiskit/qiskit-ibm-runtime#1668]
**Describe the bug**
When I tried to create QiskitRuntimeService instance with specifying the following 3 environment variables as documented [here](https://github.com/Qiskit/qiskit-ibm-runtime?tab=readme-ov-file#loading-account-from-environment-variables),
its instantiation was failed like below. It seems that we also need to specify QISKIT_IBM_URL environment variable. Is this expected behavior ?

```
(qiskit_runtime_1) ohtanim@ohtanim-mbp14 qiskit % python
Python 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from qiskit_ibm_runtime import QiskitRuntimeService
>>> service = QiskitRuntimeService()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ohtanim/qiskit_runtime_1/lib/python3.11/site-packages/qiskit_ibm_runtime/qiskit_runtime_service.py", line 124, in __init__
    self._account = self._discover_account(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ohtanim/qiskit_runtime_1/lib/python3.11/site-packages/qiskit_ibm_runtime/qiskit_runtime_service.py", line 248, in _discover_account
    account = AccountManager.get(filename=filename)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ohtanim/qiskit_runtime_1/lib/python3.11/site-packages/qiskit_ibm_runtime/accounts/management.py", line 195, in get
    raise AccountNotFoundError("Unable to find account.")
qiskit_ibm_runtime.accounts.exceptions.AccountNotFoundError: 'Unable to find account.'
```

**Steps to reproduce**
1) Set the following 3 environments as documented:
- QISKIT_IBM_CHANNEL
- QISKIT_IBM_INSTANCE
- QISKIT_IBM_TOKEN

2) Run python code to instantiate QiskitRuntimeService

**Expected behavior**
Work as documented.

**Suggested solutions**
Update README to add QISKIT_IBM_URL or update qiskit_runtime_service.py to not refer QISKIT_IBM_URL variable.

**Additional Information**

- **qiskit-ibm-runtime version**: 0.23.0
- **Python version**: 3.11
- **Operating system**: MacOS

**Comment by kt474** [comment]
Yeah this appears to be a bug, url should not be required
