### ISSUE TITLE
Unable to sample a Bell state more than exactly 10,000 times

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#1669]
**Describe the bug**
Sampling a Bell state on an Eagle system works for 10,000 shots, but fails for anything higher, e.g. 10,001

**Steps to reproduce**
```python

qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0,1)
qc.measure_all()

trans_qc = transpile(qc, backend)

sampler = SamplerV2(backend)
sampler.run([trans_qc], shots=10001)
```

**Expected behavior**
I should be able to sample up to the maximum allowed (100k) and it works

**Suggested solutions**
NA

**Additional Information**

- **qiskit-ibm-runtime version**: latest
- **Python version**:
- **Operating system**:

**Comment by jyu00** [comment]
> I should be able to sample up to the maximum allowed (100k) and it works

The backend was misconfigured to only allow 10k shots. That has since been fixed.
