### ISSUE TITLE
QiskitRuntimeService without parameters is able to pick up a backend, but _current_instance returns a deprecated instance with no backends

### ISSUE THREAD

**Issue by v-r0** [Qiskit/qiskit-ibm-runtime#1685]
**Describe the bug**
QiskitRuntimeService without parameters (i.e. without explicit channel, instance values) is able to pick up a backend. However, “service._current_instance” returns an instance that was removed (doesn’t have any associated backends). Running QiskitRuntimeService with that channel/instance returns the expected error 'No backend matches the criteria.'

**Steps to reproduce**
service = QiskitRuntimeService()
backend = service.least_busy(operational=True, simulator=False)
print(backend)

**Expected behavior**
Should pick up an instance with backends.

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 1
- **Python version**: 3.9.6
- **Operating system**: macOS 14.4.1

**Comment by kt474** [comment]
`_current_instance` is a private attribute that is just used to log the default instance chosen when the service is initialized. It is not meant to be used externally. If the deprecated instance is problematic, you can ask your hub admin to be removed.

**Comment by jyu00** [comment]
I don't think they were using `_current_instance` explicitly. I think the problem is that if the default instance used doesn't have any backends, `least_busy()` would fail.

I actually didn't realize if an instance is not specified, `least_busy()` only looks at the ones available from the default instance. I think it should look at all backends available to the account (but query each backend only once if it's available to multiple instances).

**Comment by kt474** [comment]
> I actually didn't realize if an instance is not specified, `least_busy()` only looks at the ones available from the default instance. I think it should look at all backends available to the account (but query each backend only once if it's available to multiple instances).

This is only the case if the service is initialized with an instance `QiskitRuntimeService(instance = '...')`, otherwise, `least__busy()` does look through all backends available. Should this not be the case? This was added in https://github.com/Qiskit/qiskit-ibm-runtime/pull/979

**Comment by jyu00** [comment]
If that's the case then this code

```
service = QiskitRuntimeService()
backend = service.least_busy(operational=True, simulator=False)
```

should not fail with 'No backend matches the criteria' as reported. I assume @v-r0 has another instance that does have backends, since the expected behavior is "Should pick up an instance with backends."
