### ISSUE TITLE
Create a simple Python script to validate backend configuration text files

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibm-runtime#169]
**What is the expected feature or enhancement?**
API team needs to update simulator configs sw-api-web #5009. We need a way to take the backend configuration text files and verify if they are good by validating them against https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/providers/models/backendconfiguration.py

I am thinking of writing a simple Python script that reads text files instead of calling an API to fetch all backend configurations and uses those to initialize the provider. We should patch the call to fetch all backend configurations with the data from the text files.

**Acceptance criteria**
Upload Python script to `qiskit-ibm-runtime` repo under a `scripts` folder.

**Comment by daka1510** [comment]
As discussed: there's also a [JSON schema](https://github.com/Qiskit/ibm-quantum-schemas/blob/main/schemas/backend_configuration_schema.json) for the backend configuration. 

Might it be an alternative option to refer the API team to this schema and use it as basis for their validation (in the programming language of their choice)?
