### ISSUE TITLE
Job results should be cached once job.result() is called

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#1691]
**What is the expected feature or enhancement?**

Getting job results has to query the API each time `job.result()` is called.  This makes code very slow, and should not have to be done more than once.  Results used to be cached, and should be again.

**Acceptance criteria**
Job results are cached

**Comment by kt474** [comment]
Caching job results was removed ~6 months ago - the logic behind the decision was that job results can be very large and the user does not have an easy way to free up the memory (discussed in [ch-performance](https://ibm-quantumcomputing.slack.com/archives/G01N0702C7N/p1715615300828279))

**Comment by jyu00** [comment]
Like @kt474 said, we removed the caching because people were complaining about memory consumption after running many jobs. And one can easily cache results locally by assigning them to a local variable.

**Comment by nonhermitian** [comment]
That's a shame
