### ISSUE TITLE
Batch docstring is incorrect

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1696]
**Describe the bug**

The docstring in Batch class currently says 

`"Similar to a session, a Qiskit Runtime batch groups a collection of iterative calls to the quantum computer."`, which is inaccurate. You cannot use Batch for an iterative algorithm. In addition, the code example submit only 1 circuit using Batch, which provides no benefit. 

**Steps to reproduce**

**Expected behavior**

The docstring and code example should properly reflect the use case for Batch. 

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by garrison** [comment]
IMHO it would be really nice if also a link were added to the docstring pointing to the information under "How is running N PUBs in job mode different from running N single-PUB jobs in batch mode?" at https://docs.quantum.ibm.com/run/execution-modes-faq.

**Comment by kt474** [comment]
fixed in #1696

**Comment by garrison** [comment]
The fix is in #1761, actually.  Thanks!
