### ISSUE TITLE
No module named 'qiskit.test'

### ISSUE THREAD

**Issue by gogagi1985** [Qiskit/qiskit-ibm-runtime#1733]
**Describe the bug**

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by ElePT** [comment]
If you see this error, you are using an older version of the package, `qiskit.test` was removed in Qiskit 1.0 and `qiskit-ibm-runtime` is compatible with 1.0 since [version 0.19.0](https://github.com/Qiskit/qiskit-ibm-runtime/releases/tag/0.19.0).
