### ISSUE TITLE
IBMNotAuthorizedError: '401 Client Error: Unauthorized for url: https://auth.quantum-computing.ibm.com/api/users/loginWithToken. Login with some authorized provider required., Error code: 3445.'

### ISSUE THREAD

**Issue by AbhiN2001** [Qiskit/qiskit-ibm-runtime#1747]
**Describe the bug**
I am getting an error when calling QiskitRuntimeService():

IBMNotAuthorizedError: '401 Client Error: Unauthorized for url: https://auth.quantum-computing.ibm.com/api/users/loginWithToken. Login with some authorized provider required., Error code: 3445.'

This same code was working perfectly fine yesterday, not sure what happened today.

**Steps to reproduce**

from qiskit_ibm_runtime import QiskitRuntimeService
QiskitRuntimeService.save_account(channel = 'ibm_quantum', token = 'token', set_as_default=True, overwrite=True)
service = QiskitRuntimeService()

I have updated my citizenship info and regenerated tokens, not sure what else I should try. I also looked at other issues and none seem to help me.

- **qiskit 1.10**:
- **Python 3.12.2**:
- **Mac**:

**Comment by jyu00** [comment]
Hello @AbhiN2001, please contact IBM Quantum Platform support who can better assist you in resolve issues with your account. You can find more information on the [Support page](https://docs.quantum.ibm.com/support).
