### ISSUE TITLE
JSON Error when retrieving job results

### ISSUE THREAD

**Issue by osamarais** [Qiskit/qiskit-ibm-runtime#1789]
**Describe the bug**
JSON error when running on real backend:

  File "/lib/python3.12/site-packages/simplejson/__init__.py", line 533, in loads
    return cls(encoding=encoding, **kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/qiskit_ibm_runtime/utils/json.py", line 331, in __init__
    super().__init__(object_hook=self.object_hook, *args, **kwargs)
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

**Steps to reproduce**
Submit a job and get the results from real backend
result = estimator.run([(ansatz, hamiltonian, [params])]).result()

**Expected behavior**
Should return job data without an error.

**Suggested solutions**
Simply replacing
`import json`
with
`import simplejson as json`
in qiskit_ibm_runtime/utils/json.py
fixes this particular issue.

**Additional Information**

- **qiskit-ibm-runtime version**: 0.23.0
- **Python version**: 3.12.3
- **Operating system**: Ubuntu 24.04 LTS  Linux 6.8.0-36-generic x86-64

**Comment by kt474** [comment]
Hi @osamarais, this has been discussed in a previous issue - https://github.com/Qiskit/qiskit-ibm-runtime/issues/1603. I believe the solution here would be to uninstall simplejson from your environment
