### ISSUE TITLE
Provide a usage function on RuntimeJob so metrics don't have to be parsed

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-ibm-runtime#1819]
**What is the expected feature or enhancement?**

The [RuntimeJob.metrics()](https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.RuntimeJob#metrics) method does not document what is in that metrics dictionary.

For the quantum channel the API docs are [here](https://api.quantum-computing.ibm.com/runtime/api#/Jobs/get_job_metrics_jid). For the cloud channel the API docs are [here](https://us-east.quantum-computing.cloud.ibm.com/openapi/#/Jobs/get_job_metrics_jid).

There are 3 different fields in there that talk about usage:

![image](https://github.com/user-attachments/assets/4caff964-f6dc-4534-a3c9-1d58128183eb)

It'd be nice if the client didn't have to know which of these to use to get the usage of a terminal-state job and instead a `usage()` method or something like that could abstract that information in the SDK.

This is sort of similar to how `Session.details()` has the `usage_time` field, but at least that's [documented](https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.Session#details).

**Acceptance criteria**

Provide a method on `RuntimeJob` to get the usage time of a job.

**Comment by jyu00** [comment]
We should do the same for Session + Batch. We'll need to update [docs](https://docs.quantum.ibm.com/guides/execution-modes#sessions-versus-batch-usage) once that's done.

**Comment by kt474** [comment]
> We should do the same for Session + Batch. We'll need to update [docs](https://docs.quantum.ibm.com/guides/execution-modes#sessions-versus-batch-usage) once that's done.

Added an issue to update the docs once this is in the newest release https://github.com/Qiskit/documentation/issues/1971
