### ISSUE TITLE
Batch.status says "pending" even if all jobs have been processed

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#1822]
**Describe the bug**
 `Batch.status()` gives `'Pending'` even after all jobs have been processed.

<img width="497" alt="Screenshot 2024-07-28 at 15 29 23" src="https://github.com/user-attachments/assets/24610b43-5fb6-4746-97c5-125f290474a7">

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by kt474** [comment]
The session will only close if calling `Batch.close()` explicitly or when using a context manager. Even if all jobs have been processed, the session can still be in an inactive state which would result in the `pending` status.
