### ISSUE TITLE
Massive slowdown between versions when calling `backend.target.qubit_properties`

### ISSUE THREAD

**Issue by chookity-pokk** [Qiskit/qiskit-ibm-runtime#1851]
**Describe the bug**
In `0.26.0` calling `backend.target.qubit_properties` takes much longer than previous versions.

**Steps to reproduce**
```
from qiskit_ibm_runtime import QiskitRuntimeService
from time import time

sevice_name = "<input-service-name>"
backend_name = "ibm_brisbane"
runtime = QiskitRuntimeService(name=sevice_name)
backend = runtime.get_backend(backend_name)

start = time()
[backend.target.qubit_properties[i] for i in range(127)]
print("Time taken for backend: ", time() - start)
```
Running the above snippet with older versions (tested with `0.21.2` and `24.1`) is significantly faster than with `0.26.0`. For older versions it takes about 1.5-2 seconds and with `0.26.0` it takes roughly 30-35 seconds.

**Expected behavior**
The time to be roughly the same between versions.

**Additional Information**

```
from qiskit_ibm_runtime import QiskitRuntimeService
from time import time

sevice_name = "<input-service-name>"
backend_name = "ibm_brisbane"
runtime = QiskitRuntimeService(name=sevice_name)
backend = runtime.get_backend(backend_name)

start = time()
target = getattr(backend, "target", None)
[target.qubit_properties[i] for i in range(127)]
print("Time taken for target: ", time() - start)
```
Running the above snippet only takes about 2 seconds on all tested versions (including `0.26.0`).

- **qiskit-ibm-runtime version**:
`0.26.0`, `0.21.2`, `0.24.1`

- **Python version**:
- 3.9
- **Operating system**:
- OSX Sonoma 14.5

**Comment by kt474** [comment]
Hi @chookity-pokk, the backend target is no longer cached but you can just store the target in a variable. 

```
qubit_properties = backend.target.qubit_properties
[qubit_properties[i] for i in range(127)]
```

This should only take a couple seconds

**Comment by chookity-pokk** [comment]
@kt474 Thank you for the clarification! Since this is expected behavior I'll close the issue.
