### ISSUE TITLE
Allow default runtime options in a QiskitRuntimeService

### ISSUE THREAD

**Issue by ihincks** [Qiskit/qiskit-ibm-runtime#1859]
**What is the expected feature or enhancement?**

I'm wondering if it would be possible to specify a `RuntimeOptions.image` when creating a QiskitRuntimeService that is used as the default value for all `.run()` calls, unless otherwise specified. I'm imagining this could be implemented by having a `runtime_options` argument in the QiskitRuntimeService constructor that is used as the base defaults whenever the `.run()` method is called. 

**Acceptance criteria**

There's a way to get all run calls to use a particular image without passing `image` to every primitive call.

**Comment by jyu00** [comment]
`RuntimeOptions` was created for custom programs and is not meant to be used directly now that we no longer support custom programs. `image` especially is only for authorized people.

> There's a way to get all run calls to use a particular image without passing image to every primitive call.

You can pass `image` only once when initializing the primitives though, e.g. 

```
image_options = {"experimental": {"image": "foo/bar"}}
sampler = Sampler(options={<real options>, **image_options})
```
