### ISSUE TITLE
Weird NoiseLearner.run parameter type in docs

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1877]
**Describe the bug**

The `NoiseLearner.run` [API page](https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.noise_learner.NoiseLearner) describes the `circuits` input type as 

<img width="811" alt="image" src="https://github.com/user-attachments/assets/f3cda75a-1dee-4999-9538-59c6ee91f9c8">

That's not exactly digestible.

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

@Eric-Arellano Maybe this is trying to reference `EstimatorPubLike` in a weird way? Estimator's API doc doesn't have this issue though. 

cc @SamFerracin 

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by Eric-Arellano** [comment]
> Maybe this is trying to reference EstimatorPubLike in a weird way? Estimator's API doc doesn't have this issue though.

Yes, that is what's going on. I'm not sure why Sphinx is expanding inlining `EstimatorPubLike` in https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.noise_learner.NoiseLearner#run but not https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.EstimatorV2#run 🤔

**Comment by Eric-Arellano** [comment]
I have a fix for this in the works 🚀 Working on this discovered another issue that I'm working on and blocks this. I hope to have it up tomorrow.
