### ISSUE TITLE
Backend configuration failure should not throw error, but warning

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibm-runtime#190]
**What is the expected feature or enhancement?**

Instantiating QiskitRuntimeService errors when configuration of a particular backend is not available.

```
HTTPError: 404 Client Error: Not Found for url: https://us-east.quantum-computing.test.cloud.ibm.com/devices/ibm_algiers/configuration
```

**Steps to reproduce**
Instantiate QiskitRuntimeService against a Standard Plan CRN which has real devices.
```
from qiskit_ibm_runtime import QiskitRuntimeService

service = QiskitRuntimeService(channel="ibm_cloud", token="asdasdsdfsdf", instance="CRN")
```

If the device configuration is fixed by the time of trying, try mocking a 404 on the /configuration API by modifying the code.

**Acceptance criteria**

Should throw warning in any scenario where a particular backend could not be instantiated, but shouldn't throw an error. Users should still be able to use the `service` if at least 1 backend is available.

**Comment by kt474** [comment]
Closing, this has been fixed
