### ISSUE TITLE
vqe qiskit runtime programme running too long

### ISSUE THREAD

**Issue by kalpakghosh** [Qiskit/qiskit-ibm-runtime#195]
**Describe the bug**
I have been trying to run this tutorial https://github.com/Qiskit-Partners/qiskit-runtime/blob/main/tutorials/vqe.ipynb, using the ibm quantum experience website but whenever I reach the stage of running  Runtime VQE: VQEProgram, the job runs for about five hours and then gets cancelled ("ran too long"). The only change made in the code is using the backends available to me (free account with access to only five qubit machines). This problem persists for all available systems and remains even when the number of shots is changed from 1024 to 100. When the number of shots is decreased to 2 and the maxiter is also set to 2, I get the error shown below( see screenshot). I believe this same error will persist even for 1024 shots and maxiter 50 (as shown in the tutorial). What can be the cause of this and how can I fix it? Is there a probable bug in the vqe qiskit runtime programme?
![Screenshot (322)](https://user-images.githubusercontent.com/83826611/157066477-55d0e443-91a2-4009-94c9-8189f79264eb.png)
![Screenshot (270)](https://user-images.githubusercontent.com/83826611/157066520-5d246ddd-6b96-436e-a475-ecf96901f8bf.png)

**Comment by rathishcholarajan** [comment]
@renier Could you please help check why this job failed `c8gdp223dihfro7ts250`?

**Comment by renier** [comment]
@jyu00 that tutorial should still work, right? I haven't been able to find any clues as to why it failed. Is there a way to turn on the `log_level` via the `provider.runtime.run()` call or `VQEProgram`?

**Comment by jyu00** [comment]
@renier I looked into this a bit because our other tests were also timing out. So far it looks like a performance issue. Our test that used to finish in 7 minutes (using ibmq_qasm_simualtor, Qiskit 0.34.2) 22 days ago now takes 12 minutes.

**Comment by AzizNgoueya** [comment]
I have the same behavior  on a real backend, even with 1 shot and 1 iteration, I always get the error `Cancelled - Ran too long`

**Comment by silviarieravi** [comment]
I find myself in the same situation since 21 days ago. In previous months, I sent vqe runtime jobs with 4 qubits and EfficientSU2 as the ansatz and it last less than an hour (e.g date : Nov 24, 2021, job id: c6f55ufalsooemjuf9jg). Now, whenever I try to run something with this size or smaller I get "Cancelled - Ran too long". I have tried in different real backends and in all of them it happens. Even for the exact "Leveraging Qiskit Runtime" tutorial code (job_id: c8el1e3j1bk6m260pe00) i get the Ran too long error. I am using IBM Quantum Lab to run the codes and the the versions of the libraries that I am using are: 
![image](https://user-images.githubusercontent.com/99652848/158202917-6cb03006-9247-4ff0-a38a-f91d9360f97f.png)

**Comment by Cryoris** [comment]
FYI We're still looking into this and it seems the `CircuitSampler` doesn't terminate even for a simple expectation value with a real backend.

**Comment by alejomonbar** [comment]
Hi everyone,
I'm having a similar problem. Executing even a simple optimization problem with QAOA and runtime in real hardware is impossible. I found that the maxiter in the optimizer is not working. Setting this parameter for COBYLA(maxiter=1) doesn't work and I guess always run the default value.

**Comment by Cryoris** [comment]
Yes, that's the same issue. We found the problem and the fix is underway 🙂

**Comment by rathishcholarajan** [comment]
Thanks @jyu00 @Cryoris @renier! Closing this issue as fixed, please reopen if you are still seeing issues.

**Comment by alejomonbar** [comment]
@rathishcholarajan @jyu00 @Cryoris @renier I still face the same problem. Now, it works well for QAOA but VQE, even for a small problem with COBYLA(maxiter=1), the program is canceled because of "run too long".

**Comment by Cryoris** [comment]
Could you post the settings or a minimal example that you were running? I just ran a minimal 1 qubit VQE on Armonk and that terminated correctly as far as I can tell.

**Comment by alejomonbar** [comment]
@Cryoris This is the QUBO:

\ This file has been generated by DOcplex
\ ENCODING=ISO-8859-1
\Problem name: portfolioOptimization

Minimize
 obj: - 0.008059504023 w0_0 - 0.022606130409 w0_1 - 0.015415473599 w0_2
      + 0.014582476783 w1_0 - 0.023514934815 w1_1 - 0.005708784120 w1_2 + [
      0.000000460358 w0_0^2 + 0.000001413460 w0_0*w0_1
      - 0.000000125588 w0_0*w0_2 + 0.000012672888 w0_1^2
      - 0.000000825215 w0_1*w0_2 + 0.000000941499 w0_2^2 + 0.000000979898 w1_0^2
      + 0.000001488766 w1_0*w1_1 + 0.000000073718 w1_0*w1_2
      + 0.000006637125 w1_1^2 + 0.000000369319 w1_1*w1_2 + 0.000000491954 w1_2^2
      ]/2
Subject To

Bounds
 0 <= w0_0 <= 1
 0 <= w0_1 <= 1
 0 <= w0_2 <= 1
 0 <= w1_0 <= 1
 0 <= w1_1 <= 1
 0 <= w1_2 <= 1

Binaries
 w0_0 w0_1 w0_2 w1_0 w1_1 w1_2
End

And this is the code:
``` Python
from qiskit_optimization.runtime import VQEClient
from qiskit_optimization.algorithms import MinimumEigenOptimizer
from qiskit import IBMQ
from qiskit.algorithms.optimizers import COBYLA
from qiskit.circuit.library import TwoLocal

intermediate_info = {'nfev': [],
                         'parameters': [],
                         'stddev': [],
                         'mean': []
                             }
    
def callback(nfev, parameters, mean, stddev):
    intermediate_info['nfev'].append(nfev)
    intermediate_info['parameters'].append(parameters)
    intermediate_info['mean'].append(mean)
    intermediate_info['stddev'].append(stddev)


ansatz = TwoLocal(6, rotation_blocks='ry', entanglement_blocks='cz')

provider = IBMQ.load_account() 
backend = provider.get_backend("ibmq_jakarta")

vqe_mes = VQEClient(ansatz=ansatz, provider=provider, backend=backend, shots=shots,
                        callback=callback, optimizer=COBYLA(maxiter=1)
vqe = MinimumEigenOptimizer(vqe_mes)
result = vqe.solve(qubo)

```
