### ISSUE TITLE
backend.target_history() caches backend properties

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1956]
**Describe the bug**

`backend.target_history()` calls `_get_properties()`:

https://github.com/Qiskit/qiskit-ibm-runtime/blob/51d897bee4c7cf28e22b6a0a0c9b2f337c23a9ba/qiskit_ibm_runtime/ibm_backend.py#L349-L355

which saves the properties of that given timestamp as `_properties`:

https://github.com/Qiskit/qiskit-ibm-runtime/blob/51d897bee4c7cf28e22b6a0a0c9b2f337c23a9ba/qiskit_ibm_runtime/ibm_backend.py#L241-L249

which means if I do 

```python
old_history = backend.target_history(datetime=<1 year ago>)
props = backend.properties()
```

I'll actually get `old_history` back in my second call. 

**Steps to reproduce**

**Expected behavior**

Historical properties should not be cached. `backend.properties()` does this correctly. 

**Suggested solutions**

Don't cache properties if datetime is provided. 

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by kt474** [comment]
Should the target also not be cached when calling `target_history()`? Currently, calling `backend.target` after `backend.target_history()` would still return the old target.

**Comment by jyu00** [comment]
> Should the target also not be cached when calling `target_history()`? Currently, calling `backend.target` after `backend.target_history()` would still return the old target.

Right. Backend properties should not be cached if an older copy is requested.
