### ISSUE TITLE
It should be possible to determine the executor used for generating a job without downloading the results

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#1983]
**What is the expected feature or enhancement?**
It is currently impossible to tell if a job was generated by a sampler or estimator without getting the result object.  It would be nice if this was possible

**Acceptance criteria**
It is possible to know if a job originated from the sampler or estimator without downloading the results

**Comment by kt474** [comment]
Does [job.primitive_id](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/base_runtime_job.py#L382) work? It returns "sampler" or "estimator" without needing the results.

**Comment by nonhermitian** [comment]
Ahh it does!  I though that was another thing like job ID.  thanks!
