### ISSUE TITLE
Inaccurate QiskitRuntimeService documentation

### ISSUE THREAD

**Issue by crect500** [Qiskit/qiskit-ibm-runtime#1984]
The constructor documentation at:

https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.QiskitRuntimeService

suggests that one can create a QiskitRuntimeService object with `channel="local"` to test locally. However, there is an `if` statement in the source code which raises a ValueError if so.

- **qiskit-ibm-runtime version**: 0.31.0

**Comment by kt474** [comment]
Hi @crect500 can you post the error message? There should be no issues with setting the channel as local. 


```
service = QiskitRuntimeService(channel="local")
```
