### ISSUE TITLE
Consider handling rzz validation for parametrized angles

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-ibm-runtime#2000]
`rzz` angle is allowed only in the range `[0, pi/2]`.
If a user writes `rzz(-1, qubit)` or `rzz(3, qubit)` (i.e., the angle is a number) then our ISA validation will correctly fail.
But, if the user writes `rzz(param, qubit)`, where param is a `qiskit.circuit.Parameter`, and assigns a negative (or greater than pi/2) value to the parameter - this will not be caught by the validation process, and therefore will fail much later in the stack.

**Comment by yaelbh** [comment]
See Slack thread: https://ibm-quantumcomputing.slack.com/archives/C06NWM5FUKC/p1730189009542039

**Comment by yaelbh** [comment]
I want to change the signature of `is_isa_circuit`, such that it receives a pub instead of a circuit, but I don't know if it's considered to be an API break that requires deprecation.

@jyu00 @kevinsung @mberna Does it require deprecation?

To be on the safe side, for now I'll leave ISA validation unchanged. I'll add two new functions, `validate_rzz_pub` and `is_rzz_pub`.

**Comment by kevinsung** [comment]
I don't really work on this repository, perhaps you mean to ping @kt474 .
