### ISSUE TITLE
Add a visual description for twirling strategy

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#2004]
**What is the expected feature or enhancement?**

We got some questions about what each twirling strategy does. A visual description would be very helpful. Something like

![Image](https://github.com/user-attachments/assets/bdd4fc4d-1b92-485e-8b23-10a03ee2054d)

Although obviously that picture should be re-drawn. 

**Acceptance criteria**

**Comment by atalle** [comment]
@jyu00 Here is the re-drawn twirling strategies diagram!

![Image](https://github.com/user-attachments/assets/916bbc73-735f-4a67-accf-841f02a81738)
