### ISSUE TITLE
Fix failing doc workflow action

### ISSUE THREAD

**Issue by daka1510** [Qiskit/qiskit-ibm-runtime#21]
**What is the expected feature or enhancement?**
The `doc` workflow (in particular the `tox -edocs`) command currently fails. This needs to be fixed to fix the CI checks.

![image](https://user-images.githubusercontent.com/16404496/142434402-269ed194-3841-4616-9f34-fac0353f8152.png)
![image](https://user-images.githubusercontent.com/16404496/142433617-6e3a33e6-460d-4d3d-89b6-5ea89566d766.png)

**Preliminary analysis**
Likely caused by invalid automodule references in some of the `.rst` files in https://github.com/Qiskit/qiskit-ibm-runtime/tree/main/docs/apidocs. Needs updates to accomodate the repository split.

**Comment by rathishcholarajan** [comment]
This is now fixed.
