### ISSUE TITLE
Enable automated code coverage reports

### ISSUE THREAD

**Issue by daka1510** [Qiskit/qiskit-ibm-runtime#22]
**What is the expected feature or enhancement?**
I like the use of https://coveralls.io/ in https://github.com/Qiskit/qiskit-terra and other qiskit packages for reviewing code coverage.

**Goal**
Let's discuss and decide as part of this issue if we want something similar (e.g. ability to review code coverage over time, to see comments in PRs with coverage details [[example]](https://github.com/Qiskit/qiskit-terra/pull/7288#issuecomment-972798040)) in the provider repositories.

See also
- https://coveralls.io/github/Qiskit
- https://github.com/Qiskit/qiskit-terra/issues/771

**Comment by rathishcholarajan** [comment]
It'd be nice to add coverage info to README.
