### ISSUE TITLE
Sampler program fails with missing circuit_indices

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#222]
**Describe the bug**
Running sampler with

```python

# Specify the program inputs here.
program_inputs = {"circuits": qc,
                  'run_options': {'shots': 1e4}}

# Specify the backend name.
options = {"backend_name": 'ibm_algiers'}
```
gives

TypeError: main() missing 1 required positional argument: \'circuit_indices\'\n

**Steps to reproduce**

**Expected behavior**
It should work

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.2
- **Python version**: 3.9
- **Operating system**: OSX

**Comment by nonhermitian** [comment]
Similar for estimator:

```
TypeError: main() missing 2 required positional arguments: \'circuit_indices\' and \'observable_indices\'\
```

**Comment by rathishcholarajan** [comment]
@nonhermitian It was decided in a discussion with @levbishop @jyu00 that these fields be mandatory. I will slack you that conversation link.

**Comment by rathishcholarajan** [comment]
This is working as designed. Can we close this?
