### ISSUE TITLE
Cannot pass readout mitigator class

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#223]
**Describe the bug**
The sampler primitive says it can take a readout mitigator:

```python
readout_mitigator: BaseReadoutMitigator | None = None
```

However if I try to pass a mitigator object that is a subclass of `BaseReadoutMitigator`, eg.

https://github.com/Qiskit/qiskit-terra/blob/592b9acb8d211dd3950c6be081da592cff9c00f2/qiskit/result/mitigation/local_readout_mitigator.py#L27

then I get a serialization error

```
File "/opt/miniconda3/envs/qiskit/lib/python3.10/site-packages/qiskit_ibm_runtime/utils/json.py", line 248, in default
    return super().default(obj)
  File "/opt/miniconda3/envs/qiskit/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type LocalReadoutMitigator is not JSON serializable
```

**Steps to reproduce**
Try to pass a readout mitigator class

**Expected behavior**
It should work

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.2.0
- **Python version**: 3.9
- **Operating system**: OSX

**Comment by rathishcholarajan** [comment]
I've opened this issue in an internal repository where it belongs so that the readout_mitigator option can be removed. Thanks.
