### ISSUE TITLE
User should be able to get the time taken for a runtime job programatically.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#224]
**What is the expected feature or enhancement?**
There should be a way to recover the full elapsed time a job takes from the job and/or result instance.

**Acceptance criteria**
And user sees the total elapsed time, i.e the time the user would be billed for on the IBM Cloud

**Comment by rathishcholarajan** [comment]
@renier @tmittal947 are you aware of any tickets open on API side to expose this information?

**Comment by rathishcholarajan** [comment]
NVM got it from the team, the API to expose this info is being worked upon in ntc github tickets 1144 and 1252.

**Comment by nonhermitian** [comment]
I am personally fine with whatever mechanism people decide upon. However one should make sure that the time per step values correspond to the billed times where appropriate

**Comment by rathishcholarajan** [comment]
The metrics API is ready and this issue is now unblocked. https://us-east.quantum-computing.cloud.ibm.com/openapi#/Jobs/get_job_metrics_jid

**Comment by rathishcholarajan** [comment]
Spoke to @tmittal947 and @renier. Let's just have a `job.metadata()` method that returns whatever is returned by `/jobs/{id}/metrics` API. And then in the future we will think about returning this information in the result metadata.
