### ISSUE TITLE
An user should be able to tell which backend the job ran on if none was passed.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#225]
**What is the expected feature or enhancement?**
If no `backend_name` is passed, an user should still be able to programmatically find out which system their job ran on.

**Acceptance criteria**
The above is true.

**Comment by renier** [comment]
This should already be true at the api level. If not, we can take it as a defect.

It might be something in the client is not exposing it or it’s not clear how to get it otherwise.

**Comment by nonhermitian** [comment]
Ok yeah no it was my mistake.  I missed `job.backend` queries for the device the job is running on.
