### ISSUE TITLE
Skip transpilation does not work

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#237]
**Describe the bug**

Setting `skip_transpilation` does not actually skip transpilation

**Steps to reproduce**
```python

N = 27
qc = QuantumCircuit(N, N-1)
qc.x(N-1)
qc.h(range(N))
qc.cx(range(N-1),N-1)
qc.h(range(N-1))
qc.barrier()
qc.measure(range(N-1), range(N-1))

# Specify the program inputs here.
program_inputs = {"circuits": [qc]*30,
                  'run_options': {'shots': 1e4},
                  'circuit_indices': list(range(30)),
                  'skip_transpilation': True,
                  }

# Specify the backend name.
options = {}

job = service.run(
    program_id="sampler",
    options=options,
    inputs=program_inputs,
)
```

Should fail since `h` is not in the basis set, but the job returns a result indicating that it indeed transpiled

**Expected behavior**
Should error

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.2.0
- **Python version**: 3.10
- **Operating system**: OSX

**Comment by rathishcholarajan** [comment]
I've opened this issue in an internal repo where I believe the fix needs to go.
