### ISSUE TITLE
An user should be able to verify that their run options were successfully used

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#240]
**What is the expected feature or enhancement?**
It is impossible to get verification that `run_options` other than `shots` are being applied successfully.  There should be some way to verify that the program did indeed use the options I send it.

**Acceptance criteria**
The user has some notification, in the return object or the like, that the requested options were applied.

**Comment by rathishcholarajan** [comment]
@jyu00 @daka1510 I am not sure if any other run options other than `shots` is supported.
@nonhermitian are there other options that you see are working but are just not being returned in metadata like `shots`?

**Comment by nonhermitian** [comment]
I think `rep_delay` works, probably `use_measure_esp` as well.  In the case of the former at least it raises if I throw a bad value, so the code is processing it. In the latter there is no indication.  To be fair, there has never been a good indication that certain options are actually successfully set.  However since the runtime further abstracts things, have some visibility here would be nice

**Comment by jyu00** [comment]
I gave Becky this list so it should be documented somewhere in the IBM Cloud doc:

```
shots 
qubit_lo_freq
meas_lo_freq
schedule_los
rep_time
rep_delay
init_qubits
header
use_measure_esp
```

The primitive programs don't current enforce this, but we can add that check. (And return the values used if you prefer)

**Comment by daka1510** [comment]
Interesting point, @nonhermitian. The response of the Jobs API (`GET /jobs/:job_id`) already returns the supplied input parameters but I understand your concern that this does not give enough confidence that the options are actually set at runtime. 

```json
{
  "id": "c92lvubahk6r9e4jr680",
  "backend": "ibmq_qasm_simulator",
  "state": {
    "status": "Completed"
  },
  "params": {
    "circuits": [
      {
        "__type__": "QuantumCircuit",
        "__value__": "..."
      }
    ],
    "run_options": {
      "rep_delay": 0.0001, <-- should an invalid value here fail job creation/fail a job at runtime?
      "invalid_bla": "invalid_blub", <-- should this fail job creation/fail a job at runtime?
      "shots": 1024
    },
    "circuit_indices": [
      0
    ]
  },
  "program": {
    "id": "sampler"
  },
  "created": "2022-03-31T08:02:01.138821Z",
  "runtime": "qiskit-program:948cbf9",
  "status": "Completed"
}
```

I wonder if a stricter schema validation against the support input parameters (either at runtime, or at job creation time) would help to address your concerns. That way users could not supply invalid options. If options are listed in the job definition and the job succeeds, users can be sure that they were applied correctly.

Trying to understand what exactly makes you want to verify that what you specified is actually used. Missing trust in the APIs to pass it forward correctly? Missing trust in the user to specify the parameters in the correct form?

**Comment by nonhermitian** [comment]
So take for example `use_measure_esp`.  If using this I have no idea if it is actually being applied on the backend.  I have to trust that it is.  Moreoever it is hard to determine what the default configuration is in this case.  Eg the docstring says

https://github.com/Qiskit/qiskit-ibm-provider/blob/6ee9e23398adf01a5be7dcc2eb4d0ae8ab943cef/qiskit_ibm_provider/ibm_backend.py#L179

and then I have to go and look further down to see what this means:

https://github.com/Qiskit/qiskit-ibm-provider/blob/6ee9e23398adf01a5be7dcc2eb4d0ae8ab943cef/qiskit_ibm_provider/ibm_backend.py#L243

and then I need to go to the config to determine what setting was actually applied as default.

This all makes things very confusing.  It would be nice to have some information that says "the backend was configured in this way when the jobs was run".  Explicit rather than implicit.

**Comment by nonhermitian** [comment]
The primitives only add to this as there are a lot more configurable options in the primitives.

**Comment by kt474** [comment]
@t-imamichi @ikkoham thoughts on this? There is currently no way to verify that the `run_options` passed are actually applied to the backend. Should this be handled in the base classes or in the actual sampler/estimator classes?

**Comment by renier** [comment]
>  If using this I have no idea if it is actually being applied on the backend. I have to trust that it is. Moreoever it is hard to determine what the default configuration is in this case.

This is a little confusing. I'm not sure how things can change to make the user not have to trust the service in this way. Even returning some information implies that the user trusts it is correct.

>  It would be nice to have some information that says "the backend was configured in this way when the jobs was run". Explicit rather than implicit.

I think that should be evident from the calling code itself. First, the runtime programs/primitives should document all the supported parameters and all their defaults including the `run_options`, and if you override any in your calling code you'd be doing it knowingly at that point.

The task here would be to check and ensure that:
1. The docs document all the options we support
2. That we do pass the options down as documented

If there are options that are desired but not explicitly supported (i.e. missing from the docs) then that's a different issue that can be separated out.

@jyu00 Is this still a good [list](https://github.com/Qiskit/qiskit-ibm-runtime/issues/240#issuecomment-1083545708) to start from to check 1 and 2 above?

**Comment by kt474** [comment]
> The task here would be to check and ensure that:
> 
> 1. The docs document all the options we support
> 2. That we do pass the options down as documented
> 
> If there are options that are desired but not explicitly supported (i.e. missing from the docs) then that's a different issue that can be separated out.
> 
> @jyu00 Is this still a good [list](https://github.com/Qiskit/qiskit-ibm-runtime/issues/240#issuecomment-1083545708) to start from to check 1 and 2 above?

Just following up here - is the list above still accurate?

**Comment by jyu00** [comment]
I think so? I haven't looked at the latest primitive code to see if something has changed.
