### ISSUE TITLE
IBMSampler should take a single circuit as input

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#242]
**Describe the bug**
This fails:

```python
with ibm_sampler(circuits=qc, skip_transpilation=False) as sampler:
```

with: `AttributeError: 'tuple' object has no attribute 'parameters'`

However `circuits=[qc]` works.

**Steps to reproduce**

**Expected behavior**
The docstrings say I should be able to pass a single circuit.

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by rathishcholarajan** [comment]
This issue was fixed here https://github.com/Qiskit/qiskit-ibm-runtime/pull/220 and will be released soon.
