### ISSUE TITLE
Not clear which run options are supported

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#243]
**What is the expected feature or enhancement?**
The docstrings list `**run_options`` as inputs to primitives like the `Sampler` but not all options that `backend.run()` support are supported here, eg `memory=True` does nothing.  

The docs should specify which run options are actually supported.

**Acceptance criteria**
It is clear what options are supported.

**Comment by renier** [comment]
I think we can close this as a dup of #302 and or #240 @rathishcholarajan

**Comment by nonhermitian** [comment]
If your solution to #302 and #240 is just documentation tweaks then yes, can probably be closed.

**Comment by kt474** [comment]
Closing in favor of #240
