### ISSUE TITLE
Different number of circuits and circuit_indices throws an error 

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#244]
**Describe the bug**
```python

with ibm_sampler(circuits=[qc, qc2], skip_transpilation=False) as sampler:
    result = sampler(
        circuit_indices=[0],
        shots=1e4,
    )
```
throws

```
The number of circuits (1) does not match the number of parameter sets (2).
```

**Steps to reproduce**

**Expected behavior**
It should work

**Suggested solutions**

**Additional Information**
This was reported earlier and I think it was addressed somewhere, but has not made it into production.  Using this to track.

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by rathishcholarajan** [comment]
qiskit-ibm-primitives PR 11 addressed this, yet to be deployed.

**Comment by rathishcholarajan** [comment]
This has been deployed in production. Closing.
