### ISSUE TITLE
USer should be able to get job id from calls to IBMSampler

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#245]
**What is the expected feature or enhancement?**
It should be possible to get job ids for calls to the sampler.  It does show up in the IQX jobs pane.

**Acceptance criteria**
The user can get their job ID

**Comment by rathishcholarajan** [comment]
This is possible right now with `sampler._session._job` or `sampler._session.info()`. But we should expose a public method instead of asking users to use private variables.

**Comment by rathishcholarajan** [comment]
The GET /jobs API now supports filtering by session id when fetching jobs. (currently only available on staging)  So it is now possible to expose something at the service level like:
```
service.session(session_id)
```
and it should return any info about the session and an array of all the `IBMJob` objects from the session.

**Comment by nonhermitian** [comment]
Note that doing something like described in https://github.com/Qiskit/qiskit-ibm-runtime/issues/334 also resolves this is a nice way
