### ISSUE TITLE
Cannot bind parameters to a circuit in the IBMSampler

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#246]
**Describe the bug**
This fails:

```python

from qiskit.circuit.library import TwoLocal
qc = TwoLocal(4, rotation_blocks =['rx', 'rz'])

with ibm_sampler(circuits=[qc], skip_transpilation=False) as sampler:
    params = np.random.random(qc.num_parameters)
    sampler(
        circuit_indices=[0],
        circuit_parameters=[params],
        shots=1e4,
    )
```

with

```
The number of values (0) does not match the number of parameters (32) for the 0-th circuit.
```

However I can do:

```python

bind_qc = qc.bind_parameters(params)

```

and it works just fine.

**Steps to reproduce**
Try above

**Expected behavior**
It should work

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.2
- **Python version**:
- **Operating system**:

**Comment by rathishcholarajan** [comment]
@nonhermitian You have a non-existent parameter `circuit_parameters` in your code. The correct name is `parameter_values`. Could that be the issue here?

**Comment by rathishcholarajan** [comment]
I think this issue is fixed in qiskit-ibm-primitives pull request 11. Just not deployed yet.

**Comment by nonhermitian** [comment]
This looks to be resolved.
