### ISSUE TITLE
There is no way to cancel a call to the IBMSampler

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#248]
**Describe the bug**
There is no way to cancel a call to the `IBMSampler`.  This is important as I would like to cancel things that I might be charged for, or things that I may have made a mistake on (e.g. forgot measurements)

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by nonhermitian** [comment]
If I request more than one result within the context, then it only closes the first.  Is that what you are saying here?

**Comment by rathishcholarajan** [comment]
Yes it closes the first job, which should ideally close the session (since the first job id is used as the session id).

**Comment by nonhermitian** [comment]
I just verified that this indeed cancels an active job attached to the session.
