### ISSUE TITLE
Dead links in qiskit-ibm-tutorials

### ISSUE THREAD

**Issue by fvarchon** [Qiskit/qiskit-ibm-runtime#286]
**Describe the bug**
All tutorials in the qiskit-ibm-tutorial [page](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials.html)  contain a dead link at the top. 

**Steps to reproduce**
Open a tutorial, for example: https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/how-to-getting-started-with-sampler.html

At the top it says 'This page was generated from [docs/tutorials/how-to-getting-started-with-sampler.ipynb](https://github.com/Qiskit/qiskit-ibm-runtime/blob/0.4/docs/tutorials/how-to-getting-started-with-sampler.ipynb).'

The link points to nowhere

**Comment by HuangJunye** [comment]
@fvarchon Thanks for reporting the bug. 

@rathishcholarajan The links (https://github.com/Qiskit/qiskit-ibm-runtime/blob/0.4/docs/tutorials/grover_with_sampler.ipynb) point to the 0.4 branch which does not contain these tutorials. Should the links be pointing to the main branch instead? I think this applied to all tutorials.
