### ISSUE TITLE
backend specification is not optional

### ISSUE THREAD

**Issue by johannesgreiner** [Qiskit/qiskit-ibm-runtime#288]
**Describe the bug**
https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/tutorials/how-to-getting-started-with-sampler.ipynb says:
The Sampler takes in:
[...]
- **Optional**: The **backend** to run on. If one is not specified, the least busy backend is used.

However, not specifying a backend yields an error

**Steps to reproduce**
```
with Sampler(circuits=bell, service=service) as sampler:
result = sampler(circuit_indices=[0], shots=1024)
print(result)
```

--> `IBMInputValueError: '"backend_name" is required field in "options" for ``ibm_quantum`` runtime.'`

**Expected behavior**
run on least busy backend

**Suggested solutions**
make backend_name optional as described or change relevant tutorial text. 

**Additional Information**

- **qiskit-ibm-runtime version**: 0.4.0
- **Python version**: 3.8.2
- **Operating system**: Windows 10

**Comment by johannesgreiner** [comment]
@y4izus @rathishcholarajan or @HuangJunye might be able to comment

**Comment by HuangJunye** [comment]
@johannesgreiner I could not reproduce the bug. I ran the following code and it could run without issues. Can you share the full code you have ran?

```python
from qiskit_ibm_runtime import QiskitRuntimeService, Sampler
from qiskit import QuantumCircuit

service = QiskitRuntimeService()

bell = QuantumCircuit(2)
bell.h(0)
bell.cx(0, 1)
bell.measure_all()

# executes a Bell circuit
with Sampler(circuits=bell, service=service) as sampler:
    result = sampler(circuit_indices=[0], shots=1024)
    print(result)
```

**Comment by nonhermitian** [comment]
For the IQX version it does not work. On the Cloud version it does.

**Comment by rathishcholarajan** [comment]
@HuangJunye Yes the guides need to be updated to specify the auto select backend functionality is only for IBM Cloud.

This is already specified in doc strings:
https://github.com/Qiskit/qiskit-ibm-runtime/blob/bb227fef16e96e5ce520e315c2ffd1a8d088fa74/qiskit_ibm_runtime/estimator.py#L54-L56

**Comment by HuangJunye** [comment]
I improved the program input section for the getting started guides in #290. 

I also need to add the backend option in the grover tutorial which does not specify the backend and therefore will fail on IBM Quantum. But one thing I noticed among 4 primitives tutorials is that some use `backend` key while others use `backend_name`. Which one is prefered and how can I find out the list of all options for a given runtime program? @rathishcholarajan

**Comment by johannesgreiner** [comment]
@HuangJunye yes thank you I think it's a lot clearer now! 
Users may wonder why the difference exists, but let's see how that devlops in the future. 
Maybe "backend: Optional instance" --> backend: (Optional) instance"? Since for `channel='ibm_quantum'` it's required

**Comment by rathishcholarajan** [comment]
> I improved the program input section for the getting started guides in #290.
> 
> I also need to add the backend option in the grover tutorial which does not specify the backend and therefore will fail on IBM Quantum. But one thing I noticed among 4 primitives tutorials is that some use `backend` key while others use `backend_name`. Which one is prefered and how can I find out the list of all options for a given runtime program? @rathishcholarajan

backend_name is enough, even if backend object is passed we only take the name from it

These are the only options supported now https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/estimator.py#L52 (backend, image, log_level)

**Comment by rathishcholarajan** [comment]
> @HuangJunye yes thank you I think it's a lot clearer now! Users may wonder why the difference exists, but let's see how that devlops in the future. Maybe "backend: Optional instance" --> backend: (Optional) instance"? Since for `channel='ibm_quantum'` it's required

Sure I can update this in the doc strings...
