### ISSUE TITLE
changes to coupling map from backend change the instance attribute as well

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#295]
Grabbing the coupling map from a backend configuration and making changes to the resulting list modifies the backend instance version as well. E.g.

```python
cmap = backend.configuration().coupling_map
for edge in cmap:
    cmap.remove(edge[::-1])
```

There are likely other attributes that can be modified in this way as well.

- **qiskit-ibm-runtime version**: 0.19.1
- **Python version**:
- **Operating system**:

**Comment by nonhermitian** [comment]
Sorry, this is in the wrong place.

**Comment by nonhermitian** [comment]
Yes, probably

**Comment by HuangJunye** [comment]
@mtreinish Can you help transfer this issue to Terra? I do not have the permissions
