### ISSUE TITLE
simulator_qasm3 does not work

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#298]
**Describe the bug**
the runitme lists `simulator_qasm3` as a backend.  However sending circuits to that backend only gives errors

22-04-29T09:11:45.377222604Z   File "/usr/local/lib/python3.8/site-packages/qasm3_simulator/qasm3_simulator.py", line 194, in simulate\n2022-04-29T09:11:45.377243304Z     if os.path.isfile(qasm3):\n2022-04-29T09:11:45.377249637Z   File "/usr/local/lib/python3.8/genericpath.py", line 30, in isfile\n2022-04-29T09:11:45.377258458Z     st = os.stat(path)\n2022-04-29T09:11:45.377263997Z TypeError: stat: path should be string, bytes, os.PathLike or integer, not list\n'

**Steps to reproduce**
```python

program_inputs = {
    'circuits': ReferenceCircuits.bell(),
     'circuit_indices': [0],
}
options = {'backend_name': 'simulator_qasm3'}
job = service.run(
    program_id="sampler",
    options=options,
    inputs=program_inputs)
print(f"job ID: {job.job_id}")
result = job.result()

```

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by jyu00** [comment]
You can only use the `qasm3-runner` program for `simulator_qasm3` backend. Now you're going to ask where is that documented, and the answer is it isn't because `simulator_qasm3` is not a publicized backend.
