### ISSUE TITLE
Runtime backends should have their service as an attribute / method

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#300]
**What is the expected feature or enhancement?**

In many cases external code is wrapping calls to things like `backend.run()` that need to be replaced with `Sampler`.  However doing so, and maintaining compatibility is difficult.  Namely, I must change the external API to take a service instance as well.  Instead, it would be nice if the backend instance itself could be used to set the service from which it originated.  In that case the external API can remain unchanged.

**Acceptance criteria**

**Comment by rathishcholarajan** [comment]
@mtreinish Is this something that can be added in qiskit-terra? Similar to the `provider` property can we have a `service` property in the BackendV2 class. For this we might have to create service base classes in terra though which I know you weren't in favor of.

The other option is to just expose `service` as a property in `IBMBackend` class.
