### ISSUE TITLE
Runtime should load IQX credentials from Qiskit if available

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#301]
**What is the expected feature or enhancement?**
The two different accounts for the provider and runtime make it difficult to work with code in a backward compatible manner.  The IQX account information used by Runtime (i.e the token) is the same in both cases.  As such, Runtime should be able to init a service instance from the Qsikit config credentials if none are present in the Runtime json

**Acceptance criteria**

**Comment by rathishcholarajan** [comment]
In my opinion it is super easy for the user to save the token again in qiskit-ibm-runtime json. This will be the less confusing experience. Using qiskit config file as a fallback to the new json file is more confusing and hard to explain. This will introduce a lot of unnecessarily complex code that was being used to read and write to the qiskit config file, which we made much effort to remove and make the code a lot simpler to use a json file. @tmittal947 thoughts?

Note: For Quantum lab users we are automatically creating the runtime json file with their IBM Quantum credentials when the jupyterlab image initializes.

**Comment by nonhermitian** [comment]
It is easy, but also unnecessary. You could internally import from the old config and populate the new json.  That is also not hard to do and makes things frictionless. Eg when everything has to go through runtime, the enduser needs to do nothing to migrate over.

**Comment by rathishcholarajan** [comment]
Yes copying over credentials and creating json file automatically when it doesn't exist sounds good.
