### ISSUE TITLE
No way of knowing what run options are being applied

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#302]
**Describe the bug**
There is no indication if various `run_option` kwargs are actually being applied.  Eg. all of these pass through and return results:

```
from qiskit_ibm_runtime import Sampler
with Sampler(circuits=[ReferenceCircuits.bell()]*3, service=service, 
             options={ "backend": backend.name}) as sampler:
    result = sampler(circuit_indices=[0, 1, 2], transpile_config={'optimization_level': 3})
    print(result)

from qiskit_ibm_runtime import Sampler
with Sampler(circuits=[ReferenceCircuits.bell()]*3, service=service, 
             options={ "backend": backend.name}) as sampler:
    result = sampler(circuit_indices=[0, 1, 2], transpile_config={'hello_there': 3})
    print(result)

from qiskit_ibm_runtime import Sampler
with Sampler(circuits=[ReferenceCircuits.bell()]*3, service=service, 
             options={ "backend": backend.name}) as sampler:
    result = sampler(circuit_indices=[0, 1, 2], transpiler_config={'is-it-transpile_or_transpiler': 3})
    print(result)
```
**Steps to reproduce**

**Expected behavior**
The program should error on invalid options. 

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by rathishcholarajan** [comment]
Make sure metadata is returned from program.

**Comment by renier** [comment]
At the least, any `run_options` should be documented here https://quantum-computing.ibm.com/services?program=sampler .

Validation of input parameters that are used is implicit. When it comes to dictionaries being passed, the keys are not checked to see if they are part of a known set. I think this is fine, if the docs are clearly documenting all the parameters that would work.

**Comment by renier** [comment]
Is this, #243 and #240 duplicates of each other?

**Comment by nonhermitian** [comment]
There is really nothing in the services description that tell me what the valid options are:

![image](https://user-images.githubusercontent.com/1249193/176409326-bcf5d093-66a6-4d12-b18b-5bb1db09730c.png)

And because there is no validation of inputs, nor any confirmation that my settings sticks, it is not clear if I am setting things correctly.

**Comment by kt474** [comment]
Moving this issue to ntc-ibm-programs so `estimator.json` and `sampler.json` can be updated
Will update the relevant docs in this repo in issue #240
