### ISSUE TITLE
More meaningful error handling

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibm-runtime#305]
**What is the expected feature or enhancement?**
> Copied from internal repo - originally created by Darius.

In case of an error thrown by a server, the following piece of code in `estimator.py` does not handle it nicely:
```
raw_result = self._session.read()
return EstimatorResult(
    values=raw_result["values"],
    metadata=raw_result["metadata"],
)
```
and generates the following error for the user:
```
File "/qiskit-ibm-runtime/qiskit_ibm_runtime/estimator.py", line 108, in __call__
    values=raw_result["values"],
TypeError: string indices must be integers
```
It does not include information about the original error from the server unless someone changed the estimator code to print `raw_result` before running the job. Perhaps some errors could be caught in the estimator class with a server message error printed for convenience and clarity?

**Acceptance criteria**

**Comment by kt474** [comment]
Closing for now, error handling has greatly improved
