### ISSUE TITLE
Copy unit tests from terra for qpy module

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibm-runtime#307]
**What is the expected feature or enhancement?**
The qpy module was forked from terra in https://github.com/Qiskit/qiskit-ibm-runtime/pull/250. Unit tests should also be copied to qiskit-ibm-runtime.

**Acceptance criteria**

**Comment by kt474** [comment]
Qpy has been removed from this repo so closing for now
