### ISSUE TITLE
Save credentials in JSON file

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibm-runtime#31]
**What is the expected feature or enhancement?**

When saving credentials to disk today we use `~/.qiskit/qiskitrc` file. We can refactor and simplify a lot of the code around this functionality by saving credentials in a JSON file.

Something like in `~/.qiskit/qiskit-ibm.json`.

```
{
    "cloud": {
        "token": "<paste_API_KEY_here>",
        "locator": "<paste_CRN_here>"
    },
    "legacy": {
        "token": "<paste_API_KEY_here>",
        "locator": "<paste_API_URL_here>",
        "verify": True,
        "default_hgp": "hub/group/project"
    },
    "cloud-staging": {
        "token": "<paste_Staging_API_KEY_here>",
        "locator": "<paste_Staging_CRN_here>"
    },
    "legacy-staging": {
        "token": "<paste_Staging_API_KEY_here>",
        "locator": "<paste_API_URL_here>",
        "verify": True,
        "default_hgp": "hub/group/project"
    }
}
```

We can allow users to store multiple credentials by specifying a `name` when saving an account. In the above example the user has saved their staging cloud and legacy accounts by passing the names `cloud-staging` and `legacy-staging`.

```
IBMRuntimeService.save_account(token, name="cloud-staging") # save like this
IBMRuntimeService(name="cloud-staging") # initialize like this
```

**Comment by jyu00** [comment]
A couple suggestions:

1. Don't add the word `runtime` to the filename, so we can use a single credential file for all `qiskit-ibm` repos. This way if a user needs to update their token, for example, they don't have to do it multiple times.
2. Most users don't/shouldn't have staging accounts. If we are going to allow multiple accounts, we should let people name them, e.g. 

```
IBMRuntimeService.save_account(token, name="personal")
IBMRuntimeService(name=personal)
```

**Comment by rathishcholarajan** [comment]
@jyu00 Sounds good. I've updated the description. Thanks!

**Comment by daka1510** [comment]
Account configuration is now stored in a JSON file at `~/.qiskit/qiskit-ibm.json` 

**Code Reference**
https://github.com/Qiskit/qiskit-ibm-runtime/blob/31b0597361286f0e9d5911ad78195f7b111ff0e9/qiskit_ibm_runtime/accounts/management.py#L22
