### ISSUE TITLE
There should be a backward compatible way of calling runtime within a class / function

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#327]
When dealing with third-party libraries it is common to find situations where a IBM Quantum backend is wrapped inside of a Class or function, e.g.

```python

wrapped_backend = wrapper(backend)
```

This is so that backends from multiple vendors can all be treated the same within the third-party framework.  This is akin to how the `QuantumInstance` does things.  The question is: how to call the Runtime in a backward compatible way in this situation?

To do this one must have standard provider backends work as well as backends from the Runtime (which are not the same).  Because the Runtime requires a service instance one must construct a service instance from a Provider backend.  The only way I was able to do this was via:

```python

iqx_token = backend._api_client._credentials.token
service = QiskitRuntimeService(token=iqx_token, channel='ibm_quantum')

```
However, this requires two calls to private attributes, and is thus not a stable interface.  For the Runtime backend, it is equally challenging.  Namely I must pass two objects, a service instance and the backend (or backend name).  This is not really ideal as I must carry around two different objects when only one is really required and it means a different calling signature depending on where the backend comes from. This is what motivated #300.

Finally, none of this is compatible with the Aer simulator (nor BasicAer) that is needed for using simulators and/or testing in CI environments.

It would be nice if there was a better way to incorporate Runtime in these situations and a guide for how to migrate existing code over into the Runtime format.

**Comment by rathishcholarajan** [comment]
> When dealing with third-party libraries it is common to find situations where a IBM Quantum backend is wrapped inside of a Class or function, e.g.
> 
> ```python
> wrapped_backend = wrapper(backend)
> ```
> 
> This is so that backends from multiple vendors can all be treated the same within the third-party framework. This is akin to how the `QuantumInstance` does things. The question is: how to call the Runtime in a backward compatible way in this situation?
> 
> To do this one must have standard provider backends work as well as backends from the Runtime (which are not the same). Because the Runtime requires a service instance one must construct a service instance from a Provider backend. The only way I was able to do this was via:
> 
> ```python
> iqx_token = backend._api_client._credentials.token
> service = QiskitRuntimeService(token=iqx_token, channel='ibm_quantum')
> ```
> 
> However, this requires two calls to private attributes, and is thus not a stable interface. For the Runtime backend, it is equally challenging. Namely I must pass two objects, a service instance and the backend (or backend name). This is not really ideal as I must carry around two different objects when only one is really required and it means a different calling signature depending on where the backend comes from. This is what motivated #300.

The above concern has been addressed in PR https://github.com/Qiskit/qiskit-ibm-runtime/pull/348

> Finally, none of this is compatible with the Aer simulator (nor BasicAer) that is needed for using simulators and/or testing in CI environments.

@tmittal947 We need to discuss and prioritize this.

> It would be nice if there was a better way to incorporate Runtime in these situations and a guide for how to migrate existing code over into the Runtime format.

@tmittal947 We need to discuss and prioritize this.
