### ISSUE TITLE
Runtime incompatible with backends other than IBM Quantum 

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#328]
Before Primitives and the Runtime one could just call `backend.run()`  and have things work regardless of whether that backend was real, a sim, local or remote IBM Quantum or otherwise.  However, with the Primitives (and runtime service in general) this is no longer the case.  This makes for lots of branching in code for doing things based on runtime or local / not IBM Quantum backends, and is necessarily required for things like using the local Aer simulator in CI.  Thus the introduction of Runtime makes for a more fractured ecosystem than previously existed.  It would be nice if the uniformity of the old `backend.run() style could be preserved with the introduction of Runtime.  If anything, at bare minimum, Qiskit's own components, e.g. Aer, BasicAer, etc., should be compatible with Runtime.  Without this it makes Runtime integration tricky and not really worth the effort at present.

**Comment by ajavadia** [comment]
Yes this is on the roadmap. This is why the base primitives were places in Qiskit. The idea is that estimation or sampling are well-defined tasks that any backend can implement. So all providers should implement the primitives. The IBM implementations rely on runtime, however one can mock them in software for any provider even if they do not have a runtime.

**Comment by jyu00** [comment]
Closing, since we now have the base primitives in terra as well as `BackendEstimator` and `BackendSampler` that would work with backends that don't have their own primitives.
