### ISSUE TITLE
Primitives do not allow for async usage

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#334]
### What should we add?

The primitives return a result object immediately when called that blocks further execution.  This means that one can no longer execute multiple jobs at a time when using the primitives.  This is useful for jobs where the number of circuits is larger than the HW limit and I want to get them all in queue at the same time, or I want to vary shots (which is not allowed in a single job), etc.  Of course one can drop down into the IBM Runtime and get async access, but this is not available on all backends, not something that is likely to be supported across the board, e.g. Aer or any 3rd-party backends.  Thus moving to primitives as the sole way to access hardware is removing functionality that is currently available.

**Comment by nonhermitian** [comment]
The above probably does work but it breaks the nice uniformity that we already have.  Namely currently a backend can be sync or async and I do not need to change code.  Ideally I would not like to have a bunch of extra code that depends on the situation.  It is very little work to make a result object that allows for async functionality until accessing the data, and the users code need not know the difference.

**Comment by ikkoham** [comment]
We can't get the job id or check the status in my above code. Then,  I think that it might be more convenient in some cases to have a way to return jobs.

**Comment by ikkoham** [comment]
Requirements:
- Asynchronous jobs need to be closed when exiting context.

**Comment by ValentinS4t1qbit** [comment]
I would love to see support for asynchronous job submission (e.g something that submits the job, and returns a job ID that allows users to make various queries about status or retrieving results later on). I hope the Qiskit community finds time to move that feature forward.

Any quantum chemistry experiment that we run usually requires a number of circuits to be run (we've been running stuff with 20-30 circuits recently), sometimes significantly different (measurement basis, number of shots, circuit structure...): submitting everything asynchronously, or even in batch, and getting job IDs back would be very desirable to us.

**Comment by nonhermitian** [comment]
Closed as complete.
