### ISSUE TITLE
Remove deprecated IBMEstimator class

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibm-runtime#358]
**What is the expected feature or enhancement?**
The IBMEstimator class was deprecated in favor of the Estimator class. It can be now be removed.

Note: IBMSampler was removed in this PR https://github.com/Qiskit/qiskit-ibm-runtime/pull/342 and can be used as an example.

**Comment by bopardikarsoham** [comment]
Hello @rathishcholarajan . Can you please assign me to these issues #359 and #364 as well for the future. I know that these issues are currently on hold due to the Qiskit version policy but I surely would love to solve these issues as well.

**Comment by rathishcholarajan** [comment]
@bopardikarsoham I am not able to assign external collaborators. Thank you very much. You could create the PRs and we'll leave it on hold until 0.6.0.

**Comment by rathishcholarajan** [comment]
Fixed by https://github.com/Qiskit/qiskit-ibm-runtime/pull/363
