### ISSUE TITLE
Remove BasePrimitive class

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibm-runtime#364]
**What is the expected feature or enhancement?**
Remove [BasePrimitive class](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/base_primitive.py) since the deprecated `IBMEstimator` and `IBMSampler` classes have been removed in PRs https://github.com/Qiskit/qiskit-ibm-runtime/pull/363 and https://github.com/Qiskit/qiskit-ibm-runtime/pull/342.

**Comment by rathishcholarajan** [comment]
@bopardikarsoham Do you want to pick this up? You can open up a new PR for this one.

**Comment by rathishcholarajan** [comment]
@bopardikarsoham I fixed this since I wanted to do a release today. Thanks a lot for your other contributions btw!

**Comment by bopardikarsoham** [comment]
Oh no problem, I understand. Thank you @rathishcholarajan !
