### ISSUE TITLE
Confusing docs on circuit_indices and observable_indices

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#398]
**Describe the bug**

`circuit_indices` and `observable_indices` were deprecated by #331, but if one is to look up the input parameters for estimator [on IQX](https://quantum-computing.ibm.com/services?services=runtime&program=estimator) or do a `print(service.program("estimator"))`, these two are still displayed as required inputs:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/28284230/176063913-e13f4f0e-3a66-4d5a-ae69-9cc7b0d239bf.png">

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.5.0
- **Python version**:
- **Operating system**:

**Comment by jyu00** [comment]
Personally I find it very confusing to see `circuit_indices` and `observable_indices` documented as required parameters but deprecated when actually used in a session. I don't think you can expect every user to read all the release notes especially if they just started using Qiskit Runtime (i.e. not upgrading).  If `Estimator` is the expected way to call the primitive, then perhaps the IQX documentation (and `print(service.program("estimator"))`) should be updated to reflect that.

**Comment by rathishcholarajan** [comment]
Will discuss this with @tmittal947

**Comment by jyu00** [comment]
Something like that. The `print` today is very disconnected from runtime session usage, and if session is the "encouraged" path, then the `print` should either 1) tell me it's not for session and link me to session doc (less preferred as it's another link to click) or 2) show me how to use it in session.

**Comment by renier** [comment]
ideas discussed:
- Convert metadata json to a python doc string with an example that can be extracted and all consumers (web docs, iqx ,etc) pulling from the same parseable doc string, which will make updates like this easier. Part of the issue is that we have multiple sources for the primitive api docs.
- add deprecation warnings when these params are used
