### ISSUE TITLE
Wrong description in Docs of how-to-getting-started-with-sampler.

### ISSUE THREAD

**Issue by kifumi** [Qiskit/qiskit-ibm-runtime#400]
**Describe the bug**
In the [document of how-to-getting-started-with-sampler](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/tutorials/how-to-getting-started-with-sampler.ipynb), at the bottom section "Multiple parameterized circuits example", 

1) the sentence below

> In our example, the parameter labeled **theta** is sent to the first circuit, theta2 is sent to the first circuit, and theta3 is sent to the second circuit.

should be

> In our example, the parameter labeled **theta1** is sent to the first circuit, theta2 is sent to the first circuit, and theta3 is sent to the second circuit.

2) The last sentence:

> The results align with the parameter - circuit pairs specified previously. For example, the first result ({'11': 0.42578125, '00': 0.14453125, '10': 0.0888671875, '01': 0.3408203125}) is the output of the parameter labeled **theta** being sent to the first circuit.

should also be

> The results align with the parameter - circuit pairs specified previously. For example, the first result ({'11': 0.42578125, '00': 0.14453125, '10': 0.0888671875, '01': 0.3408203125}) is the output of the parameter labeled **theta1** being sent to the first circuit.

I think they are very small typos, but people who read this for the first time would be confused..

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by HuangJunye** [comment]
Thanks for reporting the bug, Kifumi! Do you want to create a PR to fix that?

**Comment by kifumi** [comment]
Yes, I will.  Thank you, Junye.
