### ISSUE TITLE
Import failed with Qiskit Terra 0.20

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#428]
**Describe the bug**

Importing `QiskitRuntimeService` fails with 

```
~/.pyenv/versions/3.9.1/envs/sandbox-3.9/lib/python3.9/site-packages/qiskit_ibm_runtime/qpy/type_keys.py in <module>
     46     RelativeBarrier,
     47 )
---> 48 from qiskit.pulse.library import Waveform, SymbolicPulse
     49 from qiskit.pulse.schedule import ScheduleBlock
     50 from qiskit.pulse.transforms.alignments import (

ImportError: cannot import name 'SymbolicPulse' from 'qiskit.pulse.library' (/Users/jessieyu/.pyenv/versions/3.9.1/envs/sandbox-3.9/lib/python3.9/site-packages/qiskit/pulse/library/__init__.py)
```

if using qiskit-terra 0.20 since `SymbolicPulse` was introduced in 0.21. 

`setup.py` [says](https://github.com/Qiskit/qiskit-ibm-runtime/blob/0.6.1/setup.py#L22) qiskit-terra>=0.20.0 is fine.

**Steps to reproduce**

Import `QiskitRuntimeService` using qiskit-terra 0.20.

**Expected behavior**

Import should not fail. 

**Suggested solutions**

Update docs to say terra 0.21 is required or accommodate 0.20. 

**Additional Information**

- **qiskit-ibm-runtime version**: 0.6.1
- **Python version**: 3.8
- **Operating system**:

**Comment by rathishcholarajan** [comment]
Fix released in 0.6.2
