### ISSUE TITLE
A little typo in Creating Custom Programs for Qiskit Runtime

### ISSUE THREAD

**Issue by neont21** [Qiskit/qiskit-ibm-runtime#433]
**Describe the bug**
In Main program section of [Creating Custom Programs for Qiskit Runtime](https://github.com/Qiskit/qiskit-ibm-runtime/blob/stable/0.6/docs/tutorials/sample_vqe_program/qiskit_runtime_vqe_program.ipynb),

> We are now in a position to start building our main program. However, before doing so we point out that it makes the code cleaner to make a separate **fuction** that takes strings of Pauli operators that define our Hamiltonian and convert them to a list of circuits with single-qubit gates that change the measurement basis for each qubit, if needed. This function is given in [Appendix B](https://github.com/Qiskit/qiskit-ibm-runtime/blob/8d9ae319d732b4c2696709b709138a25f105c170/docs/tutorials/sample_vqe_program/#Appendix-B).

should be

> We are now in a position to start building our main program. However, before doing so we point out that it makes the code cleaner to make a separate **function** that takes strings of Pauli operators that define our Hamiltonian and convert them to a list of circuits with single-qubit gates that change the measurement basis for each qubit, if needed. This function is given in [Appendix B](https://github.com/Qiskit/qiskit-ibm-runtime/blob/8d9ae319d732b4c2696709b709138a25f105c170/docs/tutorials/sample_vqe_program/#Appendix-B).

It's a small typo that can be overlooked, but I think it would be good to fix it.

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by kt474** [comment]
Closed by #434
