### ISSUE TITLE
VQE runtime callback misses some or all iterations

### ISSUE THREAD

**Issue by schwaeti** [Qiskit/qiskit-ibm-runtime#445]
**Describe the bug**

When submitting multiple jobs and storing intermediate information using a callback, some or all iterations of the callback are missing for some jobs. 

**Steps to reproduce**
```ruby
import qiskit
from qiskit.opflow import Z
from qiskit.circuit.library import EfficientSU2
import qiskit_ibm_runtime
from qiskit_ibm_runtime import QiskitRuntimeService
from qiskit.algorithms.optimizers import SPSA

def vqe_one():
    
    def raw_callback(*args):
    # check if interim results, since both interim results (list) and final results (dict) are returned
        if type(args[1]) is list:
            job_id, (nfev, parameters, energy, stddev) = args
            intermediate_info["nfev"].append(nfev)
            intermediate_info["parameters"].append(parameters)
            intermediate_info["energy"].append(energy)
            intermediate_info["stddev"].append(stddev)
            
    intermediate_info = {"nfev": [], "parameters": [], "energy": [], "stddev": []}
    
    #simple operator as example, 12 qubits for sufficient job runtime for bug to occur
    n_qubits = 12
    operator = Z^n_qubits
    ansatz = EfficientSU2(n_qubits)
    
    options = {
        'backend_name': 'ibmq_qasm_simulator'
    }

    runtime_inputs = {
        'ansatz': ansatz, # object (required)
        'initial_parameters': 'random', # [array,string] (required)
        'operator': operator, # object (required)
        'optimizer': SPSA(), # object (required)
    }

    service = QiskitRuntimeService(
        channel='your_channel' #modify
    )
    
    job = service.run(
        program_id='vqe',
        options=options,
        inputs=runtime_inputs,
        instance='your_instance', #modify
        callback=raw_callback
    )

    return job, intermediate_info     

jobs = []
for i in range(10):
    job, intermediate_info = vqe_one()
    jobs.append({'job': job, 'intermediate_info': intermediate_info})

results = []
for job in jobs:
    result = job['job'].result()
    intermediate_info = job['intermediate_info']
    results.append({'result': result, 'intermediate_info': intermediate_info})

for result in results: 
    print(result['intermediate_info']['nfev'])
```

**Expected behavior**
Full intermediate info for every job

**Additional Information**
In this case some results are for example:
[115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 140, 139, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 164, 163, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251]
[]
[239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251]

- **qiskit-ibm-runtime version**: 0.6.2
- **Python version**: 3.9.12
- **Operating system**: Windows 10 Pro

**Comment by kt474** [comment]
This should be resolved now on the latest version of qiskit
