### ISSUE TITLE
Session does not have attribute sampler

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#469]
**Describe the bug**
I am trying to follow the example here: https://github.com/Qiskit/qiskit-ibm-runtime/blob/d5549feaf46d9b11afb48ab945b9acbcd61fa545/qiskit_ibm_runtime/session.py#L47

But get the error:

Traceback (most recent call last):
  Input In [16] in <cell line: 3>
    sampler = session.sampler()
AttributeError: 'Session' object has no attribute 'sampler'

**Steps to reproduce**

**Expected behavior**
The inline doc example should be valid

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: main
- **Python version**:
- **Operating system**:

**Comment by jyu00** [comment]
@kt474 FYI I'm fixing all the docstrings in #468
