### ISSUE TITLE
Backend option should be at session level, not job level

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#474]
**Describe the bug**

The new `Options` class added `backend` as an option that one can specify when initializing a primitive class or running a primitive job. This implies that one can switch to using a different backend in the middle of a session, which is not currently supported by the scheduler. 

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

Make `backend` a session parameter and not part of `Options`. 

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by nonhermitian** [comment]
Yes, and then this can be extended to a list, if needed in the future.

**Comment by kt474** [comment]
How exactly do we want this done? Completely remove `backend` from `Options` and add it to `Session` instead? 

Example:
```
with Session(backend="ibmq_qasm_simulator") as session:
    sampler = Sampler(session=session)
```

cc @renier

**Comment by jyu00** [comment]
Since `session` is an optional parameter to `Sampler` and `Estimator`, we'll need to add `backend` to them as well, so we know which backend to use if `session` is not specified. I'd like to avoid having the additional `service` parameter as well if possible. So perhaps `Sampler` and `Estimator` constructors can now take

- `session` (optional)
- `backend`, also optional, and can be either an `IBMBackend` instance or str. 
    - if a default session exists and the backend name matches, use that default session
    - otherwise close the default session and open a new one with the new backend
- if both `session` and `backend` are specified
   - error if they point to different backend
   - otherwise use the `session`

Also `RuntimeOptions` was deprecated because `backend` was moved to the job level. Since that's no longer true, we can potentially un-deprecate it. At the very least the deprecation message needs to be changed as `Options` is no longer a suitable alternative (since it won't have `backend`).
