### ISSUE TITLE
Setting session max_time does not work

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#475]
**Describe the bug**
I have tried to set the max time of a session using:

```python

session =  Session(service=service, max_time=int(2.5*60*60))
```

<img width="762" alt="Screen Shot 2022-08-17 at 12 11 25" src="https://user-images.githubusercontent.com/1249193/185189699-6fa9a02b-a7b5-4c59-a7d0-63c53aa5b71f.png">

however it looks like the session duration is unchanged from the default ~10 minutes.

**Steps to reproduce**
Try the above.

**Expected behavior**
The real power of a session is its ability to lock a system for some duration (usually a fairly big chunk of time).  I should be able to set that

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: main
- **Python version**:
- **Operating system**:

**Comment by renier** [comment]
able to reproduce this. will fix.

**Comment by renier** [comment]
Found a fix. will be rolled out next week. This was on the server side.

**Comment by kt474** [comment]
fixed on server side, closing
