### ISSUE TITLE
Replace **kwargs with proxies and verify in IBMRuntimeService constructor

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#48]
**What is the expected feature or enhancement?**

`IBMRuntimeService` constructor has a `**kwargs` which is documented as 

```
            **kwargs: Additional settings for the connection:
                * proxies (dict): proxy configuration.
                * verify (bool): verify the server's TLS certificate.
```

If `proxies` and `verify` are the only ones allowed, why not spell them out?

**Comment by rathishcholarajan** [comment]
document proxies
