### ISSUE TITLE
Confusing minimum session max_time value

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#487]
**Describe the bug**

There is no documentation on what the minimum session max time is (or `max_execution_time` on `service.run()`). When I tried to set it to 60, I got this error:

```
IBMRuntimeError: 'Failed to run program: \'400 Client Error: Bad Request for url: https://runtime-us-east.quantum-computing.ibm.com/jobs. {"errors":[{"code":"bad_request","message":"Key: \\\'ProgramRunParams.Cost\\\' Error:Field validation for \\\'Cost\\\' failed on the \\\'min\\\' tag","more_info":"https://cloud.ibm.com/apidocs/quantum-computing#error-handling"}],"trace":"cbvbd6v6q7nnhok4r4g0"}\''
```

This error message implies this is the `Cost` parameter, and the link from the error message says 

```
cost int32
Cost of the program as the estimated time it should take to complete (in seconds)

Possible values: value ≥ 60
```

So 60 should have worked. I tried setting it to 70 in case it's an edge case but got the same error. 

Same thing failed when setting `max_execution_time=60` in `serviec.run()`.

**Steps to reproduce**

```
job = service.run(
    program_id="sampler",
    inputs={"circuits": ReferenceCircuits.bell()},
    options={"backend": "ibmq_dublin"}, 
    max_execution_time=70
)
```

**Expected behavior**

60 should have worked. If that's not the actual minimum, the docs should be updated. 

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.7.0
- **Python version**:
- **Operating system**:

**Comment by renier** [comment]
The actual minimum is 300. The docs need to be updated.

**Comment by kt474** [comment]
@beckykd can you update the cloud api docs

**Comment by beckykd** [comment]
https://test.cloud.ibm.com/apidocs/quantum-computing and https://cloud.ibm.com/apidocs/quantum-computing have been updated and the changes will be live after the builds complete.  This can take anywhere from 20 min - an hour.
