### ISSUE TITLE
IBMBackend.name has different API from IBMQBackend.name

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-ibm-runtime#490]
**Describe the bug**
IBMBackend.name is a string whereas IBMQBackend.name is a function. They should be consistent for user-friendliness.

**Steps to reproduce**
```python
from qiskit import IBMQ
from qiskit_ibm_runtime import QiskitRuntimeService

backend_name = "ibmq_guadalupe"

IBMQ.load_account()
provider = IBMQ.get_provider(hub='ibm-q-internal', group='deployed', project='default')
backend = provider.get_backend(backend_name)
print(type(backend))
print(backend.name())

service = QiskitRuntimeService()
backend = service.backend(backend_name)
print(type(backend))
print(backend.name())
```
```
<class 'qiskit.providers.ibmq.ibmqbackend.IBMQBackend'>
ibmq_guadalupe
<class 'qiskit_ibm_runtime.ibm_backend.IBMBackend'>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [1], in <cell line: 15>()
     13 backend = service.backend(backend_name)
     14 print(type(backend))
---> 15 print(backend.name())

TypeError: 'str' object is not callable
```

**Expected behavior**
The APIs should be consistent as much as possible.

**Suggested solutions**
Make the APIs consistent.

**Additional Information**

- **qiskit-ibm-runtime version**: 29acd55eb443f770dce0837f343ace00ffa0586e
- **Python version**: 3.9.13
- **Operating system**: Arch Linux

**Comment by HuangJunye** [comment]
I think the change is coming from the backend interface version difference. qiskit-IBM-runtime uses BackendV2 while qiskit-ibmq-provider still uses BackendV1. You can see this migration guide for more details about the API changes in BackendV2 and how to migrate from BackendV1: https://qiskit.org/documentation/apidoc/providers.html#migrating-between-backend-api-versions

**Comment by nonhermitian** [comment]
I have also reported this.  I would say this is a different issue (unless the migration guide is incomplete).  Namely the move from `name()` to `name` means that one now has to type check everything to see if an user is passing an `IBMBackend` or an `IBMQBackend`.  This makes compatibility between Runtime and regular backend more of a headache then it should be.

**Comment by kt474** [comment]
Closing for now, following qiskit-terra interface

**Comment by kevinsung** [comment]
@kt474 could you clarify why you closed this issue? I don't understand the meaning of your last comment.

**Comment by kt474** [comment]
`qiskit-ibm-runtime` uses the new backendv2 where backend.name is a string - the old `qiskit-ibmq-provider` still uses backendv1. The old provider will soon be deprecated for the new `qiskit-ibm-provider` which uses backendv2
