### ISSUE TITLE
Readout error mitigation in sampler is ~50x slower than local

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#491]
**Describe the bug**
The M3 mitigation used in the `sampler` returns the timing information in the metadata.  When comparing the runtime of M3 returned by the `sampler` to executing the same locally, one finds that the runtime version is 50x slower than doing the same calculation locally on a not very new machine (Intel i3-10100, Ubuntu 20.04).  In particular, the following circuit is known to run (and verified)  in ~10ms on the same local machine:

```python

N = 12
qc = QuantumCircuit(N)

qc.x(range(N))
qc.h(range(N))

for kk in range(N // 2, 0, -1):
    qc.ch(kk, kk - 1)
for kk in range(N // 2, N - 1):
    qc.ch(kk, kk + 1)
qc.measure_all()
```

But if I run this circuit in the `sampler` multiple times then there is a wide range of values, with mean of ~0.5 sec.  Performing this experiment many times **I have seen swings up to 10 sec in some cases** for multiple circuits running inside of the same `sampler` job.  This makes mitigation quite costly in Runtime for reasons that are unclear, save for perhaps overhead from virtualization.

**Steps to reproduce**
Runt the circuit above with `"resilience_settings":{"level": 1}` and look at the timing info

**Expected behavior**
Performing mitigation in Runtime should not be markedly more expensive then doing so locally.

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: latest
- **Python version**:
- **Operating system**:

**Comment by kt474** [comment]
Closing for now, did some brief testing and this no longer appears to be an issue. Feel free to reopen
