### ISSUE TITLE
Mixer and initial states for runtime QAOA program

### ISSUE THREAD

**Issue by nkongsuwan** [Qiskit/qiskit-ibm-runtime#502]
Currently the qiskit runtime program for QAOA does not support the mixer and initial states, which limits its functionalities to the algorithm's basic capabilities. Adding such features would be very beneficial.

**Comment by kt474** [comment]
@eggerdj

**Comment by jyu00** [comment]
Closing since QAOA runtime program doesn't exist anymore.
