### ISSUE TITLE
Difficulty dealing with transpiler passes in the runtime

### ISSUE THREAD

**Issue by wshanks** [Qiskit/qiskit-ibm-runtime#520]
I want to surface an issue that came up in Slack [here](https://qiskit.slack.com/archives/C8GLMQ1U5/p1661795998740049). From what I can tell, it seems like when dynamical decoupling is used circuits have a quality that triggers the `ConstraintedReschedule` transpiler pass. This pass requires that the circuit is scheduled. `scheduling_method` is not an allowed transpiler setting for passing to the runtime, so the scheduling pass is not run in the runtime. Even if you run a scheduling pass locally before submitting the circuit, in the runtime the transpiler will not treat the circuit as scheduled. This leads to the `ConstrainedReschedule` pass complaining about the circuit not being scheduled.

Maybe the solution is just to transpile locally and use `skip_transpilation`. Or maybe it should be possible to trigger a scheduling pass in the runtime transpilation. Or maybe I have misdiagnosed the issue :slightly_smiling_face:

**Comment by jyu00** [comment]
This was actually done on purpose. We wanted to keep the primitives as high level managed services, and lower level controls such as scheduling methods and error mitigations (including DD) are done for you. 

Having said that, there are certainly users who want lower level control, and the new qiskit-ibm-provider repo will give you just that. It is targeted to be released in October, so in the mean time transpiling locally is the best option.

cc @tmittal947

**Comment by wshanks** [comment]
I just want to make sure one thing is clear -- the difficulty I want to highlight is not that it is hard to pass transpiler options in to the runtime. It is that there is a class of circuits that trigger transpiler passes that throw an error during transpilation. So unless you use `skip_transpilation=True`, you can't use the runtime for these circuits. The specific case that I ran into was that the `ConstrainedReschedule` pass requires a scheduled circuit (as produced by running the scheduling pass) and the options allowed to pass to the runtime transpile step do not allow the scheduling pass to trigger. I haven't looked into what conditions cause the `ConstrainedReschedule` pass to be run.

It might be that this should be thought of as a terra bug because perhaps the `ConstrainedReschedule` pass should never be triggered without the scheduling pass also having been triggered first. Maybe @nkanazawa1989 would know more about how these passes are triggered.

**Comment by drew-distefano** [comment]
Closing considering the amount of time passed and that more granular control is offered in `qiskit-ibm-provider`
