### ISSUE TITLE
Tutorial errors out - device not found

### ISSUE THREAD

**Issue by anna-naden** [Qiskit/qiskit-ibm-runtime#527]
**Describe the bug**
When I attempt to run the tutorial suplied at [https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/how-to-getting-started-with-sampler.html](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/how-to-getting-started-with-sampler.html)

I get an error 400 - bad request, with the additional information "device not found."
**Steps to reproduce**
Access the sample code at the URL given above. Pasted it into VSCode and press run

**Expected behavior**

You should get the rsults of the computation
**Suggested solutions**
Document the correct way to run "sampler"

**Additional Information**

- **qiskit-ibm-runtime version**: 0.6.2
- **Python version**: 3.9
- **Operating system**: Windows 11
[error-message.txt](https://github.com/Qiskit/qiskit-ibm-runtime/files/9550999/error-message.txt)

**Comment by kt474** [comment]
@anna-naden which part of the tutorial is giving you that error? The error message says the device not found is `ibmq_belem` but the tutorial only uses `ibmq_qasm_simulator`

```
{"errors":[{"code":"bad_request","message":"device was not found: ibmq_belem","more_info":"https://cloud.ibm.com/apidocs/quantum-computing#error-handling"}
```
