### ISSUE TITLE
Verison of 'main' branch same as already released RC candidate

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#536]
**Describe the bug**
The main branch is at `0.7.0rc1`, but this version was released over a month ago, and there are breaking differences between the codes

**Comment by jyu00** [comment]
@nonhermitian Did you actually encounter any breaking changes? Other than `quasi_dist` in sampler result is now a list of `QuasiDist` instead of dictionary. I just want to make sure I didn't forget anything.
