### ISSUE TITLE
Allow user to set a default HGP

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#542]
**What is the expected feature or enhancement?**

I am currently getting de-prioritized in the fair-share queue because the default HGP selected by the Runtime service has used too much of its allocation. I do not see a way to force the Runtime to select one HGP over another, and thus am stuck (unless there is a way that I missed) waiting in line.

**Acceptance criteria**
An user can select the HGP (provider) that the Runtime defaults to, if available.

**Comment by jyu00** [comment]
You can actually do this already in a number of ways:

1. Save the hgp you want in an account and load it, e.g. 
```
QiskitRuntimeService.save_account(instance="h1/g1/p1", name="foo", ...)
service = QiskitRuntimeService(name="foo")  <--- this will use h1/g1/p1
```
2. Initialize it in `QiskitRuntimeService`:
```
service = QiskitRuntimeService(instance="h1/g1/p1", ...)
```
3. Specify it at run:
```
service = QiskitRuntimeService()
job = service.run(instance="h1/g1/p1", ...)
```

What we don't have is specifying it as a primitive option, but that's coming soon!

**Comment by nonhermitian** [comment]
Ahh ok I see it now (https://github.com/Qiskit/qiskit-ibm-runtime/blob/cde093882d6656749c09b7f266e242d4a608b59e/qiskit_ibm_runtime/qiskit_runtime_service.py#L160).  Calling it an `instance` threw me off. 

Many thanks.  Helps a lot!
