### ISSUE TITLE
Docs on how to set 'readout_mitigation_num_twirled_circuits' and 'readout_mitigation_shots_calibration'

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#544]
**What is the expected feature or enhancement?**

It is unclear how to set `readout_mitigation_num_twirled_circuits` and `readout_mitigation_shots_calibration` in the options because they go with the `resilience_level` which does not have its own options class

**Acceptance criteria**
And user can easily set the options for resilience settings

**Comment by jyu00** [comment]
We don't have those in `Options` because we haven't settled on what to name them yet (or whether they are the "right" options). But it'll happen before the next official release :)

**Comment by jyu00** [comment]
We don't plan on exposing these options at this time. Will update documentation if/when we do.
