### ISSUE TITLE
Use qiskit-ibm-provider

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#548]
**What is the expected feature or enhancement?**

Now that `qiskit-ibm-provider` is released, we can include that as a dependency and reuse a lot of the same code, especially for API calls.

**Acceptance criteria**

Reuse same code in qiskit-ibm-provider.

**Comment by jyu00** [comment]
@kt474 Why is this on hold?

**Comment by kt474** [comment]
I thought it would be best to get https://github.com/Qiskit/qiskit-ibm-provider/issues/394 done first since there are still iqx api calls, but it's not a hard blocker. Removed the on hold label

**Comment by kt474** [comment]
fixed by #871
