### ISSUE TITLE
Session performance is very poor relative to other methods

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#574]
**What is the expected feature or enhancement?**

I decided to test the performance of Runtime Sessions verses other methods for the very simple task of executing 10 jobs with one circuit each on a simulator.  I looked at the performance of the local Aer simulator, calls to the `ibmq_qasm_simulator` via `backend.run()`, the legacy "upload-your-own" runtime programs, and Sessions.  Sessions was found to be the slowest with the timings begin:

Local Aer : 0.6 sec
`ibmq_qasm_simulator`: 135 sec
"upload_your_own" : 0.5 sec
Sessions: 278 sec

Thus we see that Sessions is ~550x slower than "upload your own program" style runtime for simple tasks.

My program was

```python

# Grab functions and modules from dependencies
import time

# Grab functions and modules from Qiskit needed
from qiskit import transpile

# The entrypoint for our Runtime Program
def main(
    backend,
    user_messenger,
    circuit,
    iterations=10,
    shots=int(1e4)
):  
    start = time.perf_counter()
    trans_qc = transpile(circuit, backend, optimization_level=3, approximation_degree=1)
    
    for it in range(iterations):
        cnts = backend.run(trans_qc, shots=shots).result().get_counts()
        
    stop = time.perf_counter()
    
    return stop-start
```

with the circuit given by

```python

# Build circuit here
N = 12
qc = QuantumCircuit(N)

qc.x(range(N))
qc.h(range(N))

for kk in range(N // 2, 0, -1):
    qc.ch(kk, kk - 1)
for kk in range(N // 2, N - 1):
    qc.ch(kk, kk + 1)
qc.measure_all()
```

The equivalent Session call was:

```python

backend = service.get_backend('ibmq_qasm_simulator')
start = time.perf_counter()
session = Session(service=service, backend = backend)
sampler = Sampler(session=session)
trans_qc = transpile(qc, backend, optimization_level=3, approximation_degree=1)
for kk in range(10):
    cnts = sampler.run(circuits=trans_qc, skip_transpilation=True).result()
stop = time.perf_counter()
print(stop-start)
```

For the Session calls I always hit #538 so perhaps that is adding to the total time, but since this always gets raised the timings are what I see.

**Acceptance criteria**
Sessions should not be over two orders of magnitude slower than "upload-your-own" and especially not slower than the `backend.run()` path for the `ibmq_qasm)_simulator`

**Comment by jyu00** [comment]
This now takes about 10.4s to run from my laptop. 2s of that was just transpilation (I guess my laptop is quite slow lol).
