### ISSUE TITLE
It takes many seconds to submit small jobs via the Estimator

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#587]
**Describe the bug**

It takes a very long time to submit (not run) a small example problem to the Estimator.  In particular sending a small 2Q circuit and Hamiltonian:

![image](https://user-images.githubusercontent.com/1249193/197789264-4ad8e997-0e57-4be4-89a3-77c91126059e.png)

and

```python

SparsePauliOp(['II', 'ZI', 'XI', 'IZ', 'IX', 'ZZ', 'XZ', 'ZX', 'XX'],
              coeffs=[-9.75760110e+01+0.j,  5.06368857e-01+0.j,  2.73402789e-02+0.j,
  5.06368857e-01+0.j,  2.73402789e-02+0.j,  1.79911453e-02+0.j,
  2.73402800e-02+0.j,  2.73402800e-02+0.j,  2.01226999e-01+0.j])
```

takes 15+ seconds to send using:

```python
session = Session(backend=backend)
estimator = Estimator(session=session, options=options)
job = estimator.run(circuits=circuit_list, observables=operator_list, shots=shots)
```

this can be seen by profiling the submission process that gives.

```
         453926 function calls (453634 primitive calls) in 17.142 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      275   15.566    0.057   15.566    0.057 {method 'read' of '_ssl._SSLSocket' objects}
```
at the top of the profile.

**Steps to reproduce**
Try submitting a small problem.

**Expected behavior**
It should not take 17+ seconds to send a small problem

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.7rc2
- **Python version**: Py3.9
- **Operating system**: Ubuntu 22.04

**Comment by daka1510** [comment]
@nonhermitian can you share a self-contained code sample I can use to reproduce the long submission time you're seeing? 

Not sure what you set as `circuit_list`, `operator_list`, `options` and `shots`. Not all specifics may have an effect on the submission process but I'd like to make sure I'm really tracing the right problem.

**Comment by nonhermitian** [comment]
I do not see this anymore, son closing.
