### ISSUE TITLE
Session sampler not terminated and the program is still running for several days

### ISSUE THREAD

**Issue by hosen20** [Qiskit/qiskit-ibm-runtime#609]
**Describe the bug**
The sampler session fails to terminate although the program is still running for 7 days

**Steps to reproduce**
job id: cdh67ual7ccccqmcp4a0
Note that i have ran some jobs on the backend yesterday and worked well but this one is still stuck from 7 days

**Expected behavior**
As stated in the documentation, a maximum timeout is assigned to the session.
https://quantum-computing.ibm.com/lab/docs/iql/manage/systems/sessions/#how-long-is-a-session-active
When a session is started, it is assigned a maximum session timeout value. This timeout value is the same as the initial job’s maximum execution time and is the smaller of 1) the system limit (8 hours for physical systems) and 2) the max_execution_time defined by the program. After this time limit is reached, the session is permanently closed.

Additionally, there is an interactive timeout value. If there are no session jobs queued within that window, the session is temporarily de-activated and normal fair-share job selection resumes. If the scheduler gets a job from the session again, the session is re-activated until its maximum timeout value is reached.

When using primitives with their context managers as described above, the session is closed automatically when the block is exited.

**Suggested solutions**
I think the problem is in the server side code.

**Additional Information**

- **qiskit-ibm-runtime version**: '0.7.0'
- **Python version**: '3.10.6'
- **Operating system**: Ubuntu 22.04.1 LTS
![SamplerIssue1](https://user-images.githubusercontent.com/84079430/201065286-4eddb930-1d4c-4154-9b7a-c566d87058f9.png)

**Comment by kt474** [comment]
I believe all the recent updates on the server side have resolved this issue
