### ISSUE TITLE
Image link broken in notebook "Get started with error suppression and error mitigation with Qiskit Runtime"

### ISSUE THREAD

**Issue by hosen20** [Qiskit/qiskit-ibm-runtime#610]
**Describe the bug**
One of the cells under the title "dynamical decoupling" is used to plot a graph, but it is not plotted. Instead "../_images/tutorials_Error-Suppression-and-Error-Mitigation_13_0.png" is written. Checked the images folder, no image with this name, so I think this is the reason the image is not showing. 

**Steps to reproduce**
Go to https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/Error-Suppression-and-Error-Mitigation.html
Under title "dynamical decoupling" the second cell should contain an image for the plot, but the image is not shown.

**Expected behavior**
Image should be shown

**Suggested solutions**
Add the image to the folders images

![runtime2](https://user-images.githubusercontent.com/84079430/201083275-7cfc9f47-9d2c-464b-8c70-deea76b28c6a.png)

**Comment by kt474** [comment]
@beckykd can you take a look?

**Comment by beckykd** [comment]
Thanks - I'm investigating this

**Comment by beckykd** [comment]
@kt474 - this chart is supposed to be generated from the code and it's working for me in VSCode.  I'm trying right now in Lab.

**Comment by beckykd** [comment]
I don't know where that ../../ .png message could be coming from, because the notebook never actually calls that file.  Here's that bit of code:  
![notebook code](https://user-images.githubusercontent.com/66339736/201380897-2c7f7a19-a1cc-4176-9165-336473c6bc09.png)

**Comment by beckykd** [comment]
I think I fixed it!  The "Dynamical Decoupling" heading is showing up wrong for some reason.  The code looked OK, but when I deleted it and redid it, the heading worked correctly and the plot showed up in Lab for me.  So I'll get that checked in.
