### ISSUE TITLE
Running this circuit causes runtime to stall

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-ibm-runtime#616]
**Describe the bug**
Eventually the job will time out.

**Steps to reproduce**
```python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit_ibm_runtime import QiskitRuntimeService, Sampler


service = QiskitRuntimeService()
backend = service.backend("ibmq_qasm_simulator")
sampler = Sampler(session=backend)

register = QuantumRegister(2)
clbits = ClassicalRegister(2)

circuit = QuantumCircuit(list(register), list(clbits))
circuit.measure_all()

job = sampler.run(circuit)
result = job.result()
```

**Expected behavior**
Should not stall. Should probably just stop and return the same error that Qiskit Terra would: `'Some classical bits are not used for measurements. the number of classical bits (4), the used classical bits ({2, 3}).'`

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.8.0
- **Python version**: 3.10.8
- **Operating system**: Arch Linux

**Comment by kt474** [comment]
This returns an error immediately for me - does is still stall for you? 

```python
2022-11-17T00:01:37.573259945Z     _read_instruction(
2022-11-17T00:01:37.573278059Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit_ibm_runtime/qpy/binary_io/circuits.py", line 231, in _read_instruction
2022-11-17T00:01:37.573294029Z     cargs.append(clbit_indices[carg.size])
2022-11-17T00:01:37.573311009Z KeyError: 2
```

**Comment by kevinsung** [comment]
Interesting, it is no longer stalling. Thanks.
