### ISSUE TITLE
Expose a method to return the session id from a runtime job

### ISSUE THREAD

**Issue by rachaelhouse** [Qiskit/qiskit-ibm-runtime#639]
**What is the expected feature or enhancement?**
Provide a similar method to the `job_id()` method [here](https://qiskit.org/documentation/stubs/qiskit.providers.ibmq.runtime.RuntimeJob.html) which will return the session id of the job if the job is running as part of a session.
The sessionId is already exposed by the runtime API [here](https://us-east.quantum-computing.cloud.ibm.com/openapi/#/Jobs/get_job_details_jid)

**Acceptance criteria**
A new method is exposed for runtime jobs which returns the sessionId of the job

**Comment by mriedem** [comment]
While doing this it might also be nice to add the `tags` from the API to the `RuntimeJob` instance since you can set those when running a job then they should also be in the `RuntimeJob` instance when retrieving the job.
