### ISSUE TITLE
resilience_levels 2 & 3 turns off mitigation for Sampler

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#641]
Turning on `resilience_level` 2 or 3 in the `Sampler` disables readout mitigation, i.e. `resilience_level=1` functionality.  No other mitigation looks to be applied.  This is counter to the assumption that the higher the resilience level the more mitigation is performed.

I could not find any documentation that explicitly mentions this.

**Comment by nonhermitian** [comment]
Actually I found it here: https://qiskit.org/documentation/partners/qiskit_ibm_runtime/how_to/error-mitigation.html#configure-error-mitigation (my screen just cut off the side of the table). 

Ideally, rather than no mitigation, these higher levels would keep M3 turned on.

**Comment by king-p3nguin** [comment]
When I used the `Sampler` for the first time, I did not know that setting the `resilience_level` higher than one does not perform any error mitigation until I read the document. I would instead prefer raising an error when `resilience_level > 1`, just like when I set `resilience_level = 4` for `Estimator`.
```
--- Logging error ---
Traceback (most recent call last):
File "/provider/programruntime/program_starter_wrapper.py", line 88, in execute
  final_result = self.main(backend, self.messenger, **self.user_params)
File "/code/./program.py", line 1460, in main
  raise QiskitError(f"Resilience level {resilience_level} not supported.")
qiskit.exceptions.QiskitError: 'Resilience level 4 not supported.'
```
