### ISSUE TITLE
ibm_runtime estimator fails in VQE

### ISSUE THREAD

**Issue by jadgt** [Qiskit/qiskit-ibm-runtime#642]
**Describe the bug**
I have been trying the VQE with the new estimators and whereas the estimators from `qiskit.primitives` and `qiskit_aer.primitives` works just fine. Nevertheless, the estimator coming from `qiskit_ibm_runtime` fails.

**Steps to reproduce**
The Ansatz is a UCCSD with a HF initial guess for water, since I got the integrals from my own driver I'm not including all the steps to get the Ansatz 

```
from qiskit_ibm_runtime import QiskitRuntimeService, Session, Estimator, Options
from qiskit.algorithms.minimum_eigensolvers import VQE

service = QiskitRuntimeService()
options = Options()
options.optimization_level = 3
options.resilience_level = 2

with Session(service=service, backend='ibmq_qasm_simulator') as session:
    estimator = Estimator(session=session, options=options)
    runtime_vqe = VQE(estimator=estimator,
        ansatz=ansatz,
        optimizer=SLSQP(),
        initial_point=np.zeros(ansatz.num_parameters),
    )

solver = GroundStateEigensolver(converter,runtime_vqe) 
runtime_res = solver.solve(problem)
```
Error code:
```
RuntimeError                              Traceback (most recent call last)
File ~/opt/miniconda3/envs/vlxq05/lib/python3.10/site-packages/qiskit/algorithms/minimum_eigensolvers/vqe.py:253, in VQE._get_evaluate_energy.<locals>.evaluate_energy(parameters)
    252 try:
--> 253     job = self.estimator.run(batch_size * [ansatz], batch_size * [operator], parameters)
    254     estimator_result = job.result()

File ~/opt/miniconda3/envs/vlxq05/lib/python3.10/site-packages/qiskit_ibm_runtime/estimator.py:249, in Estimator.run(self, circuits, observables, parameter_values, **kwargs)
    248 user_kwargs = {"_user_kwargs": kwargs}
--> 249 return super().run(
    250     circuits=circuits,
    251     observables=observables,
    252     parameter_values=parameter_values,
    253     **user_kwargs,
    254 )

File ~/opt/miniconda3/envs/vlxq05/lib/python3.10/site-packages/qiskit/primitives/base/base_estimator.py:233, in BaseEstimator.run(self, circuits, observables, parameter_values, **run_options)
    231 run_opts.update_options(**run_options)
--> 233 return self._run(
    234     circuits,
    235     observables,
    236     parameter_values,
    237     **run_opts.__dict__,
    238 )
...
--> 256     raise AlgorithmError("The primitive job to evaluate the energy failed!") from exc
    258 values = estimator_result.values
    260 if self.callback is not None:

AlgorithmError: 'The primitive job to evaluate the energy failed!'
```
**Expected behavior**
Compute VQE as with the other two estimators

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.8.0
- **Python version**: 3.10.6
- **Operating system**:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/101552251/205956957-e3dec7e3-630b-4088-aa5d-b21f2b6e3ec4.png">

**Comment by jyu00** [comment]
@jadgt Do you by any chance have a job ID?

**Comment by jadgt** [comment]
No, but I have fixed the issue by indenting the solver below the with

**Comment by jyu00** [comment]
@jadgt Your second example has 

```
IBMQ.load_account()
provider = IBMQ.get_provider(project='main')
backend = provider.get_backend('ibmq_qasm_simulator')
```

Unfortunately you can't mix the old provider (IBMQ) with the new Qiskit Runtime service. Can you try without that and do 

```
with Session(service=service, backend='ibmq_qasm_simulator') as session:
...
```

instead? The code worked for me once I removed the IBMQ part.

**Comment by jyu00** [comment]
This looks like an error with the estimator primitive - that it cannot do error mitigation on a simulator because simulators don't have coupling map (since everything is connected). I'll report this to the primitive service.

**Comment by jadgt** [comment]
Fair enough, I've been testing out and the max `resilience_level` allowed in the `qasm_simulator` is 2
