### ISSUE TITLE
Session.close() should not break job execution within a session

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#645]
**What is the expected feature or enhancement?**

The primitives allow for async job execution.  That is to say that one would think that code of the form:

```python

with Session(backend=backend):
    sampler = Sampler()
    estimator = Estimator()
    sampler_job = sampler.run(qc)
    estimator_job = estimator.run(qc2, oper)
```
would submit two async jobs that execute within the specified `Session`.  However, when the code inside the context is done, `session.close()` is implicitly called which causes the jobs to enter the usual fair-share scheduler rather than executing back-to-back like they would inside a session.  This makes async jobs inside a session context pointless as one always has to block and wait for the session to remain alive.

Thus the only way to do actual async job execution is to keep the session alive using:

```python

session = Session(backend=backend)
sampler = Sampler(session=session)
estimator = Estimator(session=session)
job1 = sampler.run(qc)
job2 = estimator.run(qc2, oper)
```
and calling `session.close()` only after all jobs are done (or more likely not at all, with a 5min idle duration on the device).

Alternatively `session.close()` (or something like that) should not break the job execution within the session, but rather be equivalent to the statement "I am done adding jobs to this session".

**Acceptance criteria**
One can batch jobs async within a session and close the session with jobs still executing within the session

**Comment by drew-distefano** [comment]
Closing as this was addressed by the recent sessions improvements
