### ISSUE TITLE
Default session is used after time out

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#648]
**Describe the bug**

Today if a session is not explicitly passed to the primitive constructor, a default session is created. This default session continues to be used for subsequent jobs. However, this session continues to be used even after it has reached its maximum time, causing jobs to fail (because session cache has expired). 

**Steps to reproduce**

Submit a job using default session, wait >12h and submit another job (all without existing the Python session). For example:

```
backend = service.backend("ibmq_qasm_simulator")
estimator = Estimator(session=backend)
estimator.run().result()
# wait 12h
sampler = Sampler(session=backend)
sampler.run().result()
```

**Expected behavior**

Jobs don't fail when default session is used.

**Suggested solutions**

Add a TTL to the default session and open a new one if that one has expired. 

**Additional Information**

- **qiskit-ibm-runtime version**: 0.1.0
- **Python version**:
- **Operating system**:

**Comment by merav-aharoni** [comment]
@kt474 - I see the problem here, and I have two questions:
1. I can add a `max_time` to the session built in `get_default_session`, but where do I take this `max_time` from? I couldn't find it in the `qiskit-ibm-runtime` repo (except for running a `program`).
2. Shouldn't the same default `max_time` be defined in `Session.__init__`?

**Comment by kt474** [comment]
The `max_time` for session depends on the type of program, user, and device - here are the [docs](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/faqs/max_execution_time.html#qiskit-runtime-on-ibm-quantum)

I believe this is set on the server side so it would not be defined in `Session.__init__` where it can be overridden

**Comment by jyu00** [comment]
Given the default is set by the server, and there is no mechanism to query, perhaps a try/except of session timeout error and open a new one is the easiest solution. It can even be combined with #705.

**Comment by kt474** [comment]
Will close this for now as it is not possible at the moment

**Comment by jyu00** [comment]
I'm not sure why this was deemed impossible. You can do a try/except of session timeout error and open a new one?

**Comment by jyu00** [comment]
Closing again. The scheduler will soon fail all queued jobs for a closed/expired session, so an implicitly managed session will likely cause more surprises, especially since currently there is no way to query session status.
