### ISSUE TITLE
Reporting an issue while using qiskit runtime estimator method on cloud simulator, the local version seems working 

### ISSUE THREAD

**Issue by jayeshparashar** [Qiskit/qiskit-ibm-runtime#649]
**Describe the bug**
RuntimeJobFailureError: while using ZI and IZ sparse operators, The code is working fine with ZZ operator, there seems some code issue that can be looked at (some conflict with register names), reporting this issue only with the estimator method on cloud simulator, the code works fine the local version of simulator..

**Steps to reproduce**
[https://gist.github.com/jayeshparashar/2250e15f554250f27e8f94a19a96b697](url)

**Expected behavior**
Should have returned the EstimatorResult object

**Suggested solutions**
Fix the runtime error

**Additional Information**
Works fine with Local simulator 
- **qiskit-ibm-runtime version**: 
Version: 0.37.1
- **Python version**:
- **Operating system**:

**Comment by merav-aharoni** [comment]
I suspect this is the same as #659, and in #749. I think we can close this issue.

**Comment by kt474** [comment]
closing for now, as this is a duplicate
