### ISSUE TITLE
Search is broken on qiskit-ibm-runtime doc

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-ibm-runtime#658]
**Describe the bug**
Search is broken on qiskit-ibm-runtime doc.

**Steps to reproduce**
Go to https://qiskit.org/documentation/partners/qiskit_ibm_runtime/, type keywords into search box and press Enter.

<img width="587" alt="Screen Shot 2022-12-16 at 12 57 59" src="https://user-images.githubusercontent.com/7631333/208093408-c848ef7b-7fe1-417a-9fea-ac960d78c390.png">

**Expected behavior**
Search results should be shown

**Suggested solutions**
This was a bug in qiskit.sphinx.theme 1.10.0 which has been fixed in 1.10.1. Rebuild the docs (probably just trigger the workflow again is enough since there is no version pinning) using the latest qiskit-sphinx-theme 1.10.1 should fix it.

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by kt474** [comment]
Redeployed the docs, fixed now
