### ISSUE TITLE
Error in computing expectation values of IX, XI type operators 

### ISSUE THREAD

**Issue by viveliitm** [Qiskit/qiskit-ibm-runtime#659]
The use of  Estimator to compute expectation values like IX, XI operators is showing error.
The estimator is working fine for XX, XY, XZ etc. operators' expectation values fine

**Steps to reproduce**
import time
import numpy as np
from qiskit import *
from qiskit.circuit import Parameter
from qiskit.quantum_info import Statevector, Pauli, SparsePauliOp
from qiskit.circuit.library import RealAmplitudes
import matplotlib.pyplot as plt
import matplotlib.ticker as tck
from qiskit.tools.visualization import plot_histogram
from qiskit_ibm_runtime import QiskitRuntimeService, Session, Options, Sampler, Estimator

qc = QuantumCircuit(2, 2)
qc.x(0)
qc.x(1)
qc.h(0)
qc.cx(0,1)
display(qc.draw(output="mpl"))

H11 =SparsePauliOp.from_list([("XX", 1)])
H22 =SparsePauliOp.from_list([("YY", 1)])
H33 =SparsePauliOp.from_list([("ZZ", 1)])
H10 =SparsePauliOp.from_list([("IX", 1)])
H01 =SparsePauliOp.from_list([("XI", 1)])
H20 =SparsePauliOp.from_list([("IY", 1)])
H02 =SparsePauliOp.from_list([("YI", 1)])
H30 =SparsePauliOp.from_list([("IZ", 1)])
H03 =SparsePauliOp.from_list([("ZI", 1)])

service = QiskitRuntimeService(channel='ibm_quantum')
backend = service.backends(simulator=False)[1]
print(backend)

options = Options(simulator={"seed_simulator": 42}, resilience_level=0)

with Session(service=service, backend=backend):
    estimator = Estimator(options=options)
    job = estimator.run(circuits=[qc]*3, observables=[H11,H22,H33])
    param_results = job.result()
    print(param_results)

options = Options(simulator={"seed_simulator": 42}, resilience_level=0)

with Session(service=service, backend=backend):
    estimator = Estimator(options=options)
    job = estimator.run(circuits=[qc]*3, observables=[H10,H20,H30])
    param_results = job.result()
    print(param_results)

**Expected behavior**
expectation values of H10 , H20 should be computed even if they are zero 

**Suggested solutions**
Work on way to get right expectation values 

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by merav-aharoni** [comment]
Hi @viveliitm - I ran your code and indeed saw an error. However, I believe the error is due to the definition ```qc = QuantumCircuit(2, 2)```. 
The `Estimator` does not support classical qubits. The correct line should be ```qc = QuantumCircuit(2)```. When I changed this in my code, I no longer got an error.
Please let me know if this resolves your error message.
I will open a separate issue to return a suitable error message in this case.

**Comment by viveliitm** [comment]
Yes, this is working fine now. Thanks for help

**Comment by merav-aharoni** [comment]
Closing this - issue #749 points at the exact source of the problem.
