### ISSUE TITLE
Primitive tutorials look truncated

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#664]
**Describe the bug**

The old "getting started" tutorials on [sampler](https://github.com/Qiskit/qiskit-ibm-runtime/blob/ab7486d6837652d54cb60b83cfaa9165f5d0484c/docs/tutorials/how-to-getting-started-with-sampler.ipynb) and [estimator](https://github.com/Qiskit/qiskit-ibm-runtime/blob/ab7486d6837652d54cb60b83cfaa9165f5d0484c/docs/tutorials/how-to-getting-started-with-estimator.ipynb) had a lot more information than the existing ones updated by #626. The new tutorials look incomplete - e.g. the one on estimator just suddenly stops after "Create an Estimator instance". 

Perhaps this was an attempt to make the tutorials shorter, but I think the current ones are missing some important information. For example, it omits the fact that you can run different primitives inside a session (which is the reason the `Session` class was created) and that `options` for Qiskit Runtime primitives are done slightly differently that those of terra primitives.

cc @beckykd  

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by kt474** [comment]
fixed by #635
