### ISSUE TITLE
IBMNotAuthorizedError: 'You are not authorized to upload programs.'  when  "import sys" or "import os"

### ISSUE THREAD

**Issue by patdenim** [Qiskit/qiskit-ibm-runtime#673]
**Describe the bug**
Message IBMNotAuthorizedError: 'You are not authorized to upload programs.' when uploading a runtime code containing one of the  statements here below.  Even though commented 
```
import sys   
import os 
# import sys
# import os

```

**Steps to reproduce**
add "import os" or "import sys" to the python code and upload it. You'll get the error 

```
----> 8 program_id = service.upload_program(
      9     data=program_data,
     10     metadata=program_json )
     11 print(provider.runtime.program(program_id))

File ~\.conda\envs\qiskit-0.39.x\lib\site-packages\qiskit_ibm_runtime\qiskit_runtime_service.py:1091, in QiskitRuntimeService.upload_program(self, data, metadata)
   1087         raise RuntimeDuplicateProgramError(
   1088             "Program with the same name already exists."
   1089         ) from None
   1090     if ex.status_code == 403:
-> 1091         raise IBMNotAuthorizedError(
   1092             "You are not authorized to upload programs."
   1093         ) from None
   1094     raise IBMRuntimeError(f"Failed to create program: {ex}") from None
   1095 return response["id"]

IBMNotAuthorizedError: 'You are not authorized to upload programs.'
```

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.8.0 
- **Python version**: 3.10.6
- **Operating system**: WIN11

**Comment by kt474** [comment]
Just to clarify, you can upload programs when "import sys" and "import os" are removed?

**Comment by rathishcholarajan** [comment]
Looks like @patdenim needs the `custom-programs` role to skip validation. @daka1510 How was the transition done for existing users? At least I did not get the `custom-programs` role automatically and had to request it.

**Comment by patdenim** [comment]
@kt474 Yes, when the statement import sys or import os is removed then i can upload a program

**Comment by patdenim** [comment]
@rathishcholarajan As i successfully upload custom programs if i remove any statement "import os" or "import sys"  from the python script, i guess i already have the `custom-programs` role assigned,  haven't i  !!
