### ISSUE TITLE
Remove "credentials" module

### ISSUE THREAD

**Issue by daka1510** [Qiskit/qiskit-ibm-runtime#68]
**What is the expected feature or enhancement?**
The [credentials](https://github.com/Qiskit/qiskit-ibm-runtime/tree/main/qiskit_ibm_runtime/credentials) module is superseded by an [accounts](https://github.com/Qiskit/qiskit-ibm-runtime/tree/main/qiskit_ibm_runtime/accounts) module and a [ClientParameters](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/api/client_parameters.py) class. Let's use this issue to clean this up by removing credentials from our code.

**Acceptance criteria**
Removed directory [qiskit_ibm_runtime/credentials](https://github.com/Qiskit/qiskit-ibm-runtime/tree/main/qiskit_ibm_runtime/credentials) and updated all references. CI build passes.

**Comment by daka1510** [comment]
@jyu00, @rathishcholarajan any concerns?

**Comment by jyu00** [comment]
go for it
