### ISSUE TITLE
Collect usage data

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#685]
**What is the expected feature or enhancement?**

Having usage data would help us understand and improve common use cases. Since Qiskit Runtime is designed for algorithm developers, we'd like to know which algorithms are being used. As a starting point, we can collect 2 data points:

1. The modules used by the users
2. The specific calling class

1 is easily achievable using something like

```
import sys

interesting_keywords = ["qiskit_nature", "qiskit_machine_learning", "qiskit_optimization", "qiskit_finance", "qiskit.algorithms", "qiskit.primitives"]  # add more as you please

found_keywords = [key for key in interesting_keywords if key in sys.modules]
```

2 requires looking into the stack and find the calling submodule (e.g. `qiskit.algorithms.minimum_eigensolvers.vqe`)

We can save this data in the header, similar to Qiskit version. There should also be an option to op out. 

**Acceptance criteria**

**Comment by johannesgreiner** [comment]
I'd think IBM's privacy laws would actually require users to explicitly opt in. Is it anonymous data or can it be related to the user?

**Comment by jyu00** [comment]
> I'd think IBM's privacy laws would actually require users to explicitly opt in. Is it anonymous data or can it be related to the user?

We are only collecting module names, so nothing related to the users. I've already cleared with the security/privacy team.
