### ISSUE TITLE
Document supported backend filters

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-ibm-runtime#689]
**What is the expected feature or enhancement?**
At https://qiskit.org/documentation/partners/qiskit_ibm_provider/stubs/qiskit_ibm_provider.IBMProvider.backends.html it says
>**kwargs –
Simple filters that specify a True/False criteria in the backend configuration, backends status, or provider credentials. An example to get the operational backends with 5 qubits:
IBMProvider.backends(n_qubits=5, operational=True)

This gives an example of a simple filter ("operational") but doesn't actually provide a list of supported options.

**Acceptance criteria**
I don't know what this issue template field is for.

**Comment by kt474** [comment]
The link is documentation for qiskit-ibm-provider but the docstrings of the `backends()` methods from both repos can be improved. 

For **kwargs, as mentioned, any True/False criteria in the backend configuration or attributes ([link](https://qiskit.org/documentation/partners/qiskit_ibm_provider/stubs/qiskit_ibm_provider.IBMBackend.html#qiskit_ibm_provider.IBMBackend)) can be used - there are too many options to list all of them, but we could add a couple more examples 

The filter parameter is similar but not restricted to only a boolean True/False - lambda functions can be used 

To see exactly how the filtering is done, we use the [filter_backends](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/providers/providerutils.py#L20) method in terra. 

We'll add a couple more examples to the docstring to make it more clear

**Comment by merav-aharoni** [comment]
@kt474 - I am a bit confused about the filtering mechanism. Here are my thoughts/observations:

- The filtering as well as the documentation is in several places including `qiskit_ibm_provider/ibm_backend_service.py`, `qiskit_ibm_provider/ibm_provider.py`, and twice in `qiskit_ibm_runtime/qiskit_runtime_service.py`. Wouldn't it make more sense to have the documentation in one place (`ibm_backend_service.py`) and put references in the other places?
- Also I suggest adding a reference to the documentation of `QasmBackendConfiguration` in Terra.
- The example with `quantum_volume` does not work and should be removed.
- My understanding is that in kwargs, it is only possible to pass keys with specific values, so we cannot specify something like `max_circuits >100`. This can only be done through a lambda function. Am I correct?

**Comment by kt474** [comment]
> @kt474 - I am a bit confused about the filtering mechanism. Here are my thoughts/observations:
> 
- Yes I agree - it would be ideal to have documentation in a central location, but I think it would still be good to have it at least once in each repo 
-  Sure, I think that would be helpful 
- Yes that example can be removed 
- Yes that's correct, those filters can only be done through a lambda function
