### ISSUE TITLE
RuntimeJobFailureError when VQE with qiskit runtime

### ISSUE THREAD

**Issue by qalkamo** [Qiskit/qiskit-ibm-runtime#690]
**Describe the bug**
RuntimeJobFailureError occurred when running vqe on qiskit_runtime.
As explained in https://qiskit.org/documentation/nature/tutorials/07_leveraging_qiskit_runtime.html
I ran:
```
runtime_vqe_groundstate_solver = GroundStateEigensolver(qubit_converter, runtime_vqe)
runtime_vqe_result = runtime_vqe_groundstate_solver.solve(problem)
```
but RuntimeJobFailureError occurred.

**Steps to reproduce**
Just rerun the code on the documents https://qiskit.org/documentation/nature/tutorials/07_leveraging_qiskit_runtime.html
My qiskit version is qiskit 0.40

**Expected behavior**
It should output the results of VQE runned by vqe_runtime

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.8.0
- **Python version**: 3.9.13
- **Operating system**:  macOS monterey Version 12.2.1

**Comment by kt474** [comment]
reported this bug to the qiskit nature team https://github.com/Qiskit/qiskit-nature/issues/1058, will close the issue on this side for now
