### ISSUE TITLE
Add how-to on retrieving jobs

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#696]
**What is the expected feature or enhancement?**

At one point there was documentation on how to retrieve a previously submitted job, its results and parameters used. I can't seem to find that anywhere now. 

**Acceptance criteria**

Add a `Retrieve a previous job` section under `How to` that explains how to retrieve a previously submitted job, its results and parameters used.

**Comment by jyu00** [comment]
Apparently there is doc on this already, but it's [buried inside](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/how_to/run_session.html#retrieve-previous-job-results) "Run a session" for some reason.

**Comment by beckykd** [comment]
I spoke to @jyu00 and she said we can just pull out that information into a separate topic.
