### ISSUE TITLE
Create a release plan for the next 2 milestones

### ISSUE THREAD

**Issue by daka1510** [Qiskit/qiskit-ibm-runtime#697]
- [ ] Create milestones (following the release plans from qiskit-terra https://github.com/Qiskit/qiskit-terra/milestones)
- [ ] Assign prioritized issues to include in the coming milestone

**Comment by kt474** [comment]
Created milestone here https://github.com/Qiskit/qiskit-ibm-runtime/milestones - i'll continue to update in the next few days
