### ISSUE TITLE
QAOA Runtime fails when setting mitigation and pulse efficient inputs

### ISSUE THREAD

**Issue by LenaPer** [Qiskit/qiskit-ibm-runtime#71]
**Describe the bug**
When running the code from this tutorial : https://qiskit.org/documentation/optimization/tutorials/12_qaoa_runtime.html, when setting the backend to a real one, I have a _QiskitError : TensoredMeasFitter doesn\'t support subset_fitter_ when setting `measurement_error_mitigation=True`,  and a _PulseError : "Operation \'cx\' exists, but is only defined for qubits [(0, 1), (1, 0), (1, 2), (1, 3), (2, 1), (3, 1), (3, 4), (4, 3)]."_ when `use_pulse_efficient=True`

**Steps to reproduce**
```
from qiskit import IBMQ
provider = IBMQ.load_account()
import numpy as np

from qiskit.opflow import PauliSumOp, Z, I
from qiskit.algorithms.optimizers import SPSA
program_id = "qaoa"

# Define the cost operator to run.
op = (
    (Z ^ Z ^ I ^ I ^ I)
    - (I ^ I ^ Z ^ Z ^ I)
    + (I ^ I ^ Z ^ I ^ Z)
    - (Z ^ I ^ Z ^ I ^ I)
    - (I ^ Z ^ Z ^ I ^ I)
    + (I ^ Z ^ I ^ Z ^ I)
    + (I ^ I ^ I ^ Z ^ Z)
)

# SPSA helps deal with noisy environments.
optimizer = SPSA(maxiter=100)

# We will run a depth two QAOA.
reps = 2

# The initial point for the optimization, chosen at random.
initial_point = np.random.random(2 * reps)

# The backend that will run the programm.
#options = {"backend_name": "ibm_perth"}
options = {"backend_name": "ibmq_belem"}


# The inputs of the program as described above.
runtime_inputs = {
    "operator": op,
    "reps": reps,
    "optimizer": optimizer,
    "initial_point": initial_point,
    "shots": 2 ** 13,
    # Set to True when running on real backends to reduce circuit
    "measurement_error_mitigation": True,
    # depth by leveraging swap strategies. If False the
    # given optimization_level (default is 1) will be used.
    "use_swap_strategies": False,
    # Set to True when optimizing sparse problems.
    "use_initial_mapping": False,
    # Set to true when using echoed-cross-resonance hardware.
    "use_pulse_efficient": False,
}
job = provider.runtime.run(
    program_id=program_id,
    options=options,
    inputs=runtime_inputs,
)
result = job.result()

```

- **Qiskit IBM Runtime version**: {'qiskit-terra': '0.19.1', 'qiskit-aer': '0.10.1', 'qiskit-ignis': '0.7.0', 'qiskit-ibmq-provider': '0.18.3', 'qiskit-aqua': '0.9.5', 'qiskit': '0.34.0', 'qiskit-nature': '0.3.0', 'qiskit-finance': '0.3.0', 'qiskit-optimization': '0.3.0', 'qiskit-machine-learning': '0.3.0'}
- **Python version**: Python 3.8.0
- **Operating system**: macOS Big Sur

**Comment by kt474** [comment]
I believe this is a bug with the qaoa program - there is an open PR in the ntc-programs repo to update it

**Comment by kt474** [comment]
Closing this - QAOA has been removed
