### ISSUE TITLE
Potential issues in how to run a session docs

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-ibm-runtime#715]
**Describe the bug**

Reading through https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/how_to/run_session.rst there are some concerns about the session close behavior. The scheduler service now has the following behaviors:

- jobs submitted against a closed session will be rejected with an error
- jobs which are part of a session but are still queued when the session closes, either explicitly using `session.close()` or the max session TTL expires, will be put into an error state, they will not run

#653 is related to this as well.

Some specific issues in the docs:

1. This part shows a code snippet of submitting a job and then closing the session explicitly:

https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/how_to/run_session.rst#run-a-job-in-a-session

The job will be put into an error state if you don't wait for it to run to completion. So either that example should remove the explicit close or add something to the example showing waiting for the job to complete (probably calling `job.result()`).

2. This section probably needs clarification:

https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/how_to/run_session.rst#how-long-a-session-stays-active

Specifically this:

>When you are done submitting jobs, you are encouraged to use session.close() to close the session.

Again, _submitting_ the jobs and then closing the session could immediately error out those jobs. That's similar to the problem from #653 where the Session context manager would automatically close the session. I would actually not encourage users to explicitly close a session _unless they know exactly what they are doing_, because of the implications of what happens if they don't wait for their jobs to complete before closing the session.

There seems to be a misconception that closing a session means it's closed for submitting more jobs to it only. While it's true that you can't submit jobs to a closed session now, it's also true that the scheduler will no longer _run_ jobs from a closed session if those jobs were still queued when the session closed. The docs should be very clear about this and avoid mentioning anything about explicitly closing a session unless the user knows what they are doing.

Maybe this is better reserved for explaining in the API reference so it's available but a bit more buried in the docs, for advanced users:

https://qiskit.org/documentation/partners/qiskit_ibm_runtime/stubs/qiskit_ibm_runtime.Session.close.html#qiskit_ibm_runtime.Session.close

**Steps to reproduce**

n/a

**Expected behavior**

Docs update

**Suggested solutions**

see above

**Additional Information**

- **qiskit-ibm-runtime version**: 0.9.0
- **Python version**: n/a
- **Operating system**: n/a

cc @abbycross @beckykd @jyu00

**Comment by mriedem** [comment]
A good example of _why_ the queued jobs are put into error state when a session closes is we have seen many cases where people using Qiskit with the Session context manager behavior before 0.9.0 would submit sometimes 40+ jobs, the context manager would exit and close the session, and then those jobs would run in normal fair-share mode, thus losing the advantage of running in a session to begin with. The first and last jobs in the session may actually run days apart based on shares usage in the system, and when the latter jobs in the session ran the cache from the start of the session has expired, which can make those latter jobs fail or at least yield invalid results. So, we want to enforce the behavior that when you submit jobs as a session, they are a unit and are meant to run in order with priority on the backend from the scheduler once the session is active.

**Comment by beckykd** [comment]
Looks like these changes have already been made in run_session.

**Comment by mriedem** [comment]
> Looks like these changes have already been made in run_session.

How so? I was pulling stuff directly from the `main` branch for that file.

**Comment by beckykd** [comment]
> > Looks like these changes have already been made in run_session.
> 
> How so? I was pulling stuff directly from the `main` branch for that file.

My mistake.  I hadn't synced my fork.  It's straightened out now.

**Comment by beckykd** [comment]
> At the suggestion of @jyu00 , I'm adding the comment " # Close the session only if all jobs are finished, and you don't need to run more in the session" anywhere that session.close() appears in the documentation -- and adding job.result() if it's not already there.
> 
> However, there are a lot of .py files with session.close(). I didn't mess with those.

Jessie said to add the comment in the .py files too.  Working on that.
