### ISSUE TITLE
Getting memory from primitive sessions

### ISSUE THREAD

**Issue by siyuchen95** [Qiskit/qiskit-ibm-runtime#732]
I am running qiskit runtime to generate random numbers, and I'd like to see the result of individual measurements.

On Simulators I can do

job = backend.run(circuit, shots=800, memory=True)
job.result().get_memory()

but it seems that the option is ignored if I try to run it with a Sampler.

It would be nice to get that back as well because generating outputs based on quasiprobabilities will not produce the entropy we are looking for.

Thank you!

**Comment by jyu00** [comment]
@siyuchen95 the primitives are designed to provide higher level outputs used in most algorithms. If you need more direct output like per-shot measurements, you can use `backend.run` in [qiskit-ibm-provider](https://github.com/Qiskit/qiskit-ibm-provider).
