### ISSUE TITLE
Update docs on max session and program time

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#740]
**Describe the bug**

1. The [existing doc](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/faqs/max_execution_time.html#qiskit-runtime-on-ibm-quantum) on maximum execution time still talks about the limit for Open User + Private Program, except open users can no longer run private programs.

2. The default session max as described [here](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/how_to/run_session.html#how-long-a-session-stays-active) is no longer true. We now use the program max execution time described [here](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/faqs/max_execution_time.html#qiskit-runtime-on-ibm-quantum) as the default max session time (@ChitsimranGill please double check this is correct). 

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by kt474** [comment]
fixed by #846
