### ISSUE TITLE
Accept all options in a dictionary as first level

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#755]
**What is the expected feature or enhancement?**

The options one can pass to the runtime primitives are structured so that each falls under a category. For example, `shots` is under `execution`. This is true even when options are passed as a dictionary:

```
# You can do this
options = Options()
options.execution.shots = 1024

# Or this
options = {"execution": {"shots": 1024}}
```

It was designed this way to allow easier auto-complete when one simply does `options.<tab>`. However, this is inconsistent with the base primitive classes in qiskit-terra (which came after) that uses a flat structure:

```
options = {"shots": 1024}
```

This means users need to know to change their code when switching from terra (or aer) primitives to runtime primitives. Furthermore, if one does `options={"shots": 1024}`, the shot number will be silently ignored (see #754). 

**Acceptance criteria**

Allow users to specify all options as "first level" options, when passing it as a dictionary. For example, 

```
from qiskit_ibm_runtime import Estimator

estimator = Estimator(..., options={"shots": 1024})
```

The ` _merge_options()` can be used to do this.

**Comment by merav-aharoni** [comment]
Do we want to fix this on the level of the `Options` constructor as well? For example
```
from qiskit_ibm_runtime import Options
options = Options({"shots": 1})
print(options)
```
This results in 
```
Options(optimization_level={'shots': 1}, resilience_level=None, max_execution_time=None, transpilation=TranspilationOptions(skip_transpilation=False, initial_layout=None, layout_method=None, routing_method=None, approximation_degree=None), resilience=ResilienceOptions(noise_amplifier='TwoQubitAmplifier', noise_factors=(1, 3, 5), extrapolator='LinearExtrapolator'), execution=ExecutionOptions(shots=4000, init_qubits=True), environment=EnvironmentOptions(log_level='WARNING', callback=None, job_tags=[]), simulator=SimulatorOptions(noise_model=None, seed_simulator=None, coupling_map=None, basis_gates=None))
```
Or is this the way we would like `Options` to behave?

**Comment by jyu00** [comment]
`Options` is a dataclass, so no, we don't want `Options({"shots":1})`. It'd just treat the input dictionary as the value to the first positional argument (`optimization_level` in this case). Once this issue is done, one can easily convert a dictionary to an `Options` by doing `options = Options(**my_dict)`.
