### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#767]
**What is the expected feature or enhancement?**

Unlike the old IQX path, Qiskit Runtime doesn't do any input validation on the server side prior to adding jobs to the queue. This means a user can wait hours or even days just to have their job fail due to a typo. Some basic validation on the client side could reduce some of the pain. 

**Acceptance criteria**

Things to validate:
1. `resilience_level` and `optimization_level` should be within range for the primitive being called
1. `noise_amplifier` and `extrapolator` resilience options are one of those [supported values](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/options/resilience_options.py#L21-L32). 
2. `noise_factors` has at least 5 entries if `QuarticExtrapolator` is used; at least 4 if `CubicExtrapolator` is used
3. If `resilience_level=3` is specified and the backend is a simulator, a `coupling_map` must also be specified in simulator options.

A `ValueError` should be raise if the validation fails. However, there should be an env variable that one can set to bypass validation (e.g. for testing).

**Comment by merav-aharoni** [comment]
@jyu00 - two questions on this issue:
1. Do we indeed want an environment variable for testing? Can't we simply catch the validation errors we get during testing, as we usually do?
2. You asked to validate the allowed options for `resilience_options`. Shouldn't we do this for other options as well, while we are at it? E.g., options for `log_level`.

**Comment by jyu00** [comment]
> @jyu00 - two questions on this issue:
> 
> 1. Do we indeed want an environment variable for testing? Can't we simply catch the validation errors we get during testing, as we usually do?

This is not for our unit testing, but for other teams who want to test new backend features that have not been documented. 

> 2. You asked to validate the allowed options for `resilience_options`. Shouldn't we do this for other options as well, while we are at it? E.g., options for `log_level`.

We can. Resilience options are new compared to other options, and there are more input errors related to them, hence they are more important. But we certainly can do validation for other options.
