### ISSUE TITLE
Pretty print error from API

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibm-runtime#768]
**What is the expected feature or enhancement?**
Today if there is an error from the API it gets reported like:

```
IBMRuntimeError: 'Failed to run program: \'400 Client Error: Bad Request for url: https://us-east.quantum-computing.cloud.ibm.com/jobs. {"errors":[{"code":1209,"message":"You are not authorized to specify runtime parameter: got abc:xyz.","solution":"Contact support to get access.","more_info":"https://cloud.ibm.com/apidocs/quantum-computing#error-handling"}],"trace":"cgeteirdojsgo5icm4mg"}\''
```

This is hard to read. It would be great if there is a way to pretty print the json response.

**Acceptance criteria**
It would be great if it could like below:
```
IBMRuntimeError: 'Failed to run program: \'400 Client Error: Bad Request for url: https://us-east.quantum-computing.cloud.ibm.com/jobs. 
{
    "errors": [
        {
            "code":1209,
            "message":"You are not authorized to specify runtime parameter: got abc:xyz.",
            "solution":"Contact support to get access.",
            "more_info":"https://cloud.ibm.com/apidocs/quantum-computing#error-handling"
        }
    ],
    "trace":"cgeteirdojsgo5icm4mg"
}\''
```

**Comment by jyu00** [comment]
I don't think we'll be doing this because we cannot pretty print the error string inside an exception. We could pretty print the error string in addition to raising the exception, but the user can also do the pretty print themselves. And it'd be better for the user to make that decision (e.g. if they want to print or catch).
