### ISSUE TITLE
Raise early if circuit uses faulty qubits or gates

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-ibm-runtime#792]
**What is the expected feature or enhancement?**

Currently, if a user submits a circuit which uses gates or qubits which are marked as faulty, they will get an opaque `IBMJobFailureError` due to an error in transpilation.

It should be possible, when backends have faulty qubits or gates, to scan submitted circuits and raise early if there is an instruction on a faulty gate or qubit. This can help users avoid waiting in the queue for jobs which cannot run successfully, and gives an opportunity to inform the user to either use different physical qubits, or re-transpile their circuit with a different seed or settings .

N.B. https://github.com/Qiskit/qiskit-ibm-provider/issues/568 raises the same concern for `qiskit-ibm-provider`, but as far as I can tell, this would have to be addressed in both the `provider` and the `runtime`. Feel free to close one of them if that's not the case.

**Acceptance criteria**

**Comment by blakejohnson** [comment]
I believe we should do this check whenever `skip_transpilation=True` for either the Sampler or Estimator.
