### ISSUE TITLE
Error on PEC type error mitigation

### ISSUE THREAD

**Issue by maniraman-periyasamy** [Qiskit/qiskit-ibm-runtime#795]
**Describe the bug**

Running circuits with resilience level of 3 ends up with the following error:
TypeError: 'str' object is not callable

please see the attached file for full log:
[pce_error.txt](https://github.com/Qiskit/qiskit-ibm-runtime/files/11186230/pce_error.txt)

**Steps to reproduce**

Running the example code provided in Qiskit webpage:
https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/Error-Suppression-and-Error-Mitigation.html

**Expected behavior**

Circuit expectation value estimated.

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.9.2 
- **Python version**: 3.10.8
- **Operating system**: CentOS 7

**Comment by yc-guo19** [comment]
The same problem.

**Comment by chriseclectic** [comment]
This errors is from the runtime internally switching from using V1 to V2 backends before the PEC code was updated to work with V2 backends. This should be fixed soon.

**Comment by jyu00** [comment]
This is fixed
