### ISSUE TITLE
`session.run` should not require backend when no options are passed

### ISSUE THREAD

**Issue by asarver** [Qiskit/qiskit-ibm-runtime#810]
**Describe the bug**

the [docs](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/how_to/run_session.html#session-options) show that backend is only required in the `with Session(...)` block, but there is an error when removing `options` during `session.run`.

_Note: this works when `options={}` is set_

**Steps to reproduce**

```python
service = QiskitRuntimeService(channel="ibm_quantum",
                               token=os.environ.get('QISKIT_TOKEN'),
                               instance=PROVIDER,
                               url=AUTH_URL)
with Session(service=service, backend=device) as session:
        job = session.run(program_id="hello-world",
                          inputs=program_inputs)
```

#### error
if you remove the `backend` kwarg from the `Session` context manager it fails:

```
        if self._service.channel == "ibm_quantum" and not backend:
>           raise ValueError('"backend" is required for ``ibm_quantum`` channel.')
E           ValueError: "backend" is required for ``ibm_quantum`` channel.

.tox/staging/lib/python3.8/site-packages/qiskit_ibm_runtime/session.py:111: ValueError
```

And if you remove the `options` dict:

```
        if channel == "ibm_quantum" and not self.backend:
>           raise IBMInputValueError(
                '"backend" is required field in "options" for "ibm_quantum" channel.'
            )
E           qiskit_ibm_runtime.exceptions.IBMInputValueError: '"backend" is required field in "options" for "ibm_quantum" channel.'

.tox/staging/lib/python3.8/site-packages/qiskit_ibm_runtime/runtime_options.py:93: IBMInputValueError
```

**Expected behavior**

`session.run` uses the backend within the session context instead of explicitly requiring it via `options`

**Additional Information**

- **qiskit-ibm-runtime version**: 0.9.3
- **Python version**: 3.10.9
- **Operating system**: tested on both mac os and linux

**Comment by merav-aharoni** [comment]
I tried to reconstruct this failure, but it passed for me. I probably missed something. Can you post a complete test case that fails @asarver ?

**Comment by mriedem** [comment]
> And if you remove the `options` dict:

I wonder if you hit what I did in #879? It was a mistake on my part. Removing the `options` dict from `session.run` was fine as long as the session was started with the `backend` kwarg.

**Comment by asarver** [comment]
ah yeah, I cannot get this to fail now. Thanks @mriedem
