### ISSUE TITLE
No error message from provider but on IQP

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#811]
**Describe the bug**

When my job `ch1ebkol1tcq36kffct0` failed, the IQP dashboard had a nice error message

<img width="563" alt="image" src="https://user-images.githubusercontent.com/28284230/233725660-80f2b707-54d5-4291-bd0f-9ec54b1d6f8d.png">

But `job.result()` doesn't tell me anything:

```
RuntimeJobFailureError: 'Unable to retrieve job result. Job ch1ebkol1tcq36kffct0 has failed:\n'
```

**Steps to reproduce**

**Expected behavior**

I should get the same error message back.

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.9.3
- **Python version**:
- **Operating system**:

**Comment by merav-aharoni** [comment]
@jyu00 - is this a specific error you are referring to or are you referring to the general passing of error messages from IQX/ntc to the client side?
For example, when we get an error message of the type:
```
raise RuntimeJobFailureError(
qiskit_ibm_runtime.exceptions.RuntimeJobFailureError: 'Unable to retrieve job result. Job ch7t1a16klhd7q9nmsb0 has failed:\n2023-05-01T14:41:10.325743630Z Setting up watches.\n2023-05-01T14:41:10.325743630Z Watches established.\n2023-05-01T14:41:11.869480303Z INFO:     Started server process [7]\n2023-05-01T14:41:11.869480303Z INFO:     Waiting for application startup.\n2023-05-01T14:41:11.869644223Z INFO:     Application startup complete.\n2023-05-01T14:41:11.870529297Z INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)\n2023-05-01T14:46:01.568084729Z INFO:     127.0.0.1:58630 - "POST /run HTTP/1.1" 202 Accepted\n2023-05-01T14:46:01.592333791Z /opt/app-root/lib64/python3.9/site-packages/qiskit/qpy/interface.py:246: UserWarning: The qiskit version used to generate the provided QPY file, 0.24.0, is newer than the current qiskit version 0.23.3. This may result in an error if the QPY file uses instructions not present in this current qiskit version\n2023-05-01T14:46:01.592333791Z   warnings.warn(\n2023-05-01T14:46:01.708923029Z programruntime.program_starter_wrapper - ERROR Error executing program job ch7t1a16klhd7q9nmsb0\n2023-05-01T14:46:01.709192817Z webserver-starter - ERROR Failed to execute program: \'Number of qubits (37) in circuit-96 is greater than maximum (27) in the coupling_map\'\n2023-05-01T14:46:01.713413295Z /pod-data/ CLOSE_WRITE,CLOSE terminated\n2023-05-01T14:46:01.713709365Z Termination marker file found. Kill process (7).\n2023-05-01T14:46:01.727959171Z /bin/bash: line 3:     7 Killed                  python -m uvicorn server.main:app --port 8081\n2023-05-01T14:46:01.728262989Z Termination signal received, exited.\n'
```
Do we want the provider to catch this and return a more reasonable message to the user? E.g., `ERROR: 'Number of qubits (37) in circuit-96 is greater than maximum (27) in the coupling_map`

**Comment by jyu00** [comment]
> Do we want the provider to catch this and return a more reasonable message to the user? E.g., ERROR: 'Number of qubits (37) in circuit-96 is greater than maximum (27) in the coupling_map

That would be great! I don't know if IQP is doing something similar, since it's showing a nice message instead of the stacktrace or just blank. 

If you want to produce the specific `RecursionError` (which I'm just using as an example), you can just send a 100-qubit x 20 depth random circuit to seattle (before they fix it) lol

**Comment by rathishcholarajan** [comment]
We store this nice error in db now and return it as `state.reason` in this API https://us-east.quantum-computing.cloud.ibm.com/openapi#/Jobs/get_job_details_jid and that's how it shows up in IQP UI. So all the provider needs to do is return this to the user when user requests `job.error_message()`. 

For `job.result()` the proper fix has to be a server side fix to save the nicer error message as json in results field, but if we want a temp fix in provider when the job has failed provider can replicate logic for `job.error_message()` when user calls `job.result()`. I would rather open an issue and fix it in API.

**Comment by merav-aharoni** [comment]
I think, for a start, I will return the `job._reason` rather than `job._error_message`. See https://github.com/Qiskit/qiskit-ibm-runtime/pull/818.
From various examples of failures, I see that this doesn't cover all cases, so I will need to check if there are other places that need to be updated.
