### ISSUE TITLE
Expose job status reason if there is no result on a failed job

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-ibm-runtime#841]
**What is the expected feature or enhancement?**

With recent changes in the scheduler for the ibm_cloud and ibm_quantum channels, jobs in a session which didn't run before the session closed will be errored out and put into a `Failed` status.

On the client side, when you look for the error message on these jobs you just get something like this:

`Job chd744aceq17dip7od0g has failed:`

Note the colon without anything after it. I believe that comes from this code:

https://github.com/Qiskit/qiskit-ibm-runtime/blob/63742c76c9dc93ca8cbadf82c17bf2e3db321047/qiskit_ibm_runtime/runtime_job.py#L451-L471

In this case the job failed before it ran, as part of the scheduler, so there are no results, but there is the reason, which in the DB is this:

`Session chd7442ceq17dip7octg has been closed`

It'd be nice if there are no results for the job, if we could expose the reason (if there is one) in the `RuntimeJob.error_message()` return value. There might be implications for not wanting to expose all reasons in case there are internal details that shouldn't be leaked out, but I'd think maybe the job status reason code could be used to determine that. In this case the reason code was 1217.

**Acceptance criteria**

Expose the job status reason if there are no results on a failed job.

**Comment by kt474** [comment]
> I think this is a duplicate of #811?

Yes, we have an open PR #818 for that but it won't fix this issue.

The changes in #818 will make it so if there are no results, just the reason is returned in `job.result()` and then the full error log(`job_result_raw`) is returned in `job.error_message()`  (which should also include the reason). So for this scenario, we could add logic to check if `job_result_raw` exists and if not, return the reason.

**Comment by jyu00** [comment]
> The changes in https://github.com/Qiskit/qiskit-ibm-runtime/pull/818 will make it so if there are no results, just the reason is returned in job.result()

Shouldn't it be the other way around? i.e. return results (error log) only if there is no reason? Since reason is often more useful and easier to decipher than the full error log.

**Comment by kt474** [comment]
Yes, that's what I meant - it currently works that way https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/runtime_job.py#L224

If there is no reason, the error message is returned
