### ISSUE TITLE
Explain `SPSA(150)` in VQE tutorial

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-ibm-runtime#854]
The tutorial https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/vqe_with_estimator.html#Solve-with-VQE has the following example:

```python
from qiskit.algorithms.minimum_eigensolvers import VQE

# Use RealAmplitudes circuit to create trial states
from qiskit.circuit.library import RealAmplitudes

ansatz = RealAmplitudes(num_qubits=2, reps=2)

# Search for better states using SPSA algorithm
from qiskit.algorithms.optimizers import SPSA

optimizer = SPSA(150)
```

In this example, the `SPSA(150)` line is a bit obscure.  Some ways to improve it:
 * A link to <https://qiskit.org/documentation/stubs/qiskit.algorithms.optimizers.SPSA.html>
 * Explain the parameter `SPSA(maxiter=150)`, maybe with an inline comment.
 * Explain why `150` is a good parameter.

**Comment by nonhermitian** [comment]
This will be removed in the upcoming tutorial refresh.
