### ISSUE TITLE
Please update link in GitHub's About section to https://qiskit.org/ecosystem/ibm-runtime/ 

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/qiskit-ibm-runtime#856]
The site now lives on /ecosystem/ibm-runtime.

To fix this, go to the "Code"/home page of the repo. Then click the wheel on the "about" section on the right. Set the website to https://qiskit.org/ecosystem/ibm-runtime/.

![Screenshot 2023-05-15 at 9 55 20 AM](https://github.com/Qiskit-Partners/qiskit-aqt-provider/assets/14852634/5085a3cd-e3d8-43e1-996f-be9e3c9d6147)

Thanks!

**Comment by kt474** [comment]
Done!
