### ISSUE TITLE
Simultaneous measurement support for the Estimator

### ISSUE THREAD

**Issue by Zshan0** [Qiskit/qiskit-ibm-runtime#865]
**What is the expected feature or enhancement?**
To measure multiple observables on the same circuit with `Estimator` and optimize the total shots with commuting operators.

For example, I would like to run a circuit corresponding to constructing the ground state of the transverse field quantum Ising chain and measure the overall magnetization.

The overall magnetization is given by $M = \frac{1}{N} \sum_i Z_i$ Here $Z_i$ denotes an observable with $I$ at all qubit locations other than $i$ where there is a $Z$ operator. These observables commute, which means that I should be able to measure all of them simultaneously, reducing the total number of shots by a factor of $N$.

**Acceptance criteria**

A functionality that will allow me to pass a set of observables for the same circuit, and indicate that they commute so that all of them can be measured simultaneously. The estimator should return the expectation value for all the individual observables.

**Comment by garrison** [comment]
I believe that what you desire is the default behavior of the Qiskit Runtime Estimator, and currently there is no way to turn this off.  (Specifically, this optimization will happen when the operators _qubit-wise_ commute.)  Is there something in particular, in code that you have run, that leads you to believe that this optimization is not taking place?

**Comment by garrison** [comment]
My above comment is only correct for a single `SparsePauliOp`, apparently. See discussion at https://github.com/Qiskit/qiskit-ibm-runtime/issues/903#issuecomment-1590511496.

**Comment by Zshan0** [comment]
Will the support be added for `Estimator`? I can close this issue if that is not planned.

**Comment by garrison** [comment]
@Zshan0, this [has been fixed](https://github.com/Qiskit/qiskit-ibm-runtime/issues/903#issuecomment-1955254877) in `EstimatorV2`.  I recommend upgrading to version 2 of the primitives, following the guide at https://docs.quantum.ibm.com/api/migration-guides/qiskit-1.0-features#qiskitprimitives.

**Comment by ihincks** [comment]
Closing this issue as, as @garrison mentions, the V2 Estimator implements this. For every unique parameter set in a pub, all of the terms in all observables are unioned together, grouped into qubit-wise commuting groups, and one execution is performed for each group.
