### ISSUE TITLE
Expose session details

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#887]
**What is the expected feature or enhancement?**

An user should be able to query for the remaining session time from a session instance. In addition, it'd also be useful to know about session status, and what the various TTLs are. 

**Acceptance criteria**

- [ ] Expose session details, including
    - backend name
    - created/updated/started/closed timestamps
    - last job start/complete
    - interactive ttl (map to `interactive_timeout`)
    - max ttl (map to `max_time` to match session parameter)
    - state (should map to `open`, `closed` (not accepting job, see [this issue](https://github.com/Qiskit/qiskit-ibm-runtime/issues/1008)), and `cancelled`)
- [ ] Doc update

**Comment by kt474** [comment]
@merav-aharoni you can see how these session details are exposed [here](https://us-east.quantum-computing.cloud.ibm.com/openapi/#/Sessions/get_session_information). Currently, this is only supported on the cloud channel. We can start working on this issue, but should wait until this is also supported on the iqp side before merging. 

You can also see @kvcmarshall's helpful screen shots in her PR on the server side (ntc 3052)

**Comment by jyu00** [comment]
@beckykd we should also update session docs once this is done - e.g. under [session time limits](https://qiskit.org/ecosystem/ibm-runtime/faqs/max_execution_time.html#session-time-limits) we can show code to query the data.

**Comment by mriedem** [comment]
For IQP (`quantum` channel) the API is here: https://api-dev.quantum-computing.ibm.com/runtime/api#/sessions/GetSessionDetailsController_sendAcceptingJobs
