### ISSUE TITLE
Add method to return `Sampler` transpiled circuits

### ISSUE THREAD

**Issue by mberna** [Qiskit/qiskit-ibm-runtime#898]
**What is the expected feature or enhancement?**
Transpiled circuits are available for Sampler jobs. We need to provide a way to be able to retrieve these transpiled circuits from this package.

**Acceptance criteria**
Proposal: add a `SamplerJob` class that inherits from `RuntimeJob` . Add a `transpiled_circuits()` method to the `SamplerJob` class. Transpiled circuits are only available for Sampler jobs, not Estimator.

**Comment by cacosomoza** [comment]
Not having access to the transpiled circuits with the specific decomposition of the gates that was deployed on the backend seems really urgent to me. For publication-quality results, specifics are extremely important! One could do the same about the specific implementation of the noise resilience and circuit optimization implementations.

**Comment by balewski** [comment]
Is there any progress on  giving user access to transpiled circuit? It is important to know which qubits have been chosen. Is there any hack in the meantime?

**Comment by jyu00** [comment]
Let's just close this for now. With ISA circuit change, SamplerV2 doesn't do transpilation anymore.
