### ISSUE TITLE
Add support for simultaneous measurement of commuting-observables in Runtime

### ISSUE THREAD

**Issue by HaoranLiao** [Qiskit/qiskit-ibm-runtime#903]
**What is the expected feature or enhancement?**
Currently, if one wants to measure, say ZIII, IZII, and IIIZ on a 4q quantum circuit, one will need to submit three copies of the same circuit to Runtime, each of which corresponds to one of the observables. This is very inefficient. There are already features to support commuting observable simultaneous measurement if the observable has terms that are commuting. For example, if the observable is a SparsePauliOp of three terms ZZII+0.5IIZI+0.2IIIZ, only one measurement is needed in Runtime. This could be naturally expanded to solve the raised problem

**Acceptance criteria**

**Comment by t-imamichi** [comment]
Runtime Estimator applies grouping of SparsePauliOp in terms of qubit-wise commuting. So, `ZZII+0.5IIZI+0.2IIIZ` will be grouped and evaluated with one measurement.
Ref: https://qiskit.org/documentation/stubs/qiskit.quantum_info.SparsePauliOp.group_commuting.html

**Comment by HaoranLiao** [comment]
@t-imamichi Yes, and that's why I said "There are already features to support commuting observable simultaneous measurement if the observable has terms that are commuting. For example, if the observable is a SparsePauliOp of three terms ZZII+0.5IIZI+0.2IIIZ, only one measurement is needed in Runtime." 

I suggest extending this feature to separate observables (not in a sum) that are commuting, because oftentimes, we want to measure let's say single Z's on multiple qubits. And currently, it takes multiple copies of the circuit (each one with a single Z observable) and multiple executions on the backend to get all of them, which is very inefficient.

**Comment by HaoranLiao** [comment]
I see that this issue has been discussed in: https://github.ibm.com/IBM-Q-Software/ws-primitives/issues/76 since two days ago. Thanks.

**Comment by t-imamichi** [comment]
Could you not put an internal link here in public github, please?

**Comment by nonhermitian** [comment]
Yes, this use case is quite common.  Single qubit magnetization comes to mind.

**Comment by caleb-johnson** [comment]
[circuit-knitting-toolbox.entanglement_forging](https://qiskit-extensions.github.io/circuit-knitting-toolbox/entanglement_forging/explanation/index.html) needs the grouping described here. We are currently reverting our usage of the `Estimator`, and we'll instead use `Sampler` and calculate our own expvals so that we can do Pauli observable grouping.

**Comment by zlatko-minev** [comment]
Was this ever resolved? Looking for this functionality again

**Comment by jyu00** [comment]
This will be available in v2 primitives

**Comment by zlatko-minev** [comment]
Thanks! Looking forward to them 

What's the best place / link to track the roadmap specification for V2?

**Comment by ihincks** [comment]
The V2 estimator was released in qiskit-ibm-runtime version 0.21 which fixes this issue.
