### ISSUE TITLE
Runtime docs do not indicate version number

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#915]
**What is the expected feature or enhancement?**
It is currently impossible to tell what Runtime version the documentation corresponds to.

**Acceptance criteria**
The docs should explicitly have the Runtime version number on the front page.  E.g. see Terra docs: https://qiskit.org/documentation/#qiskit-version-documentation

**Comment by beckykd** [comment]
Is the expectation that we would maintain multiple versions of the documentation, or just that we include the version number (which will always just be the current version number) in the docs?  Also, is there somewhere I can find the current code version?  Is it updated every 2 weeks, when @kt474 merges changes?

**Comment by beckykd** [comment]
> Is the expectation that we would maintain multiple versions of the documentation, or just that we include the version number (which will always just be the current version number) in the docs? Also, is there somewhere I can find the current code version? Is it updated every 2 weeks, when @kt474 merges changes?

I got answers for most of this via Slack from Kevin - just need to know whether the expectation is that we will have multiple versions of the documentation published.  If that's the case, we'll need to track this in a broader discussion.  But I'll add the version number for now.

**Comment by nonhermitian** [comment]
Just version number
