### ISSUE TITLE
Test all resilience levels

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#922]
**What is the expected feature or enhancement?**

We should have unit tests and ideally integration tests (simulator only) for all resilience levels.

**Acceptance criteria**

Have unit tests for running primitives at different resilience levels.

**Comment by merav-aharoni** [comment]
@jyu00 - do you mean tests that actually check the quality of the results? or just tests that check that each resilience level is set  properly and doesn't fail?

**Comment by merav-aharoni** [comment]
From a conversation with @jyu00 and @kt474 - check that the values are correct in the metadata in the response.

**Comment by kt474** [comment]
Discussion from a meeting - adding this here for a little more detail: 

Ways to differentiate metadata:
- resilience level 1: contains `readout_mitigation_num_twirled_circuits`
- resilience level 2: contains `zne`
- resilience level 3: contains `standard_error`

```
# resilience level 1 
Metadata: {'variance': 0.999984, 'shots': 4000, 'readout_mitigation_num_twirled_circuits': 16, 'readout_mitigation_shots_calibration': 8192}

# resilience level 2 
Metadata: {'zne': {'noise_amplification': {'noise_amplifier': "<TwoQubitAmplifier:{'noise_factor_relative_tolerance': 0.01, 'random_seed': None, 'sub_folding_option': 'from_first'}>", 'noise_factors': [1, 3, 5], 'values': [0.025, -0.0245, -0.0145], 'variance': [0.999375, 0.99939975, 0.99978975], 'shots': [4000, 4000, 4000]}, 'extrapolation': {'extrapolator': 'LinearExtrapolator'}}}

# resilience level 3 
Metadata: {'standard_error': 0.0013975411040892565, 'shots': 512000, 'samples': 4000, 'sampling_overhead': 1, 'total_mitigated_layers': 0}
```
