### ISSUE TITLE
Use service already initialized

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#923]
**What is the expected feature or enhancement?**

Since `Sampler` and `Estimator` accepts a backend name string, a user can easily do something like

```
service = QiskitRuntimeService(..., instance="h1/g1/p1")
job = Sampler("ibmq_manila").run(...)
```

and expect the `service` object to be used (with h1/g1/p1). But since `service` is not passed to `Sampler`, it'd actually just use whatever the default is from `QiskitRuntimeService()`.  There is also no way to pass `service` to `Sampler` today. 

**Acceptance criteria**

Save and use the `QiskitRuntimeService` if one was previously initialized when backend name is passed to the primitive.

**Comment by merav-aharoni** [comment]
@jyu00 , I am trying to understand your intent. How would Sampler know which service to use? What if the user defines 2 services, for example?

**Comment by kt474** [comment]
Just noticed that if you have both a cloud and quantum channel account configured and run something like this, the job will actually run on the cloud channel, because it's the default. #955 will also fix this issue

```python

service = QiskitRuntimeService(channel="ibm_quantum")

job = Sampler('ibmq_qasm_simulator').run(ReferenceCircuits.bell())
job.result()

```
