### ISSUE TITLE
Failed cron job tests

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit-ibm-runtime#93]
Compiling all of the consistently failing cron job tests here to avoid constantly scrolling through all the logs 
Also makes it easier to track 

Tests that failed multiple times in past 30 days:

Cron prod 
- `test_retrieve_interim_results`, `test_run_program_failed` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4770862632?check_suite_focus=true#step:5:2715)
- `test_stream_results_done`, `test_retrieve_job_running` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4770862701?check_suite_focus=true#step:5:3080)
- `test_job_logs` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4798875351?check_suite_focus=true#step:5:1289)

Cron staging 
- `test_callback_cancel_job` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4771170167?check_suite_focus=true#step:5:3231)
- `test_interim_result_callback` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4751624404?check_suite_focus=true)
- `test_stream_results` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4836695675?check_suite_focus=true#step:5:2191)

Slow test
- test suite exceeds 6 hours [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4771840368?check_suite_focus=true)
- `test_callback_cancel_job`, `test_retrieve_interim_results` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4785873993?check_suite_focus=true#step:5:3483)
- `test_retrieve_unauthorized_program_data` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4799854338?check_suite_focus=true#step:5:3159)
- `test_retrieve_returned_jobs` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4837351455?check_suite_focus=true#step:5:3430)

Terra main 
- `test_run_program_real_device` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4656428096?check_suite_focus=true#step:5:2497)
- many failed jobs that don't fail consistently 

will check the cron jobs daily to keep this issue updated

**Comment by jyu00** [comment]
> Cron prod
> 
> * `test_retrieve_interim_results`, `test_run_program_failed` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4770862632?check_suite_focus=true#step:5:2715)
> * `test_stream_results_done`, `test_retrieve_job_running` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4770862701?check_suite_focus=true#step:5:3080)

These are all connection issues. Hopefully #92 will help. #33 will help too once done; polling for job status creates a lot of requests. 

> * `test_retrieve_job_queued`, `test_cancel_job_queued`, `test_delete_job_queued` [link](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4698201609?check_suite_focus=true#step:5:1503)
> 

These are related to `ibmq_berlin` being retired but not removed fro the account. Should be fixed by #75.
