### ISSUE TITLE
Interim result streaming doesn't work

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#933]
**Describe the bug**

Interim result streaming doesn't work.

**Steps to reproduce**

```
def my_callback(job_id, response):
    print(f"response in my_callback: {response}")

options = {'backend_name': "ibm_ithaca"}
job = provider.runtime.run(
    program_id="test-program",
    options=options,
    inputs={},
    callback=my_callback,
)
result = job.result()
```

I wrote a simple `test-program` to make testing easier:

```
import time

def main(backend, user_messenger, **kwargs):
    for i in range(5):
        time.sleep(5)
        user_messenger.publish(f"iteration {i}")
    return "Hello, World!"
```

**Expected behavior**

Interim results are received and printed to the screen.

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.11.1
- **Python version**: 3.9
- **Operating system**:

**Comment by kt474** [comment]
We will remove the interim results streaming code from this code base after ws-runtime issue # 381

**Comment by kt474** [comment]
We are deprecating interim results in #1774, closing this issue
