### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 29: invalid start byte

### ISSUE THREAD

**Issue by AzizNgoueya** [Qiskit/qiskit-ibm-runtime#934]
**Describe the bug**

The runtime can't decode a circuit containing a barrier instruction applied on a two dimensionnal array of qubits
**Steps to reproduce**
`circuit.barrier([[0]])`
**Expected behavior**

**Suggested solutions**
I am not sure if by appending the barrier instruction this way on this circuit should work but just using `circuit.barrier([0])` is fine

**Additional Information**

- **qiskit-ibm-runtime version**: 0.10.0
- **Python version**: 3.8
- **Operating system**: OSX

**Comment by kt474** [comment]
@AzizNgoueya Can you post a snippet of code to replicate this issue?

**Comment by kt474** [comment]
Closing for now, feel free to reopen
