### ISSUE TITLE
... invalid version and will not be supported in a future release

### ISSUE THREAD

**Issue by julenl** [Qiskit/qiskit-ibm-runtime#941]
**Describe the bug**
Loading the `QiskitRuntimeService` produces an ugly `PkgResourcesDeprecationWarning` message.

``` python
>>> from qiskit_ibm_runtime import QiskitRuntimeService
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
```

**Steps to reproduce**
Install the (latest version of) the package with pip and load it.

``` bash
pip install --upgrade qiskit qiskit-ibm-runtime
python3 -c 'import qiskit_ibm_runtime'
```

**Expected behavior**
The packages distributed from PyPi should not have such errors (warnings) by simply loading modules.

**Suggested solutions**
Maybe adding a version tag to the code, which can be parsed by `parse_version()`?

**Additional Information**

- **qiskit-ibm-runtime version**: 0.11.1
- **Python version**: 3.10.6
- **Operating system**: Ubuntu

**Comment by kt474** [comment]
Seems like this is unrelated to `qiskit-ibm-runtime` and actually a bug with `setuptools`

https://askubuntu.com/questions/1406952/what-is-the-meaning-of-this-pkgresourcesdeprecationwarning-warning-from-pipenv

**Comment by julenl** [comment]
You are right @kt474, I upgraded `pyenv` with `pip3 install --upgrade pipenv` and now the warning is gone.
Thank you very much!
