### ISSUE TITLE
Properly disposition Qiskit Runtime content

### ISSUE THREAD

**Issue by beckykd** [Qiskit/qiskit-ibm-runtime#952]
With the release of 1xp, the Qiskit Runtime content needs to be either removed or redirected.  I'm not sure what has been decided, but these are the suggestions:

- Remove the content for Qiskit Runtime and replace it with pointers to the new location (that is, delete the words and put the new URL in the file for a time before actually deleting the files).
- Leave the content for now with a big warning / notice banner across the top for a couple of weeks.
- Create redirects for the URLs in question; either right away or after a warning has been in the banner for a while.

**Comment by kt474** [comment]
I believe this has been completed
