### ISSUE TITLE
Allow users to specify a default channel 

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit-ibm-runtime#954]
**What is the expected feature or enhancement?**

Currently, if a user has both a cloud and quantum channel account saved, calling `QiskitRuntimeService()` without any parameters will always default to the cloud channel. It would be useful to specify a default channel, maybe with `os.environ["QISKIT_IBM_CHANNEL"]`, which already exists but is only used when the auth and url are also saved as env variables. 

I believe there may have been a specific reason why the cloud channel is the default (but I don't remember)

**Comment by jyu00** [comment]
In addition to an env var, it'd be nice if one can identify the default to use when save the account (e.g. `save_account(..., default=True)`)
