### ISSUE TITLE
Cannot deserialize IBMBackend

### ISSUE THREAD

**Issue by iuliazidaru** [Qiskit/qiskit-ibm-runtime#962]
**Describe the bug**

When deserializing IBMBackend I get RecursionError: maximum recursion depth exceeded

---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
Cell In[37], line 7
      4 pickle_out.close()
      6 dict_pickle_in = open("dict.pickle","rb")
----> 7 dict1 = pickle.load(dict_pickle_in)
      8 print(dict1)

File ~/REPO/Internal-QML-Acceleration-Toolkit/venv/lib/python3.9/site-packages/qiskit_ibm_runtime/ibm_backend.py:199, in IBMBackend.__getattr__(self, name)
    193 """Gets attribute from self or configuration
    194 
    195 This magic method executes when user accesses an attribute that
    196 does not yet exist on IBMBackend class.
    197 """
    198 # Lazy load properties and pulse defaults and construct the target object.
--> 199 self._get_properties()
    200 self._get_defaults()
    201 self._convert_to_target()

File ~/REPO/Internal-QML-Acceleration-Toolkit/venv/lib/python3.9/site-packages/qiskit_ibm_runtime/ibm_backend.py:222, in IBMBackend._get_properties(self, datetime)
    220 if datetime:
    221     datetime = local_to_utc(datetime)
--> 222 if not self._properties:
    223     api_properties = self._api_client.backend_properties(
    224         self.name, datetime=datetime
    225     )
    226     if api_properties:

File ~/REPO/Internal-QML-Acceleration-Toolkit/venv/lib/python3.9/site-packages/qiskit_ibm_runtime/ibm_backend.py:199, in IBMBackend.__getattr__(self, name)
    193 """Gets attribute from self or configuration
    194 
    195 This magic method executes when user accesses an attribute that
    196 does not yet exist on IBMBackend class.
    197 """
    198 # Lazy load properties and pulse defaults and construct the target object.
--> 199 self._get_properties()
    200 self._get_defaults()
    201 self._convert_to_target()

File ~/REPO/Internal-QML-Acceleration-Toolkit/venv/lib/python3.9/site-packages/qiskit_ibm_runtime/ibm_backend.py:222, in IBMBackend._get_properties(self, datetime)
    220 if datetime:
    221     datetime = local_to_utc(datetime)
--> 222 if not self._properties:
    223     api_properties = self._api_client.backend_properties(
    224         self.name, datetime=datetime
    225     )
    226     if api_properties:

    [... skipping similar frames: IBMBackend.__getattr__ at line 199 (1483 times), IBMBackend._get_properties at line 222 (1483 times)]

File ~/REPO/Internal-QML-Acceleration-Toolkit/venv/lib/python3.9/site-packages/qiskit_ibm_runtime/ibm_backend.py:199, in IBMBackend.__getattr__(self, name)
    193 """Gets attribute from self or configuration
    194 
    195 This magic method executes when user accesses an attribute that
    196 does not yet exist on IBMBackend class.
    197 """
    198 # Lazy load properties and pulse defaults and construct the target object.
--> 199 self._get_properties()
    200 self._get_defaults()
    201 self._convert_to_target()

File ~/REPO/Internal-QML-Acceleration-Toolkit/venv/lib/python3.9/site-packages/qiskit_ibm_runtime/ibm_backend.py:222, in IBMBackend._get_properties(self, datetime)
    220 if datetime:
    221     datetime = local_to_utc(datetime)
--> 222 if not self._properties:
    223     api_properties = self._api_client.backend_properties(
    224         self.name, datetime=datetime
    225     )
    226     if api_properties:

RecursionError: maximum recursion depth exceeded

**Steps to reproduce**
service = QiskitRuntimeService(channel="ibm_quantum")
backend = service.backend("ibmq_qasm_simulator")

import pickle
pickle_out = open("dict.pickle","wb")
pickle.dump(backend, pickle_out)
pickle_out.close()

dict_pickle_in = open("dict.pickle","rb")
dict1 = pickle.load(dict_pickle_in)
print(dict1)
**Expected behavior**
Deserialization works.

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- 0.20.2
- **Python version**:
3.9.6
- **Operating system**:
- Darwin

**Comment by kt474** [comment]
I believe this should work on the latest version of `qiskit-ibm-runtime`, 0.11.2 - can upgrade and then try again

**Comment by iuliazidaru** [comment]
Thank you @kt474 ! Works :)
