### ISSUE TITLE
WebsocketError - Failed to establish a websocket connection

### ISSUE THREAD

**Issue by CarolaCiara** [Qiskit/qiskit-ibm-runtime#967]
**Describe the bug**
I encountered a WebsocketError while running the provided code that utilizes qiskit-ibm-runtime. The specific error message is as follows:
qiskit_ibm_runtime.api.exceptions.WebsocketError: 'Max retries exceeded: Failed to establish a websocket connection.'

**Steps to reproduce**
1. Run the provided code that uses qiskit-ibm-runtime.
2. Observe the error message: 'Max retries exceeded: Failed to establish a websocket connection.'

**Expected behavior**
The code should execute without errors and connect successfully to the IBM Quantum Runtime service. I have no problem with my API TOKEN or my internet connection.

**Additional Information**

- **qiskit-ibm-runtime version**: 0.11.1
- **Python version**: 3.11.0
- **Operating system**: macOS Ventura 13.4.1

**Comment by kt474** [comment]
Hi @CarolaCiara! Can you post a snippet of code to replicate this issue?

**Comment by CarolaCiara** [comment]
### Sure, here an example:

from qiskit.circuit.library import EfficientSU2
from qiskit.providers.ibmq import IBMQ
from qiskit_ibm_runtime import QiskitRuntimeService, Session, Sampler

IBMQ.load_account()

# Create ansatz
ansatz = EfficientSU2(4).bind_parameters([1]*32)
ansatz.measure_all()

# Prepare IBMQ runtime session with "its own" QASM simulator
service = QiskitRuntimeService()
backend = service.get_backend('ibmq_qasm_simulator')
with Session(service=service, backend=backend, max_time='5m') as session:
    # Create Sampler instance to obtain the measurement quasi-distribution
    # Because it's created inside the context manager, it automatically uses the session

    sampler = Sampler()

    # Transform quasi-distribution to counts
    res = {k: int(v*2048)
           for k, v in sampler.run(ansatz).result().quasi_dists[0].binary_probabilities().items()}
    meas_res = dict(sorted(res.items(), key=lambda x: x[1], reverse=True))
    print(meas_res)

    # Close the session
    session.close()

**Comment by CarolaCiara** [comment]
Sure, here an example:

from qiskit.circuit.library import EfficientSU2
from qiskit.providers.ibmq import IBMQ
from qiskit_ibm_runtime import QiskitRuntimeService, Session, Sampler

IBMQ.load_account()

ansatz = EfficientSU2(4).bind_parameters([1]*32)
ansatz.measure_all()

service = QiskitRuntimeService()
backend = service.get_backend('ibmq_qasm_simulator')
with Session(service=service, backend=backend, max_time='5m') as session:

    sampler = Sampler()
   
    res = {k: int(v*2048)
           for k, v in sampler.run(ansatz).result().quasi_dists[0].binary_probabilities().items()}
    meas_res = dict(sorted(res.items(), key=lambda x: x[1], reverse=True))
    print(meas_res)
    
    session.close()

**Comment by merav-aharoni** [comment]
I suggest you remove the lines: 
 ```
 from qiskit.providers.ibmq import IBMQ
 IBMQ.load_account()
```
In addition, use:
```
service = QiskitRuntimeService(channel="ibm_quantum") or 
service = QiskitRuntimeService(name=<your_cloud_account_name>)
```
depending on which service you wish to use.

**Comment by CarolaCiara** [comment]
Thank you for your suggestion @merav-aharoni, unfortunately even with this modification, it still doesn't work and I keep getting the same error:

 from qiskit.circuit.library import EfficientSU2
 from qiskit_ibm_runtime import QiskitRuntimeService, Session, Sampler
 ansatz = EfficientSU2(4).bind_parameters([1]*32)
 ansatz.measure_all()

 service = QiskitRuntimeService(channel="ibm_quantum")
 backend = service.get_backend('ibmq_qasm_simulator')
 with Session(service=service, backend=backend, max_time='5m') as session:
     sampler = Sampler()
     res = {k: int(v*2048)
            for k, v in sampler.run(ansatz).result().quasi_dists[0].binary_probabilities().items()}
     meas_res = dict(sorted(res.items(), key=lambda x: x[1], reverse=True))
     print(meas_res)
     session.close()

# WebsocketError: 
qiskit_ibm_runtime.api.exceptions.WebsocketError: 'Max retries exceeded: Failed to establish a websocket connection.'

**Comment by kt474** [comment]
Closing this issue for now, feel free to reopen if you are still having this problem
