### ISSUE TITLE
Changes in `runtime` following implementation of `Session` in `provider`

### ISSUE THREAD

**Issue by merav-aharoni** [Qiskit/qiskit-ibm-runtime#969]
**What is the expected feature or enhancement?**
In https://github.com/Qiskit/qiskit-ibm-provider/pull/675, we are supporting `Session` in `qiskit-ibm-provider`. 
I am opening this issue to keep track of changes that should be done here after the above PR is complete.
- [x] Remove `utils/converters.py` and import that from `qiskit-ibm-provider`.
- [ ] Can `class Session` be united between the two repos?
- [x] Can `api/rest/rutime_session.py` be united between the two repos?
- [x] Consider removing `Session._circuits_map` if not used
- [x] Fix example in `session.py` documentation. `circ` is not defined.

**Acceptance criteria**

**Comment by jyu00** [comment]
Addition code that can probably be united:

- `ibm_backend.py`
- `hub_group_project.py`
- `exception.py`
- `constants.py`
- account management
- job
- a bunch of code in `utils`, like `json.py`, `runner_result.py`, etc

**Comment by merav-aharoni** [comment]
`Session` here cannot be united with that of `qiskit-ibm-provider` because here is has a `QiskitRuntimeService` member. However, I think we could inherit here from `Session` in provider. This would require changing one of the `Session` names. @kt474 , @jyu00 - let me know if you think this is worthwhile.

**Comment by merav-aharoni** [comment]
> 

I am moving this list to #1028, because these duplications are not related to the implementation of `Session` in the provider, and uniting these files is not trivial.

**Comment by kt474** [comment]
> `Session` here cannot be united with that of `qiskit-ibm-provider` because here is has a `QiskitRuntimeService` member. However, I think we could inherit here from `Session` in provider. This would require changing one of the `Session` names. @kt474 , @jyu00 - let me know if you think this is worthwhile.

We can focus on the other parts of this issue for now, changing one of the `Session` names would complicate things for users.

**Comment by kt474** [comment]
will track the remaining code duplication/consolidation in #1028
