### ISSUE TITLE
QiskitRuntimeService `url` argument from env variables.

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit/qiskit-ibm-runtime#973]
**What is the expected feature or enhancement?**

Ability to construct `QiskitRuntimeService` object with `url` argument from env variable (let's say `QISKIT_AUTH_URL`).
This will enable to set auth url from env variables in different dev environments.

**Acceptance criteria**

When env variable is set one can construct `QiskitRuntimeService` class without specifying `url` argument. 

Example:
```python
print(os.environ)
# environ({"QISKIT_AUTH_URL": "https://my_awesome_url/api"})

service = QiskitRuntimeService() # same as I would call QiskitRuntimeService(url="https://my_awesome_url/api")
```

**Comment by jyu00** [comment]
We already have this env var - `QISKIT_IBM_URL`. Perhaps we need to document it better.

**Comment by kt474** [comment]
There is documentation regarding `QISKIT_IBM_URL` in [contributing.md](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/CONTRIBUTING.md#configuration) - I think this is sufficient, but we could also update the [setup-channel](https://docs.quantum.ibm.com/start/setup-channel) doc. If that's the case feel free to open this issue in https://github.com/Qiskit/documentation
