### ISSUE TITLE
Quantum gate `ry` no longer supported in manila

### ISSUE THREAD

**Issue by adrianor** [Qiskit/qiskit-ibm-runtime#980]
**Describe the bug**

Recently my circuits cannot be executed in manila because the error is returned:

Failed - Instruction ry is not supported

**Steps to reproduce**

The state preparation:

   `from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit`

    `qreg_q = QuantumRegister(4, 'q')`
    `creg_c = ClassicalRegister(4, 'c')`
    `circuit = QuantumCircuit(qreg_q, creg_c)`

   `circuit.ry(theta, qreg_q[0])`
    `circuit.p(alpha, qreg_q[0])`
    `circuit.ry(theta, qreg_q[1])`
    `circuit.p(alpha, qreg_q[1])`
    `circuit.ry(theta, qreg_q[2])` 
    `circuit.p(alpha, qreg_q[2])`
    `circuit.ry(theta, qreg_q[3])`
    `circuit.p(alpha, qreg_q[3])`

     `circuit.measure(qreg_q[3], creg_c[3])`
     `circuit.measure(qreg_q[2], creg_c[2])`
     `circuit.measure(qreg_q[1], creg_c[1])`
     `circuit.measure(qreg_q[0], creg_c[0])`

seems to fail.

**Comment by kt474** [comment]
Hi @adrianor! How are you defining your circuit? A simple circuit like the one below should work fine on manila

```
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from numpy import pi

qreg_q = QuantumRegister(2, 'q')
creg_c = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qreg_q, creg_c)

circuit.h(qreg_q[0])
circuit.ry(pi / 2, qreg_q[0])
circuit.measure(qreg_q[0], creg_c[0])
```

**Comment by adrianor** [comment]
It seems that for some reason, either qiskit or the device is failing to perform the transpilation procedure. I have now tried another different circuit, with the same state preparation as above and some extra gates and this circuit is properly transpiled into the native gate set in manila.

**Comment by adrianor** [comment]
Ah, I see.. the problem was the transpilation step:

     circuits.append(circuit)
     circuits = transpile(circuits, backend=backend, initial_layout=qubit_used)
