### ISSUE TITLE
Runtime Session fails to deserialize ndarray circuit metadata

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-ibm-runtime#984]
**Describe the bug**

When running a circuit containing a Numpy array as metadata, the returned Result object when running through a `Session` has incorrect metadata containing the non-deserialized numpy array.

**Steps to reproduce**

```python
import numpy as np
from qiskit import QuantumCircuit
from qiskit_ibm_runtime import QiskitRuntimeService, Session

qc = QuantumCircuit(1)
qc.measure_all()
qc.metadata = {"array": np.eye(2)}

# Run through session
service = QiskitRuntimeService()
session = Session(service=service, backend="ibmq_qasm_simulator")
result = session.run("circuit-runner", inputs={"circuits": [qc]}).result()

# Print metadata
print(result.results[0].header.metadata)
{'array': {'__type__': 'ndarray', '__value__': 'eJyb7BfqGxDJyFDGUK2eklqcXKRupaBuk2ahrqOgnpZfVFKUmBefX5SSChJ3S8wpTgWKF2ckFqQC+RpGOgpGmjoKtQpkAy4GMPhgz4AVfLAHAOaIHc0='}}
```

**Expected behavior**

When running the an IBM Provider backend this works as expected:

```python
from qiskit_ibm_provider import IBMProvider
provider = IBMProvider()
backend = provider.get_backend("ibmq_qasm_simulator")
result = backend.run(qc).result()

print(result.results[0].header.metadata)
{'array': array([[1., 0.],
        [0., 1.]])}
```

**Suggested solutions**

It looks like the JSON encoder is not decoding the numpy arrays when going through the runtime/circuit runner.

**Additional Information**

- **qiskit-ibm-runtime version**: 0.11.2
- **Python version**: 3.9
- **Operating system**: MacOS

**Comment by ihincks** [comment]
Hmm, I've had success with the JSON decoder for np arrays when the result is an array, it must have something to do with being in the header. @jyu00 ?

**Comment by t-imamichi** [comment]
In the case of Estimator, the server returns expectation values as a tuple of float. But circuit metadata is returned as a serialized data as Chris pointed out. I made a workaround to deserialize the metadata when decoding a job result.
#993
