### ISSUE TITLE
QiskitRuntime instructions lead to error

### ISSUE THREAD

**Issue by radescu** [Qiskit/qiskit-ibm-runtime#994]
Following the step by step instructions i get an error:

<img width="867" alt="image" src="https://github.com/Qiskit/qiskit-ibm-runtime/assets/12171505/ab371d0e-a3b0-4090-978a-7a8ca08773e2">

**Comment by nikolabintev** [comment]
Hi @radescu,

Could you please provide the source code as a snippet instead of screenshots?

**Comment by nikolabintev** [comment]
@radescu It runs with no errors for me, however, it takes forever to get the job result. What's the python version that you are using?

**Comment by jyu00** [comment]
@radescu Can you also provide the `qiskit-ibm-runtime` version you are using? I suspect this is related to some parameter being deprecated then removed a while ago.

**Comment by radescu** [comment]
```
from qiskit_ibm_runtime import QiskitRuntimeService, Session, Options, Sampler
from qiskit import QuantumCircuit

service = QiskitRuntimeService()
options = Options(optimization_level=2)
options.execution.shots = 1024  # Options can be set using auto-complete.

bell = QuantumCircuit(2)
bell.h(0)
bell.cx(0, 1)
bell.measure_all()
with Session(service=service, backend="ibmq_belem") as session:
    sampler = Sampler(session=session, options=options)
    job = sampler.run(circuits=bell)
    print(f"Job ID is {job.job_id()}")
    print(f"Job result is {job.result()}")

```
<img width="347" alt="image" src="https://github.com/Qiskit/qiskit-ibm-runtime/assets/12171505/88b42463-e940-46e8-8aec-113103b3a346">

**Comment by kt474** [comment]
Hi @radescu! You're using an outdated version of `qiskit-ibm-runtime`, upgrading to the latest version, 0.11.2 will resolve this issue
