### ISSUE TITLE
qiskit_ibm_runtime_Estimator gets unexpected keywords

### ISSUE THREAD

**Issue by lupa981** [Qiskit/qiskit-ibm-runtime#996]
### Informations

- **Qiskit version**: {'qiskit-terra': '0.24.0', 'qiskit-aer': '0.12.0', 'qiskit-ignis': None, 'qiskit-ibmq-provider': '0.20.2', 'qiskit': '0.43.0', 'qiskit-nature': '0.5.2', 'qiskit-finance': '0.3.4', 'qiskit-optimization': '0.5.0', 'qiskit-machine-learning': '0.6.0'}
- **Python version**: Python 3.10.8
- **Operating system**: Windows 10 Enterprise (Version 22H2)

### What is the current behavior?
When following the 'Variational Quantum Eigensolver with Estimator primitive' tutorial (https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/vqe_with_estimator.html), the following error occurs when running the main calculation:
![image](https://github.com/Qiskit/qiskit-metapackage/assets/132747987/0cc6edcb-dd9e-4be7-a4cb-86432176ea33)

### Steps to reproduce the problem
The problem can be reproduced by simply calling the Estimator class (independently of VQE)(https://qiskit.org/documentation/partners/qiskit_ibm_runtime/_modules/qiskit_ibm_runtime/estimator.html#Estimator). E.g. the same error arrises when running the example code provided in the Source Code

### Suggested solutions
Removing the
super().__init__(
            circuits=circuits,
            observables=observables,
            parameters=parameters,
        )
in https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/estimator.py seems to resolve the issue for me.
![image](https://github.com/Qiskit/qiskit-metapackage/assets/132747987/6775a44b-8356-4057-b68d-2db28096bb8a)

**Comment by kt474** [comment]
Hi @lupa981! Can you try upgrading to the latest version of qiskit-ibm-runtime to run the latest version of the tutorial? That should resolve this issue - If not, feel free to reopen!
